using System.Text;

namespace Puck.Cli.Formats;

/// <summary>
/// The generated <c>FormatShapes.g.cs</c> of each project that declares a format: one <see langword="const"/> string
/// per ledger entry holding that entry's shape fingerprint, so the codec that owns the format can write it in its header
/// or handshake and refuse a mismatch by name. The constants are the ledger's own digests in one spelling
/// (<c>Type.Member</c> read as <c>TypeMember</c>), written by <c>puck formats</c> and checked by <c>--check</c>; the
/// files are <c>.g.cs</c>, which the shape digest never reads, so a fingerprint never depends on the file holding it.
/// </summary>
internal static class FormatShapesFiles {
    /// <summary>The generated file's name, beside the project file that declares the formats.</summary>
    public const string FileName = "FormatShapes.g.cs";
    /// <summary>The class each file declares.</summary>
    public const string ClassName = "FormatShapes";

    /// <summary>The constant a format's fingerprint is read from.</summary>
    /// <param name="id">The format's ledger id, <c>Type.Member</c>.</param>
    /// <returns>The member name on <see cref="ClassName"/>.</returns>
    public static string ConstantOf(string id) => id.Replace(
        newValue: string.Empty,
        oldValue: "."
    );
    /// <summary>Plans every generated file: each project's constants for the formats its source files declare, each in
    /// the namespace of the file that declares it, so the codec reads <c>FormatShapes.X</c> unqualified and no namespace
    /// exists that the source did not already have.</summary>
    /// <param name="entries">The ledger's entries.</param>
    /// <param name="projectOf">Resolves a declaring file's repository-relative path to its project's directory (with a
    /// trailing slash) and the namespace the file declares.</param>
    /// <returns>Each file's repository-relative path with forward slashes and its text.</returns>
    /// <exception cref="InvalidOperationException">Two formats of one namespace spell the same constant.</exception>
    public static IReadOnlyDictionary<string, string> Plan(IReadOnlyList<FormatEntry> entries, Func<string, (string Directory, string Namespace)> projectOf) {
        var plan = new SortedDictionary<string, string>(comparer: StringComparer.Ordinal);

        foreach (var project in entries.GroupBy(keySelector: entry => projectOf(arg: entry.Source).Directory, comparer: StringComparer.Ordinal)) {
            var builder = new StringBuilder();

            builder.Append(value: "// <auto-generated/>\n");
            builder.Append(value: "// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.\n");
            builder.Append(value: "// `puck formats --check` fails when this file disagrees with the source.\n");
            builder.Append(value: "#nullable enable\n");

            foreach (var group in project.GroupBy(keySelector: entry => projectOf(arg: entry.Source).Namespace, comparer: StringComparer.Ordinal).OrderBy(keySelector: static group => group.Key, comparer: StringComparer.Ordinal)) {
                var seen = new HashSet<string>(comparer: StringComparer.Ordinal);

                builder.Append(value: $"\nnamespace {group.Key} {{\n");
                builder.Append(value: "    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.\n");
                builder.Append(value: "    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>\n");
                builder.Append(value: $"    internal static class {ClassName} {{\n");

                foreach (var entry in group.OrderBy(keySelector: static entry => entry.Id, comparer: StringComparer.Ordinal)) {
                    var constant = ConstantOf(id: entry.Id);

                    if (!seen.Add(item: constant)) {
                        throw new InvalidOperationException(message: $"'{entry.Id}' spells the constant {constant}, which another format of namespace {group.Key} already does.");
                    }

                    builder.Append(value: $"        /// <summary>The shape fingerprint of <c>{entry.Id}</c>, declared in <c>{entry.Source}</c>.</summary>\n");
                    builder.Append(value: $"        public const string {constant} = \"{entry.Shape}\";\n");
                }

                builder.Append(value: "    }\n}\n");
            }

            plan[$"{project.Key}{FileName}"] = builder.ToString();
        }

        return plan;
    }
    /// <summary>The <c>--check</c> verdict on the generated files already on disk.</summary>
    /// <param name="plan">What <see cref="Plan"/> says every file holds.</param>
    /// <param name="existing">Each tracked generated file's repository-relative path and text.</param>
    /// <returns>Every problem, each naming its fix; empty when the files hold.</returns>
    public static IReadOnlyList<string> Check(IReadOnlyDictionary<string, string> plan, IReadOnlyDictionary<string, string> existing) {
        var problems = new List<string>();

        foreach (var (path, text) in plan) {
            if (!existing.TryGetValue(
                key: path,
                value: out var recorded
            )) {
                problems.Add(item: $"unrecorded: {path} is missing; its project declares formats whose fingerprints it holds");
            } else if (!string.Equals(
                a: recorded,
                b: text,
                comparisonType: StringComparison.Ordinal
            )) {
                problems.Add(item: $"stale: {path} differs from the fingerprints the source declares now");
            }
        }
        foreach (var path in existing.Keys.Where(predicate: path => !plan.ContainsKey(key: path))) {
            problems.Add(item: $"stale: {path} belongs to a project that declares no format now");
        }

        return problems;
    }
}
