using Xunit;

namespace Puck.Analyzers.Tests;

/// <summary>
/// Exercises <see cref="InternalsVisibleToAnalyzer"/> over small compilations: a grant written as an assembly attribute
/// is refused, a grant the SDK generates from a csproj <c>&lt;InternalsVisibleTo&gt;</c> item is refused, a grant to a
/// test assembly is refused like any other, and an assembly that grants nothing passes.
/// </summary>
public sealed class InternalsVisibleToAnalyzerTests {
    private const string Id = "IVT001";
    private const string Library = "namespace Subject.Assembly;\n\npublic static class Subject {\n    internal static int Value => 1;\n}\n";

    private static AnalysisResult Run(params SourceFile[] sources) {
        var result = Harness.Analyze(
            analyzer: new InternalsVisibleToAnalyzer(),
            compilation: Harness.Compile(
                assemblyName: "Puck.Subject",
                sources: [new SourceFile(Name: "Subject.cs", Text: Library), .. sources]
            )
        );

        Assert.True(
            condition: result.CompilesCleanly,
            userMessage: result.CompilerErrorText
        );

        return result;
    }

    [Fact]
    public void AnAssemblyAttributeGrantIsRefused() {
        var result = Run(new SourceFile(
            Name: "Properties/AssemblyInfo.cs",
            Text: "using System.Runtime.CompilerServices;\n\n[assembly: InternalsVisibleTo(\"Puck.Subject.Friend\")]\n"
        ));

        var diagnostic = result.Single(id: Id);

        Assert.Equal(
            actual: diagnostic.Severity,
            expected: Microsoft.CodeAnalysis.DiagnosticSeverity.Error
        );
        Assert.StartsWith(
            actualString: diagnostic.GetMessage(),
            expectedStartString: "'Puck.Subject' grants its internals to 'Puck.Subject.Friend'"
        );
        Assert.Equal(
            actual: diagnostic.Location.SourceTree?.FilePath,
            expected: "Properties/AssemblyInfo.cs"
        );
    }
    [Fact]
    public void AGrantGeneratedFromACsprojItemIsRefused() {
        // The SDK writes a csproj <InternalsVisibleTo> item into the generated assembly-info file in this shape.
        var result = Run(new SourceFile(
            Name: "obj/Release/net10.0/Puck.Subject.AssemblyInfo.cs",
            Text: "//------------------------------------------------------------------------------\n// <auto-generated>\n//     This code was generated by a tool.\n// </auto-generated>\n//------------------------------------------------------------------------------\n\n[assembly: System.Runtime.CompilerServices.InternalsVisibleToAttribute(\"Puck.Subject.Tests\")]\n"
        ));

        Assert.StartsWith(
            actualString: result.Single(id: Id).GetMessage(),
            expectedStartString: "'Puck.Subject' grants its internals to 'Puck.Subject.Tests'"
        );
    }
    [Fact]
    public void EveryGrantIsRefusedTestAssembliesIncluded() {
        var result = Run(new SourceFile(
            Name: "Properties/AssemblyInfo.cs",
            Text: "using System.Runtime.CompilerServices;\n\n[assembly: InternalsVisibleTo(\"Puck.Subject.Tests\")]\n[assembly: InternalsVisibleTo(\"Puck.Subject.Friend, PublicKey=0024\")]\n"
        ));

        Assert.Equal(
            actual: result.WithId(id: Id).Length,
            expected: 2
        );
    }
    [Fact]
    public void AnAssemblyThatGrantsNothingPasses() {
        var result = Run(new SourceFile(
            Name: "Properties/AssemblyInfo.cs",
            Text: "using System.Reflection;\n\n[assembly: AssemblyMetadata(\"Subject\", \"Value\")]\n"
        ));

        Assert.Empty(collection: result.WithId(id: Id));
    }
}
