<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsAotCompatible>false</IsAotCompatible>
        <PuckKind>Production</PuckKind>
        <PuckLayer>Engine services</PuckLayer>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Puck.Abstractions\Puck.Abstractions.csproj" />
        <ProjectReference Include="..\Puck.Commands\Puck.Commands.csproj" />
        <ProjectReference Include="..\Puck.Maths\Puck.Maths.csproj" />
        <ProjectReference Include="..\Puck.Networking\Puck.Networking.csproj" />
        <ProjectReference Include="..\Puck.World.Schema\Puck.World.Schema.csproj" />
    </ItemGroup>
</Project>
