# Regenerate ../puck-ca-bundle.c from REAL CA roots. Prefers the WSL system cert store, falls
# back to each CA's official published download URL. Roots embedded: ISRG Root X1 (Let's Encrypt),
# DigiCert Global Root G2 + Baltimore CyberTrust Root (Azure).
#
#   pwsh -File regen-ca-bundle.ps1
#
# Part of Puck.BareMetal.
$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
$outC = Join-Path $here "..\puck-ca-bundle.c" | Resolve-Path -ErrorAction SilentlyContinue
if (-not $outC) { $outC = (Join-Path $here "..\puck-ca-bundle.c") }
$pemTmp = Join-Path $here "ca-bundle.tmp.pem"

# Fetch the roots inside WSL (system store first, official URL fallback), concatenated to a PEM.
$bash = @'
set -u
OUT="$1"; M=/usr/share/ca-certificates/mozilla; : > "$OUT"
add() {
  if [ -f "$M/$2" ]; then cat "$M/$2" >> "$OUT"; echo "  $1 <- system";
  else t="$(mktemp)"; if curl -fsS "$3" -o "$t" 2>/dev/null && grep -q 'BEGIN CERT' "$t"; then
    cat "$t" >> "$OUT"; echo "  $1 <- url"; else echo "  $1 MISSING"; fi; rm -f "$t"; fi
  echo "" >> "$OUT"
}
add "ISRG Root X1"         "ISRG_Root_X1.crt"              "https://letsencrypt.org/certs/isrgrootx1.pem"
add "DigiCert Global G2"   "DigiCert_Global_Root_G2.crt"   "https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem"
add "Baltimore CyberTrust" "Baltimore_CyberTrust_Root.crt" "https://cacerts.digicert.com/BaltimoreCyberTrustRoot.crt.pem"
echo "total certs: $(grep -c 'BEGIN CERT' "$OUT")"
'@
$wslPem = (& wsl.exe -d Ubuntu -- wslpath -a ($pemTmp -replace '\\','/')).Trim()
$bash | & wsl.exe -d Ubuntu -- bash -s -- $wslPem

$pem = Get-Content $pemTmp -Raw
$certs = ([regex]::Matches($pem, 'BEGIN CERTIFICATE')).Count
if ($certs -lt 1) { throw "no certificates fetched" }
$lines = ($pem -split "`r?`n") | ForEach-Object { '    "' + $_ + '\n"' }
$body = $lines -join "`r`n"
$out = @"
// Auto-generated by mbedtls-port/regen-ca-bundle.ps1 -- DO NOT hand-edit. Real CA trust roots
// (PEM) for the bare-metal TLS client: ISRG Root X1 (Let's Encrypt), DigiCert Global Root G2 +
// Baltimore CyberTrust Root (Azure). Sourced from the system cert store; not invented here.
// Part of the Puck.BareMetal companion.
const char g_puckCaBundle[] =
$body
    "";
const unsigned int g_puckCaBundleLen = sizeof(g_puckCaBundle);
"@
Set-Content -Path $outC -Value $out -Encoding ASCII
Remove-Item $pemTmp -Force -ErrorAction SilentlyContinue
Write-Host ("wrote " + (Resolve-Path $outC).Path + " (" + $certs + " roots)")
