// World traffic is QUIC/UDP. A single ACI group preserves the single-writer world placement.
param location string = resourceGroup().location
param name string = 'bytrcsilop000'
param image string
param identityResourceId string
param clientId string
param siloDocument string
param zoneName string = 'byteterrace.com'
@secure()
param federationKey string

resource silo 'Microsoft.ContainerInstance/containerGroups@2025-09-01' = {
  name: name
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${identityResourceId}': {}
    }
  }
  properties: {
    osType: 'Linux'
    restartPolicy: 'Always'
    imageRegistryCredentials: [
      {
        server: first(split(image, '/'))
        identity: identityResourceId
      }
    ]
    ipAddress: {
      type: 'Public'
      dnsNameLabel: name
      autoGeneratedDomainNameLabelScope: 'ResourceGroupReuse'
      ports: [{ port: 33333, protocol: 'UDP' }]
    }
    containers: [
      {
        name: 'world-silo'
        properties: {
          image: image
          ports: [{ port: 33333, protocol: 'UDP' }]
          resources: {
            requests: { cpu: 2, memoryInGB: 4 }
          }
          environmentVariables: [{ name: 'AZURE_CLIENT_ID', value: clientId }]
          volumeMounts: [
            { name: 'configuration', mountPath: '/configuration', readOnly: true }
            { name: 'state', mountPath: '/state', readOnly: false }
          ]
        }
      }
    ]
    volumes: [
      {
        name: 'configuration'
        secret: {
          'silo.json': base64(siloDocument)
          'federation.pk8': federationKey
        }
      }
      { name: 'state', emptyDir: {} }
    ]
  }
}
resource zone 'Microsoft.Network/dnsZones@2018-05-01' existing = {
  name: zoneName
}
resource record 'Microsoft.Network/dnsZones/CNAME@2018-05-01' = {
  parent: zone
  name: 'world'
  properties: {
    TTL: 300
    CNAMERecord: { cname: silo.properties.ipAddress.fqdn }
  }
}
output hostname string = silo.properties.ipAddress.fqdn
