<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Test</PuckKind>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsAotCompatible>false</IsAotCompatible>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/Puck.Audio/Puck.Audio.csproj" />
    </ItemGroup>
</Project>
