// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Cli.Automation {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldReleaseExerciseResult.CurrentSchema</c>, declared in <c>src/Puck.Cli.Release/Automation/WorldReleaseExerciseCommand.cs</c>.</summary>
        public const string WorldReleaseExerciseResultCurrentSchema = "daf2ae7865a1235e";
        /// <summary>The shape fingerprint of <c>WorldReleaseQualificationRunner.Marker</c>, declared in <c>src/Puck.Cli.Release/Automation/WorldReleaseQualificationRunner.cs</c>.</summary>
        public const string WorldReleaseQualificationRunnerMarker = "616097e9ff426e1c";
    }
}

namespace Puck.Cli.Azure {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldReleaseDeploymentStore.Schema</c>, declared in <c>src/Puck.Cli.Release/Azure/WorldReleaseDeploymentStore.cs</c>.</summary>
        public const string WorldReleaseDeploymentStoreSchema = "f7a31ac45624e93c";
    }
}
