// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.GamingBricks.Forge {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>CartridgeDocument.SchemaId</c>, declared in <c>src/Puck.GamingBricks.Forge/CartridgeDocument.cs</c>.</summary>
        public const string CartridgeDocumentSchemaId = "e688d04e540f5ea8";
    }
}
