// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Cli.Canary {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>CanaryCeilingsLedger.Format</c>, declared in <c>src/Puck.Cli.Runs/Canary/CanaryCeilingsLedger.cs</c>.</summary>
        public const string CanaryCeilingsLedgerFormat = "53728c1a0c1bbd6e";
    }
}

namespace Puck.Cli.Determinism {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>DeterminismManifest.Schema</c>, declared in <c>src/Puck.Cli.Runs/Determinism/DeterminismManifest.cs</c>.</summary>
        public const string DeterminismManifestSchema = "77e0891a6dbf676d";
        /// <summary>The shape fingerprint of <c>DeterminismStream.Version</c>, declared in <c>src/Puck.Cli.Runs/Determinism/DeterminismStream.cs</c>.</summary>
        public const string DeterminismStreamVersion = "4144962243a7a7be";
    }
}

namespace Puck.Cli.Parity {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>ParityManifestLoader.ContractSchema</c>, declared in <c>src/Puck.Cli.Runs/Parity/ParityManifestLoader.cs</c>.</summary>
        public const string ParityManifestLoaderContractSchema = "ca919f631cf14ac8";
    }
}

namespace Puck.Cli.Qualification {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>QualificationReport.SchemaVersion</c>, declared in <c>src/Puck.Cli.Runs/Qualification/QualificationReport.cs</c>.</summary>
        public const string QualificationReportSchemaVersion = "d2d9087d13f0c2c3";
        /// <summary>The shape fingerprint of <c>ReleaseProfile.SchemaVersion</c>, declared in <c>src/Puck.Cli.Runs/Qualification/ReleaseProfile.cs</c>.</summary>
        public const string ReleaseProfileSchemaVersion = "cea0019378921bc2";
    }
}
