// Generated by puck shaders generate from WorldSkyKinds. Do not edit.
using Puck.Shaders;
using Puck.SignedDistance;

namespace Puck.World.Client;

public sealed partial class WorldEnvironmentResolve {
    private static ISdfSkyParameterTable CreateSkyKindTable(WorldSkyKind kind, int count) => kind.Tag switch {
        0u => new SdfSkyParameterTable<SdfSkyAuroraData>("aurora", count),
        1u => new SdfSkyParameterTable<SdfSkyCloudsData>("clouds", count),
        2u => new SdfSkyParameterTable<SdfSkyGradientData>("gradient", count),
        3u => new SdfSkyParameterTable<SdfSkyNoiseData>("noise", count),
        4u => new SdfSkyParameterTable<SdfSkyPanoramaData>("panorama", count),
        5u => new SdfSkyParameterTable<SdfSkyPatternData>("pattern", count),
        6u => new SdfSkyParameterTable<SdfSkyStarsData>("stars", count),
        _ => throw new ArgumentException("The sky kind is absent from the generated table inventory.", nameof(kind)),
    };

    private static SkyWriter CreateSkyWriter(WorldRenderSkyLayer layer, in SkyWriterContext context) => layer switch {
        WorldRenderSkyLayer.Aurora authored => new SkyAuroraWriter(authored, context),
        WorldRenderSkyLayer.Clouds authored => new SkyCloudsWriter(authored, context),
        WorldRenderSkyLayer.Gradient authored => new SkyGradientWriter(authored, context),
        WorldRenderSkyLayer.Noise authored => new SkyNoiseWriter(authored, context),
        WorldRenderSkyLayer.Panorama authored => new SkyPanoramaWriter(authored, context),
        WorldRenderSkyLayer.Pattern authored => new SkyPatternWriter(authored, context),
        WorldRenderSkyLayer.Stars authored => new SkyStarsWriter(authored, context),
        _ => throw new ArgumentException("The sky layer is absent from the generated writer inventory.", nameof(layer)),
    };
}
