<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Production</PuckKind>
        <PuckLayer>Presentation</PuckLayer>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Puck.Abstractions\Puck.Abstractions.csproj" />
        <ProjectReference Include="..\Puck.DirectX.Presentation\Puck.DirectX.Presentation.csproj" />
        <ProjectReference Include="..\Puck.Platform\Puck.Platform.csproj" />
        <ProjectReference Include="..\Puck.Platform.Windows\Puck.Platform.Windows.csproj" />
        <ProjectReference Include="..\Puck.Vulkan.Presentation\Puck.Vulkan.Presentation.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Puck.Abstractions.Gpu" />
        <Using Include="Puck.Abstractions.Presentation" />
        <Using Include="Puck.Abstractions.Windowing" />
    </ItemGroup>
</Project>
