using System.CommandLine;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Puck.Analyzers;

namespace Puck.Cli.Ratchets;

/// <summary><c>puck lengths</c> and <c>puck comment-smells</c>: the verbs over the repository's two
/// <see cref="RatchetLedger"/>s, <c>FileLengths.json</c> and <c>CommentSmells.json</c>, which
/// <see cref="FileLengthAnalyzer"/> and <see cref="CommentSmellAnalyzer"/> read in every compilation. An analyzer sees
/// one compilation at a time, so a ledger entry whose file was deleted or moved never reaches it; each verb walks the
/// tracked tree instead and measures every file with the analyzer's own count. By default a verb rewrites its ledger
/// from the tree: it removes stale entries and lowers fallen ones, and refuses (exit 2, naming the file) to raise a
/// recorded count or record a new file. <c>--ceiling</c> lowers the ceiling and records every file over the new one
/// at its current count, and creates a missing ledger. <c>--check</c> writes nothing, reports every stale entry,
/// every recorded file that rose, and every unrecorded file over the ceiling, and exits 1 on any.</summary>
internal static class RatchetCommand {
    private static readonly Regex GeneratedName = new(
        options: RegexOptions.Compiled | RegexOptions.IgnoreCase,
        pattern: @"\.(g|generated|designer|g\.i)\.cs$"
    );
    private static readonly Gate LengthsGate = new(
        LedgerFileName: FileLengthAnalyzer.FileName,
        Measure: static text => FileLengthAnalyzer.CountLines(text: SourceText.From(text: text)),
        Measured: "is",
        Remedy: "split it",
        Unit: "line(s)",
        Verb: "lengths"
    );
    private static readonly Gate CommentSmellsGate = new(
        LedgerFileName: CommentSmellAnalyzer.FileName,
        Measure: static text => CommentSmellClassifier.CountSmells(root: CSharpSyntaxTree.ParseText(
            options: CSharpParseOptions.Default.WithLanguageVersion(version: LanguageVersion.Preview),
            text: text
        ).GetRoot()),
        Measured: "carries",
        Remedy: "rewrite or delete the comment",
        Unit: "comment smell(s)",
        Verb: "comment-smells"
    );

    // The same header heuristic the compiler uses to mark a tree generated.
    private static bool IsAutoGenerated(string text) {
        var head = text[..Math.Min(
            val1: text.Length,
            val2: 512
        )];

        return (
            head.Contains(
            comparisonType: StringComparison.OrdinalIgnoreCase,
            value: "<auto-generated"
        ) ||
            head.Contains(
            comparisonType: StringComparison.OrdinalIgnoreCase,
            value: "<autogenerated"
        )
        );
    }
    private static string Describe(Gate gate, RatchetFinding finding, int ceiling) => finding.Verdict switch {
        RatchetVerdict.Stale when (finding.Count is null) => $"stale: '{finding.Key}' is recorded at {finding.Recorded} but is not a tracked source file",
        RatchetVerdict.Stale => $"stale: '{finding.Key}' {gate.Measured} {finding.Count} {gate.Unit}, at or under the ceiling of {ceiling}, but is recorded at {finding.Recorded}",
        RatchetVerdict.Grew => $"grew: '{finding.Key}' {gate.Measured} {finding.Count} {gate.Unit}, over the {finding.Recorded} recorded; a recorded count may only fall",
        _ => $"new: '{finding.Key}' {gate.Measured} {finding.Count} {gate.Unit}, over the ceiling of {ceiling} and not recorded; {gate.Remedy} rather than recording it",
    };
    // The trees the root build compiles; experimental/ is quarantined and never reaches the analyzers.
    private static Dictionary<string, int> MeasureTree(string repositoryRoot, Gate gate) {
        var result = new Dictionary<string, int>(comparer: StringComparer.Ordinal);
        var listing = CliGit.Run(
            repositoryRoot,
            "ls-files", "-z", "--", "src/*.cs", "tests/*.cs", "build/*.cs"
        );

        if (listing.ExitCode != 0) {
            throw new InvalidOperationException(message: $"git ls-files failed: {listing.Stderr}");
        }

        foreach (var relative in listing.Stdout.Split(
            options: StringSplitOptions.RemoveEmptyEntries,
            separator: '\0'
        )) {
            if (GeneratedName.IsMatch(input: relative)) {
                continue;
            }

            var fullPath = Path.Combine(
                path1: repositoryRoot,
                path2: relative
            );

            if (!File.Exists(path: fullPath)) {
                continue;
            }

            var text = File.ReadAllText(path: fullPath);

            if (IsAutoGenerated(text: text)) {
                continue;
            }

            result[relative] = gate.Measure(arg: text);
        }

        return result;
    }
    private static int Run(Gate gate, bool check, int? ceiling) {
        if (!CliPaths.TryGetRepositoryRoot(repositoryRoot: out var repositoryRoot)) {
            return CliExit.Refused;
        }

        if (
            check &&
            ceiling.HasValue
        ) {
            return CliExit.Refuse(
                verb: gate.Verb,
                what: "--ceiling",
                why: "lowering the ceiling rewrites the ledger, so it does not combine with --check."
            );
        }

        var ledgerPath = Path.Combine(
            path1: repositoryRoot,
            path2: gate.LedgerFileName
        );
        RatchetLedger ledger;

        if (File.Exists(path: ledgerPath)) {
            if (!RatchetLedger.TryParse(
                error: out var error,
                json: File.ReadAllText(path: ledgerPath),
                ledger: out var parsed
            )) {
                return CliExit.Refuse(
                    verb: gate.Verb,
                    what: gate.LedgerFileName,
                    why: $"unusable: {error}"
                );
            }

            ledger = parsed!;
        } else if (
            !check &&
            ceiling.HasValue
        ) {
            ledger = RatchetLedger.Create(ceiling: int.MaxValue);
        } else {
            return CliExit.Refuse(
                verb: gate.Verb,
                what: gate.LedgerFileName,
                why: $"'{ledgerPath}' does not exist; --ceiling <count> creates it."
            );
        }

        if (
            ceiling.HasValue &&
            ((ceiling.Value < 0) || (ceiling.Value > ledger.Ceiling))
        ) {
            return CliExit.Refuse(
                verb: gate.Verb,
                what: $"--ceiling {ceiling.Value}",
                why: $"a ledger's ceiling only falls, and this one is {ledger.Ceiling}."
            );
        }

        var reconciliation = ledger.Reconcile(
            ceiling: ceiling,
            measured: MeasureTree(
                gate: gate,
                repositoryRoot: repositoryRoot
            )
        );

        if (check) {
            foreach (var finding in reconciliation.Findings) {
                Console.Error.WriteLine(value: $"{gate.Verb}: {Describe(
                    ceiling: reconciliation.Ceiling,
                    finding: finding,
                    gate: gate
                )}");
            }

            Console.WriteLine(value: $"{gate.Verb}: ceiling {reconciliation.Ceiling}; {ledger.RecordedCount} recorded file(s); {reconciliation.Findings.Count} problem(s).");

            return ((reconciliation.Findings.Count == 0)
                ? CliExit.Success
                : CliExit.Failed
            );
        }

        if (reconciliation.Refused) {
            _ = CliExit.Refuse(
                verb: gate.Verb,
                what: gate.LedgerFileName,
                why: "the ledger only falls, so a risen or new file over the ceiling is fixed rather than recorded; nothing written:"
            );

            foreach (var finding in reconciliation.Findings.Where(predicate: static finding => (finding.Verdict != RatchetVerdict.Stale))) {
                Console.Error.WriteLine(value: $"  {Describe(
                    ceiling: reconciliation.Ceiling,
                    finding: finding,
                    gate: gate
                )}");
            }

            return CliExit.Refused;
        }

        File.WriteAllText(
            contents: reconciliation.Render(),
            encoding: new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            path: ledgerPath
        );

        var added = reconciliation.Next.Count(predicate: pair => (ledger.TryGetRecorded(key: pair.Key) is null));
        var lowered = reconciliation.Next.Count(predicate: pair => ((ledger.TryGetRecorded(key: pair.Key) is { } recorded) && (pair.Value < recorded)));
        var removed = reconciliation.Findings.Count(predicate: static finding => (finding.Verdict == RatchetVerdict.Stale));

        Console.WriteLine(value: $"{gate.Verb}: wrote {gate.LedgerFileName} — ceiling {reconciliation.Ceiling}; {reconciliation.Next.Count} recorded file(s), {added} added, {lowered} lowered, {removed} removed.");

        return CliExit.Success;
    }
    private static Command Create(Gate gate, string description, string detail) {
        var check = CliOptions.Check(description: $"Write nothing; report every stale, risen, and unrecorded-over-ceiling file in {gate.LedgerFileName}, and exit 1 on any.");
        var ceiling = new Option<int?>(name: "--ceiling") {
            Description = $"Lower the ledger's ceiling to this count, recording every file over it at its current count; creates a missing {gate.LedgerFileName}.",
        };
        var command = new Command(
            description: description,
            name: gate.Verb
        ) { check, ceiling };

        command.SetAction(action: parseResult => Run(
            ceiling: parseResult.GetValue(option: ceiling),
            check: parseResult.GetValue(option: check),
            gate: gate
        ));
        command.Detail(detail: detail);

        return command;
    }

    /// <summary>Creates <c>puck comment-smells</c>, the verb over <c>CommentSmells.json</c>.</summary>
    /// <returns>The command.</returns>
    public static Command CreateCommentSmells() => Create(
        description: "Regenerate CommentSmells.json, the comment-smell ledger, from the tracked tree.",
        detail: """
            A file's count is its inline comments in a named smell bucket (sync-coupling,
            debt-marker, banner-divider, commented-out-code, narrative-history, dead-provenance);
            unclassified comments and XML documentation are not counted. `puck scan --only
            comment-smells` lists each comment and its bucket. The ceiling is zero, so a file the
            ledger does not record carries no smell, and a recorded count may only fall.

            By default the ledger is rewritten from the tree: stale entries (file gone, or back
            at the ceiling) are removed and fallen counts lowered. A recorded file that rose, or
            an unrecorded file over the ceiling, is refused (exit 2, naming the file) and nothing
            is written.

            Exit codes: 0 written, or clean under --check; 1 drift under --check; 2 a refused
            rise or new file, a raised ceiling, or an unusable ledger.
            """,
        gate: CommentSmellsGate
    );
    /// <summary>Creates <c>puck lengths</c>, the verb over <c>FileLengths.json</c>.</summary>
    /// <returns>The command.</returns>
    public static Command CreateLengths() => Create(
        description: "Regenerate FileLengths.json, the file-length ledger, from the tracked tree.",
        detail: """
            By default the ledger is rewritten from the tree: stale entries (file gone, or at or
            under the ceiling) are removed and shrunken ones lowered. A recorded file that grew,
            or an unrecorded file over the ceiling, is refused (exit 2, naming the file) and
            nothing is written: the ledger only shrinks. --ceiling lowers the ceiling and records
            every file over the new one at its current length.

            The line count is line breaks plus one, what the analyzer counts. Generated files
            (*.g.cs and auto-generated headers) are outside the rule, as they are for the analyzer.

            Exit codes: 0 written, or clean under --check; 1 drift under --check; 2 a refused
            growth or new file, a raised ceiling, or an unusable ledger.
            """,
        gate: LengthsGate
    );

    // One ledger's verb: its name, ledger, the analyzer's own per-file count over a file's text, and the verb, unit
    // and remedy its findings are reported in.
    private sealed record Gate(string Verb, string LedgerFileName, Func<string, int> Measure, string Measured, string Unit, string Remedy);
}
