# Rasterizes a monospace font into an 8x16 1bpp glyph table for the framebuffer console and emits
# puck-font.c. Run on Windows (uses GDI+). Prints an ASCII-art preview of a few glyphs to confirm.
#   pwsh -File regen-font.ps1
param([string]$Font = "Consolas", [int]$EmPx = 14)
Add-Type -AssemblyName System.Drawing
$first = 0x20; $last = 0x7E
$rows = 16; $cols = 8
$glyphs = @{}
$bmp = New-Object System.Drawing.Bitmap($cols, $rows)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
$fnt = New-Object System.Drawing.Font($Font, $EmPx, [System.Drawing.GraphicsUnit]::Pixel)
for ($code = $first; $code -le $last; $code++) {
  $g.Clear([System.Drawing.Color]::Black)
  $s = [char]$code
  $g.DrawString($s, $fnt, [System.Drawing.Brushes]::White, -1.0, -1.0)
  $bytes = New-Object byte[] $rows
  for ($y = 0; $y -lt $rows; $y++) {
    $b = 0
    for ($x = 0; $x -lt $cols; $x++) {
      $p = $bmp.GetPixel($x, $y)
      if (($p.R + $p.G + $p.B) -ge 200) { $b = $b -bor (1 -shl (7 - $x)) }
    }
    $bytes[$y] = $b
  }
  $glyphs[$code] = $bytes
}
# Preview a few glyphs as ASCII art.
foreach ($ch in @([int][char]'A', [int][char]'g', [int][char]'0', [int][char]'#', [int][char]':')) {
  Write-Host "--- '$([char]$ch)' ---"
  foreach ($row in $glyphs[$ch]) {
    $line = ""
    for ($x = 0; $x -lt 8; $x++) { $line += (($row -band (1 -shl (7 - $x))) ? '#' : '.') }
    Write-Host $line
  }
}
# Emit puck-font.c
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Generated by regen-font.ps1 ($Font ${EmPx}px). An 8x16 1bpp font for the framebuffer console,")
[void]$sb.AppendLine(" * printable ASCII 0x20..0x7E; each glyph is 16 rows, one byte per row, MSB = leftmost pixel. */")
[void]$sb.AppendLine("const unsigned char g_puckFont8x16[95][16] = {")
for ($code = $first; $code -le $last; $code++) {
  $hex = ($glyphs[$code] | ForEach-Object { "0x{0:x2}" -f $_ }) -join ","
  $cc = ([char]$code); if ($cc -eq '\') { $cc = "backslash" }
  [void]$sb.AppendLine("    { $hex }, /* '$cc' */")
}
[void]$sb.AppendLine("};")
$out = Join-Path $PSScriptRoot "puck-font.c"
[System.IO.File]::WriteAllText($out, $sb.ToString())
Write-Host "wrote $out"
