// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Commands {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>BindingProfileDocument.CurrentVersion</c>, declared in <c>src/Puck.Commands/BindingProfileDocument.cs</c>.</summary>
        public const string BindingProfileDocumentCurrentVersion = "903942a74dd26e78";
    }
}
