using System.CommandLine;
using Puck.SdfVm;

namespace Puck.Cli.Shaders;

/// <summary><c>puck shaders generate</c>: writes every HLSL include the C# model owns, each regenerated from the live
/// types, or under <c>--check</c> regenerates them in memory and compares, the drift shape <c>puck schema --check</c>
/// and <c>puck registry --check</c> share. Exit 0 wrote or matched, 1 check found drift, 2 missing repository
/// root.</summary>
internal static class GenerateCommand {
    // Each generated include, by its repository-relative path, and the generator that owns its text.
    private static readonly (string Path, Func<string> Generate)[] Files = [
        ($"src/Puck.SdfVm/Assets/Shaders/Sdf/{SdfIsaHlsl.FileName}", SdfIsaHlsl.Generate),
    ];

    private static int Run(bool check) {
        if (!CliPaths.TryGetRepositoryRoot(repositoryRoot: out var repositoryRoot)) {
            return 2;
        }

        var matched = true;

        foreach (var (relativePath, generate) in Files) {
            matched &= CliGeneratedFile.WriteOrCheck(
                check: check,
                detail: "",
                relativePath: relativePath,
                repositoryRoot: repositoryRoot,
                source: "the model",
                text: generate(),
                verb: "shaders generate"
            );
        }

        return (matched ? 0 : 1);
    }

    public static Command Create() => CliOptions.CheckVerb(
        checkDescription: "Regenerate every include in memory and compare against the checked-in file; write nothing, and exit 1 naming each file that differs and its first differing line.",
        description: """
        The HLSL includes the C# model owns, generated and checked.

        sdf-isa.hlsli (src/Puck.SdfVm/Assets/Shaders/Sdf) is generated by Puck.SdfVm.SdfIsaHlsl
        from the SDF instruction set in Puck.SignedDistance: the version handshake, every enum an
        instruction word carries, and the packed-layout constants the interpreter decodes words
        with. A kernel build reads the checked-in file, so a C# change to the instruction set is
        regenerated here and rebuilt.
        """,
        name: "generate",
        run: Run
    );
}
