using System.Text;
using Puck.Abstractions.Presentation;
using Puck.SignedDistance;
using Puck.World;

namespace Puck.Cli.Shaders;

/// <summary>The sky schema owns kind names, defaults and tags. These generated consumers keep the native table
/// declarations, host writer selection and shader dispatcher on that one inventory.</summary>
internal static class SkyGenerate {
    internal const string BindingsPath = "src/Puck.Shaders/Graph/SdfSkyKindBindings.Generated.cs";
    internal const string WritersPath = "src/Puck.World.Client/WorldEnvironmentResolve.SkyWriters.Generated.cs";
    internal const string DispatcherPath = "src/Puck.SdfVm/Assets/Shaders/Sdf/sky/sdf-sky-kinds.generated.hlsli";

    internal static IEnumerable<GeneratedInclude> Outputs() => [
        new(BindingsPath, Bindings),
        new(WritersPath, Writers),
        new(DispatcherPath, Dispatcher),
    ];

    internal static string Bindings() {
        var text = Header("namespace Puck.Shaders;");
        text.AppendLine("/// <summary>Native sky tables generated from the authored kind inventory.</summary>");
        text.AppendLine("public static class SdfSkyKindBindings {");
        text.AppendLine("    /// <summary>Every registered kind in stable tag order; absent kinds use the ordinary empty region.</summary>");
        text.AppendLine("    public static IReadOnlyList<SdfSkyKindBinding> All { get; } = [");
        foreach (var kind in WorldSkyKinds.All) {
            text.Append("        new(\"").Append(kind.Name).Append("\", ").Append(kind.Tag).Append("u, ");
            text.Append("ShaderInterfaceMember.ReadOnlyBuffer(group: ShaderInterfaceGroup.World, name: \"sky")
                .Append(kind.Type.Name).AppendLine("\",");
            text.Append("            structure: ShaderInterfaceStructure.From<").Append(kind.NativeRecord).AppendLine(">())),");
        }
        text.AppendLine("    ];");
        text.AppendLine("}");
        return text.ToString();
    }

    internal static string Writers() {
        var text = Header("using Puck.Shaders;\nusing Puck.SignedDistance;\n\nnamespace Puck.World.Client;");
        text.AppendLine("public sealed partial class WorldEnvironmentResolve {");
        text.AppendLine("    private static ISdfSkyParameterTable CreateSkyKindTable(WorldSkyKind kind, int count) => kind.Tag switch {");
        foreach (var kind in WorldSkyKinds.All) {
            text.Append("        ").Append(kind.Tag).Append("u => new SdfSkyParameterTable<").Append(kind.NativeRecord)
                .Append(">(\"").Append(kind.Name).AppendLine("\", count),");
        }
        text.AppendLine("        _ => throw new ArgumentException(\"The sky kind is absent from the generated table inventory.\", nameof(kind)),");
        text.AppendLine("    };");
        text.AppendLine();
        text.AppendLine("    private static SkyWriter CreateSkyWriter(WorldRenderSkyLayer layer, in SkyWriterContext context) => layer switch {");
        foreach (var kind in WorldSkyKinds.All) {
            text.Append("        WorldRenderSkyLayer.").Append(kind.Type.Name).Append(" authored => new Sky")
                .Append(kind.Type.Name).AppendLine("Writer(authored, context),");
        }
        text.AppendLine("        _ => throw new ArgumentException(\"The sky layer is absent from the generated writer inventory.\", nameof(layer)),");
        text.AppendLine("    };");
        text.AppendLine("}");
        return text.ToString();
    }

    internal static string Dispatcher() {
        var text = new StringBuilder();
        text.AppendLine("// Generated by puck shaders generate from WorldSkyKinds. Do not edit.");
        text.AppendLine("#ifndef SDF_SKY_KINDS_GENERATED_HLSLI");
        text.AppendLine("#define SDF_SKY_KINDS_GENERATED_HLSLI");
        Constants<SdfSkyMask>(text, "SDF_SKY_MASK_");
        Constants<SdfSkyBlend>(text, "SDF_SKY_BLEND_");
        Constants<SdfSkyVisibility>(text, "SDF_SKY_VISIBILITY_");
        Constants<QualityTier>(text, "SDF_SKY_QUALITY_");
        text.AppendLine("#define SDF_SKY_RUNTIME 1");
        foreach (var kind in WorldSkyKinds.All) {
            text.Append("#include \"kinds/").Append(kind.Name).AppendLine(".hlsli\"");
        }
        text.AppendLine();
        text.AppendLine("// The common wrapper admits masks, tier and inspection before dispatching any kind work.");
        text.AppendLine("float4 sdfEvaluateSkyKind(uint kind, SdfSkyContext context, uint parameterIndex, inout SdfSkyWork work) {");
        text.AppendLine("    switch (kind) {");
        foreach (var kind in WorldSkyKinds.All) {
            text.Append("        case ").Append(kind.Tag).Append("u: return sdfSkyKind").Append(kind.Type.Name)
                .AppendLine("(context, parameterIndex, work);");
        }
        text.AppendLine("        default: return 0.0;");
        text.AppendLine("    }");
        text.AppendLine("}");
        text.AppendLine("#undef SDF_SKY_RUNTIME");
        text.AppendLine("#endif");
        return text.ToString();
    }

    private static void Constants<T>(StringBuilder text, string prefix) where T : struct, Enum {
        foreach (var value in Enum.GetValues<T>()) {
            text.Append("#define ").Append(prefix).Append(value.ToString().ToUpperInvariant()).Append(' ')
                .Append(Convert.ToUInt32(value)).AppendLine("u");
        }
    }

    private static StringBuilder Header(string declaration) => new StringBuilder()
        .AppendLine("// Generated by puck shaders generate from WorldSkyKinds. Do not edit.")
        .AppendLine(declaration).AppendLine();
}
