<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Production</PuckKind>
        <PuckLayer>Engine services</PuckLayer>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Puck.Assets\Puck.Assets.csproj" />
        <ProjectReference Include="..\Puck.Maths\Puck.Maths.csproj" />
        <ProjectReference Include="..\Puck.Scripting\Puck.Scripting.csproj" />
        <ProjectReference Include="..\Puck.World.Server\Puck.World.Server.csproj" />
    </ItemGroup>
</Project>
