// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.World {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AssetChunk.Version</c>, declared in <c>src/Puck.World.Schema/CompiledWorldChunks.cs</c>.</summary>
        public const string AssetChunkVersion = "962bda5aad6c3435";
        /// <summary>The shape fingerprint of <c>CompiledWorld.FormatVersion</c>, declared in <c>src/Puck.World.Schema/CompiledWorld.cs</c>.</summary>
        public const string CompiledWorldFormatVersion = "c11d717d2aceb351";
        /// <summary>The shape fingerprint of <c>CompiledWorld.Magic</c>, declared in <c>src/Puck.World.Schema/CompiledWorld.cs</c>.</summary>
        public const string CompiledWorldMagic = "c11d717d2aceb351";
        /// <summary>The shape fingerprint of <c>DefinitionChunk.Version</c>, declared in <c>src/Puck.World.Schema/CompiledWorldChunks.cs</c>.</summary>
        public const string DefinitionChunkVersion = "962bda5aad6c3435";
        /// <summary>The shape fingerprint of <c>WorldBakePack.FormatVersion</c>, declared in <c>src/Puck.World.Schema/WorldBakePack.cs</c>.</summary>
        public const string WorldBakePackFormatVersion = "d2e03cce30cc1a53";
        /// <summary>The shape fingerprint of <c>WorldBakePack.Magic</c>, declared in <c>src/Puck.World.Schema/WorldBakePack.cs</c>.</summary>
        public const string WorldBakePackMagic = "d2e03cce30cc1a53";
        /// <summary>The shape fingerprint of <c>WorldCameraProgram.CurrentVersion</c>, declared in <c>src/Puck.World.Schema/WorldCameraProgram.cs</c>.</summary>
        public const string WorldCameraProgramCurrentVersion = "1cd1cb91bae0e6a5";
        /// <summary>The shape fingerprint of <c>WorldCounterpartAttestation.SchemaVersion</c>, declared in <c>src/Puck.World.Schema/WorldCounterpartAttestation.cs</c>.</summary>
        public const string WorldCounterpartAttestationSchemaVersion = "0b8d3db0201510b6";
        /// <summary>The shape fingerprint of <c>WorldCountersCeilings.SchemaVersion</c>, declared in <c>src/Puck.World.Schema/WorldCountersCeilings.cs</c>.</summary>
        public const string WorldCountersCeilingsSchemaVersion = "0c837ab9484f1526";
        /// <summary>The shape fingerprint of <c>WorldCountersReport.SchemaVersion</c>, declared in <c>src/Puck.World.Schema/WorldCountersReport.cs</c>.</summary>
        public const string WorldCountersReportSchemaVersion = "8e0944dc515d7ebc";
        /// <summary>The shape fingerprint of <c>WorldDefinition.SchemaVersion</c>, declared in <c>src/Puck.World.Schema/WorldDefinition.cs</c>.</summary>
        public const string WorldDefinitionSchemaVersion = "5aa274e3218a0ec1";
        /// <summary>The shape fingerprint of <c>WorldProjectionDocument.SchemaVersion</c>, declared in <c>src/Puck.World.Schema/WorldProjection.cs</c>.</summary>
        public const string WorldProjectionDocumentSchemaVersion = "a8be06c80c5ac8ec";
        /// <summary>The shape fingerprint of <c>WorldScheduleSection.ManifestSchemaId</c>, declared in <c>src/Puck.World.Schema/WorldSchedule.cs</c>.</summary>
        public const string WorldScheduleSectionManifestSchemaId = "71c50cc4cc1e463f";
        /// <summary>The shape fingerprint of <c>WorldSiloDefinition.SchemaVersion</c>, declared in <c>src/Puck.World.Schema/WorldSiloDefinition.cs</c>.</summary>
        public const string WorldSiloDefinitionSchemaVersion = "379adf01c58b1922";
    }
}
