using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

namespace Puck.World;

/// <summary>One JSON path a registered member reaches in a <c>puck.world.def.v1</c> document.</summary>
/// <param name="Path">The path from the root: <c>rules[].effects[setState].state</c>, where <c>[]</c> is a list
/// element and <c>[name]</c> a <c>$type</c> arm.</param>
/// <param name="Field">The registration the path carries.</param>
public sealed record WorldNameSite(string Path, WorldNameField Field);

public static partial class WorldNameRegistry {
    // Member names that read as a name position when their type is a plain string or string list; a member matching
    // one of these must be registered or excluded.
    private static readonly HashSet<string> NameShapedMembers = new(comparer: StringComparer.Ordinal) {
        "Name", "State", "Row", "Topology", "Pattern", "Table", "Zones", "Zone", "Rule", "From", "To", "Draw",
        "Source", "Attribute", "Occupancy", "Board", "Tokens", "Turn", "Verdict", "Legal", "Reach", "Held", "Counts",
        "Best", "Move", "Plan", "Medium", "Field", "Binding", "Template", "ForEach", "Key", "FromKey", "SetKey",
        "TargetKey", "ComparandKey", "ComparandState", "FromState", "FilterRow", "SpillRow", "ValuesFrom",
        "PhaseOf", "ScaleRow", "CapacityRow", "RangeState", "HalfAngleState", "Set", "Left", "Right", "Codes",
        "With", "Over", "Register", "Score", "Mask", "ReadersFrom", "Id", "Names",
    };
    private static readonly string[] NameShapedSuffixes = ["State", "Row", "Key", "Rule", "Table", "Pattern", "Zone", "Zones", "Topology", "Field", "Binding", "Expression"];

    private static readonly Lazy<Walk> Walked = new(valueFactory: static () => Walk.Run(fields: Fields));

    /// <summary>Gets every JSON path a registered member reaches, in document order.</summary>
    public static IReadOnlyList<WorldNameSite> Sites => Walked.Value.Sites;
    /// <summary>Gets every name-shaped member that is neither registered nor excluded, each as
    /// <c>path (Owner.Member)</c>; empty when the registry covers the model.</summary>
    public static IReadOnlyList<string> Uncovered => Walked.Value.Uncovered;

    /// <summary>Returns the uncovered members under an alternative registration list — the control a law uses to
    /// prove the check bites when a field is dropped.</summary>
    /// <param name="fields">The registrations to check the model against.</param>
    /// <returns>Every name-shaped member the list leaves neither registered nor excluded.</returns>
    public static IReadOnlyList<string> UncoveredUnder(IReadOnlyList<WorldNameField> fields) =>
        Walk.Run(fields: fields).Uncovered;

    /// <summary>Renders the registry as the Markdown document <c>docs/world-name-registry.md</c> holds.</summary>
    /// <returns>The document text, LF-terminated.</returns>
    public static string Render() {
        var walk = Walked.Value;
        var output = new StringBuilder();

        _ = output.Append(value: "# World name registry\n\n");
        _ = output.Append(value: "Generated by `puck registry` from `WorldNameRegistry` over `WorldJsonContext`; do not hand-edit.\n");
        _ = output.Append(value: "`puck registry --check` fails when this file disagrees with the model.\n\n");
        _ = output.Append(value: "Every document field that carries a state, zone, rule, table, pattern, topology, generator, field, or\n");
        _ = output.Append(value: "dynamics name. `[]` is a list element; `[name]` is a `$type` arm; `{tokens}` is an expression's postfix\n");
        _ = output.Append(value: "spelling; `{row}` is a reaction scalar's row form. A path ending in `…` re-enters a shape listed above it.\n");
        _ = output.Append(value: "An aliased import (`imports[].as`) prefixes every `Declares` site with `<alias>_` and rewrites every other\n");
        _ = output.Append(value: "role's names to match; see `src/Puck.World.Schema/README.md`.\n\n");
        _ = output.Append(value: "## Registered fields\n\n| Path | Kind | Role | Member |\n|---|---|---|---|\n");

        foreach (var site in walk.Sites) {
            _ = output.Append(value: ((site.Field.Member.Length == 0)
                ? $"| `{site.Path}` | | | re-enters `{TypeName(type: site.Field.Owner)}` |\n"
                : $"| `{site.Path}` | {site.Field.Kind} | {site.Field.Role} | `{TypeName(type: site.Field.Owner)}.{site.Field.Member}` |\n"
            ));
        }

        _ = output.Append(value: "\n## Name-shaped fields carrying no module name\n\n| Path | Member | Reason |\n|---|---|---|\n");

        foreach (var (path, owner, member, reason) in walk.Excluded) {
            _ = output.Append(value: $"| `{path}` | `{TypeName(type: owner)}.{member}` | {reason} |\n");
        }

        return output.ToString();
    }

    private static string TypeName(Type type) =>
        ((type.DeclaringType is { } outer) ? $"{TypeName(type: outer)}.{type.Name}" : type.Name);
    // Resolves a JSON property to the C# member that declares it: the metadata's own attribute provider when it
    // carries one, else the public property whose camel-cased name is the JSON name.
    internal static (Type DeclaringType, string Member) ResolveMember(JsonPropertyInfo property) {
        if (property.AttributeProvider is MemberInfo member) {
            return ((member.DeclaringType ?? property.DeclaringType), member.Name);
        }

        foreach (var candidate in property.DeclaringType.GetProperties(bindingAttr: (BindingFlags.Public | BindingFlags.Instance))) {
            if (string.Equals(a: JsonNamingPolicy.CamelCase.ConvertName(name: candidate.Name), b: property.Name, comparisonType: StringComparison.Ordinal)) {
                return ((candidate.DeclaringType ?? property.DeclaringType), candidate.Name);
            }
        }

        return (property.DeclaringType, property.Name);
    }
    // A state row is converter-backed, so its metadata lists no properties; the converter reads the record's own
    // init-able members by camel-cased name, which is what the walk reflects here.
    internal static IEnumerable<(string JsonName, Type DeclaringType, string Member, Type PropertyType)> ReflectedRowMembers(Type type) {
        foreach (var property in type.GetProperties(bindingAttr: (BindingFlags.Public | BindingFlags.Instance))) {
            if ((property.SetMethod is null) || property.IsDefined(attributeType: typeof(System.Text.Json.Serialization.JsonIgnoreAttribute), inherit: true)) {
                continue;
            }

            yield return (JsonNamingPolicy.CamelCase.ConvertName(name: property.Name), (property.DeclaringType ?? type), property.Name, property.PropertyType);
        }
    }
    /// <summary>Finds the registration for a member, or the implicit one its type carries: a
    /// <see cref="BindableScalar"/>/<see cref="BindableColor"/> member is a state binding wherever it sits.</summary>
    /// <param name="declaringType">The type the member was found on.</param>
    /// <param name="member">The member's C# name.</param>
    /// <param name="propertyType">The member's declared type.</param>
    /// <param name="field">The registration, when one applies.</param>
    /// <returns><see langword="true"/> when the member carries a name.</returns>
    public static bool TryResolve(Type declaringType, string member, Type propertyType, out WorldNameField field) {
        if (TryFind(declaringType: declaringType, member: member, field: out field)) {
            return true;
        }

        var leaf = Unwrap(type: propertyType);

        if ((leaf == typeof(BindableScalar)) || (leaf == typeof(BindableColor))) {
            field = new WorldNameField(Owner: declaringType, Member: member, Kind: WorldNameKind.State, Role: WorldNameRole.Binding);

            return true;
        }

        return false;
    }
    internal static Type Unwrap(Type type) {
        type = (Nullable.GetUnderlyingType(nullableType: type) ?? type);

        if (type.IsGenericType && (type.GetGenericTypeDefinition() == typeof(IReadOnlyList<>))) {
            return Unwrap(type: type.GetGenericArguments()[0]);
        }

        return type;
    }
    private static bool IsNameShaped(Type propertyType, string member) {
        var leaf = Unwrap(type: propertyType);

        if ((leaf == typeof(CellName)) || (leaf == typeof(ValueExpression)) || (leaf == typeof(BindableScalar)) || (leaf == typeof(BindableColor)) || (leaf == typeof(WorldLatticeScalar))) {
            return true;
        }

        if (leaf != typeof(string)) {
            return false;
        }

        if (NameShapedMembers.Contains(item: member)) {
            return true;
        }

        foreach (var suffix in NameShapedSuffixes) {
            if ((member.Length > suffix.Length) && member.EndsWith(value: suffix, comparisonType: StringComparison.Ordinal)) {
                return true;
            }
        }

        return false;
    }

    private sealed class Walk {
        private readonly IReadOnlyList<WorldNameField> m_fields;
        private readonly List<Type> m_stack = [];
        private readonly JsonSerializerOptions m_options = WorldJsonContext.Default.Options;

        public List<WorldNameSite> Sites { get; } = [];
        public List<(string Path, Type Owner, string Member, string Reason)> Excluded { get; } = [];
        public List<string> Uncovered { get; } = [];

        private Walk(IReadOnlyList<WorldNameField> fields) => m_fields = fields;

        public static Walk Run(IReadOnlyList<WorldNameField> fields) {
            var walk = new Walk(fields: fields);

            walk.VisitType(type: typeof(WorldDefinition), path: string.Empty);

            return walk;
        }

        private void VisitType(Type type, string path) {
            type = (Nullable.GetUnderlyingType(nullableType: type) ?? type);

            if (type == typeof(ValueExpression)) {
                VisitType(type: typeof(ValueExpressionTokens), path: $"{path}{{tokens}}");

                return;
            }

            if (type == typeof(WorldLatticeScalar)) {
                Record(path: $"{path}{{row}}", declaringType: typeof(WorldLatticeScalar), member: nameof(WorldLatticeScalar.Row), propertyType: typeof(string));

                return;
            }

            if (type.IsPrimitive || type.IsEnum || (type == typeof(string)) || (type == typeof(decimal))) {
                return;
            }

            JsonTypeInfo typeInfo;

            try {
                typeInfo = m_options.GetTypeInfo(type: type);
            } catch (Exception exception) when ((exception is NotSupportedException or InvalidOperationException)) {
                return;
            }

            if (m_stack.Contains(item: type)) {
                Sites.Add(item: new WorldNameSite(Path: $"{path}…", Field: new WorldNameField(Owner: type, Member: string.Empty, Kind: WorldNameKind.State, Role: WorldNameRole.Names)));

                return;
            }

            m_stack.Add(item: type);

            if (typeof(StateRow).IsAssignableFrom(c: type)) {
                foreach (var (jsonName, declaringType, member, propertyType) in ReflectedRowMembers(type: type)) {
                    var childPath = $"{path}.{jsonName}";

                    Record(path: childPath, declaringType: declaringType, member: member, propertyType: propertyType);
                    VisitType(type: propertyType, path: childPath);
                }

                m_stack.RemoveAt(index: (m_stack.Count - 1));

                return;
            }

            switch (typeInfo.Kind) {
                case JsonTypeInfoKind.Object:
                    foreach (var property in typeInfo.Properties) {
                        if (property.IsExtensionData || (property.Get is null) || (property.Set is null)) {
                            continue;
                        }

                        var (declaringType, member) = ResolveMember(property: property);
                        var childPath = ((path.Length == 0) ? property.Name : $"{path}.{property.Name}");

                        Record(path: childPath, declaringType: declaringType, member: member, propertyType: property.PropertyType);
                        VisitType(type: property.PropertyType, path: childPath);
                    }

                    if (typeInfo.PolymorphismOptions is { } polymorphism) {
                        foreach (var derived in polymorphism.DerivedTypes) {
                            VisitType(type: derived.DerivedType, path: $"{path}[{derived.TypeDiscriminator}]");
                        }
                    }

                    break;
                case JsonTypeInfoKind.Enumerable:
                    VisitType(type: typeInfo.ElementType!, path: $"{path}[]");

                    break;
                case JsonTypeInfoKind.Dictionary:
                    VisitType(type: typeInfo.ElementType!, path: $"{path}{{*}}");

                    break;
            }

            m_stack.RemoveAt(index: (m_stack.Count - 1));
        }
        private void Record(string path, Type declaringType, string member, Type propertyType) {
            if (TryFind(fields: m_fields, declaringType: declaringType, member: member, field: out var field)) {
                Sites.Add(item: new WorldNameSite(Path: path, Field: field));

                return;
            }

            var leaf = Unwrap(type: propertyType);

            if ((leaf == typeof(BindableScalar)) || (leaf == typeof(BindableColor))) {
                Sites.Add(item: new WorldNameSite(Path: path, Field: new WorldNameField(Owner: declaringType, Member: member, Kind: WorldNameKind.State, Role: WorldNameRole.Binding)));

                return;
            }

            if (leaf == typeof(WorldLatticeScalar)) {
                return;
            }

            if (ExclusionReason(declaringType: declaringType, member: member) is { } reason) {
                Excluded.Add(item: (path, declaringType, member, reason));

                return;
            }

            if (IsNameShaped(propertyType: propertyType, member: member)) {
                Uncovered.Add(item: $"{path} ({TypeName(type: declaringType)}.{member}: {Unwrap(type: propertyType).Name})");
            }
        }
    }
}
