<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>ByteTerrace.Puck.HumbleGamingDeck.Tests</PackageId>
        <PuckKind>Test</PuckKind>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsAotCompatible>false</IsAotCompatible>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <Using Include="Xunit" />
        <ProjectReference Include="../../src/Puck.HumbleGamingDeck.Post/Puck.HumbleGamingDeck.Post.csproj" />
        <Compile Include="../Shared/FormatLedgerShapes.cs" Link="FormatLedgerShapes.cs" />
    </ItemGroup>
</Project>
