# Embed a DYNAMIC musl guest + its ld-musl interpreter + its shared-library closure into GuestElf.cs
# (base64). The bare-metal loader maps the guest + ld-musl, registers each .so in the VFS, and enters
# ld-musl, which links the guest in-guest (Route A) -- the path musl static-pie can't take (no dlopen).
# Defaults to the foouser de-risk (one extra .so). For RADV pass -Main/-Libs accordingly.
#
#   pwsh -File embed-dyn.ps1 [-Main <elf>] [-Interp <ld-musl>] [-Libs @{ "/guest/path.so" = "host\file" }]
#
# Part of Puck.BareMetal.
param(
    [string]$Main = (Join-Path $PSScriptRoot "..\..\.qemu\radv\foouser"),
    [string]$Interp = (Join-Path $PSScriptRoot "..\..\.qemu\radv\ld-musl-x86_64.so.1"),
    [hashtable]$Libs = @{ "/lib/libfoo.so.1" = (Join-Path $PSScriptRoot "..\..\.qemu\radv\libfoo.so.1") }
)
$ErrorActionPreference = 'Stop'
function B64File([string]$p) {
    if (-not (Test-Path $p)) { throw "missing: $p" }
    [System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes((Resolve-Path $p)))
}

$mainBytes = [System.IO.File]::ReadAllBytes((Resolve-Path $Main))
$mainB64 = [System.Convert]::ToBase64String($mainBytes)
$interpBytes = [System.IO.File]::ReadAllBytes((Resolve-Path $Interp))
$interpB64 = [System.Convert]::ToBase64String($interpBytes)

$paths = @(); $blobs = @()
foreach ($k in $Libs.Keys) {
    $paths += '"' + $k + '"'
    $blobs += '"' + (B64File $Libs[$k]) + '"'
}
$libPathsInit = ($paths -join ", ")
$libBlobsInit = ($blobs -join ",`r`n        ")

$cs = @"
// Auto-generated by embed-dyn.ps1. A DYNAMIC musl Linux x86-64 guest + its ld-musl interpreter +
// its shared-library closure, base64-embedded. The loader maps the guest + ld-musl, registers each
// .so in the VFS (PuckVfsAddFile), and enters ld-musl, which links the guest in-guest (Route A).
//
// Part of Puck.BareMetal.
internal static class GuestElf {
    public const string Base64 =
        "$mainB64";
    public const string InterpBase64 =
        "$interpB64";
    public static readonly string[] LibPaths = { $libPathsInit };
    public static readonly string[] LibBlobs = {
        $libBlobsInit
    };
}
"@
Set-Content -Path (Join-Path $PSScriptRoot "GuestElf.cs") -Value $cs -Encoding ASCII
Write-Host "embedded dynamic guest ($($mainBytes.Length) B) + ld-musl ($($interpBytes.Length) B) + $($Libs.Count) lib(s)"
