# Compile a guest/<name>.c into a static-pie musl x86-64 binary (via WSL musl-gcc) and embed it,
# base64, into GuestElf.cs so the bare-metal loader runs a genuine toolchain ELF.
#
#   pwsh -File mkguest.ps1 <name>     # e.g. mkguest.ps1 drm
#
# Requires WSL with musl-tools (musl-gcc). Part of Puck.BareMetal.
param([Parameter(Mandatory)][string]$Name)
$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
$src = Join-Path $here "guest\$Name.c"
if (-not (Test-Path $src)) { throw "no guest source: $src" }

$work = (New-Item -ItemType Directory -Force -Path (Join-Path $here "..\.qemu")).FullName
$bin = Join-Path $work "$Name.bin"
function ConvertTo-WslPath([string]$p) {
    $full = [System.IO.Path]::GetFullPath($p)
    "/mnt/" + $full.Substring(0, 1).ToLower() + ($full.Substring(2) -replace '\\', '/')
}
$srcW = ConvertTo-WslPath $src
$binW = ConvertTo-WslPath $bin

wsl.exe -d Ubuntu musl-gcc -static-pie -Os -s -pthread "$srcW" -o "$binW"
if (-not (Test-Path $bin)) { throw "musl-gcc produced no binary" }

$bytes = [System.IO.File]::ReadAllBytes($bin)
$b64 = [System.Convert]::ToBase64String($bytes)
$cs = @"
// Auto-generated by mkguest.ps1 from guest/$Name.c via ``musl-gcc -static-pie -Os -s -pthread``.
// A real statically-linked, position-independent musl Linux x86-64 binary, base64-embedded so the
// loader can run a genuine toolchain ELF. $($bytes.Length) bytes.
//
// Part of Puck.BareMetal.
internal static class GuestElf {
    public const string Base64 =
        "$b64";
    public const string InterpBase64 = ""; // static-pie guest: no dynamic interpreter
    public static readonly string[] LibPaths = { };
    public static readonly string[] LibBlobs = { };
}
"@
Set-Content -Path (Join-Path $here "GuestElf.cs") -Value $cs -Encoding ASCII
Write-Host "embedded $Name ($($bytes.Length) bytes) into GuestElf.cs"
