// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.World.Authoring {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>CreationDocument.CurrentSchema</c>, declared in <c>src/Puck.World.Authoring/Authoring/CreationDocument.cs</c>.</summary>
        public const string CreationDocumentCurrentSchema = "dbb60db181964920";
        /// <summary>The shape fingerprint of <c>MusicDocument.CurrentSchema</c>, declared in <c>src/Puck.World.Authoring/Authoring/MusicDocument.cs</c>.</summary>
        public const string MusicDocumentCurrentSchema = "dd8b4ec0eda26fac";
    }
}
