using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using Puck.Maths;

namespace Puck.HumbleGamingBrick.Post;

/// <summary>Reads and writes <c>Expectations.json</c>, the generated per-ROM outcome ledger the corpus-wide Post
/// stages gate against. The file is generated by <c>--record</c>, sorted by (suite, path, model) so a diff shows only
/// what actually changed, and written with LF line endings.</summary>
internal static partial class ExpectationsLedger {
    private sealed class EntryDto {
        public required string Suite { get; init; }
        public required string Path { get; init; }
        public required string Model { get; init; }
        public required string Probe { get; init; }
        public required string RomHash { get; init; }
        public required string Outcome { get; init; }
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Reason { get; init; }
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public int? DiffPixels { get; init; }
    }

    [JsonSourceGenerationOptions(WriteIndented = true)]
    [JsonSerializable(typeof(EntryDto[]))]
    private sealed partial class EntryDtoJsonContext : JsonSerializerContext;

    /// <summary>Resolves <c>Expectations.json</c>'s path beside this source file, independent of the process's
    /// working directory or build-output layout.</summary>
    /// <param name="sourceFile">Supplied by the compiler; never pass explicitly.</param>
    public static string ResolvePath([CallerFilePath] string sourceFile = "") =>
        Path.Combine(
        path1: (Path.GetDirectoryName(path: sourceFile) ?? "."),
        path2: "Expectations.json"
    );
    /// <summary>Loads the ledger, keyed by (suite, path, model).</summary>
    /// <param name="path">The ledger file's path.</param>
    /// <returns>The loaded entries, or an empty ledger when the file does not exist yet.</returns>
    public static IReadOnlyDictionary<(string Suite, string Path, string Model), LedgerEntry> Load(string path) {
        if (!File.Exists(path: path)) {
            return new Dictionary<(string, string, string), LedgerEntry>();
        }

        var dtos = (JsonSerializer.Deserialize(
            json: File.ReadAllText(path: path),
            jsonTypeInfo: EntryDtoJsonContext.Default.EntryDtoArray
        ) ?? []);
        var entries = new Dictionary<(string, string, string), LedgerEntry>(capacity: dtos.Length);

        foreach (var dto in dtos) {
            var entry = new LedgerEntry(
                DiffPixels: dto.DiffPixels,
                Model: dto.Model,
                Outcome: ParseOutcome(text: dto.Outcome),
                Path: dto.Path,
                Probe: dto.Probe,
                Reason: dto.Reason,
                RomHash: dto.RomHash,
                Suite: dto.Suite
            );

            entries[entry.Key] = entry;
        }

        return entries;
    }
    /// <summary>Computes a ROM image's ledger hash.</summary>
    /// <param name="romPath">The ROM's absolute path.</param>
    /// <returns>The lowercase hexadecimal FNV-1a hash of the file's bytes.</returns>
    public static string HashRom(string romPath) =>
        Fnv1aHash.Compute(values: File.ReadAllBytes(path: romPath)).ToString(format: "x16");
    /// <summary>Renders a probe kind as the ledger's stable string form.</summary>
    public static string ProbeName(ProbeKind probe) =>
        probe switch {
            ProbeKind.ConformanceSerial => "conformance-serial",
            ProbeKind.AcceptanceFibonacci => "acceptance-fibonacci",
            ProbeKind.RegisterSignature => "register-signature",
            ProbeKind.GbMicrotest => "gb-microtest",
            ProbeKind.Screenshot => "screenshot",
            _ => throw new NotSupportedException(message: $"Unhandled probe kind '{probe}'."),
        };
    /// <summary>Writes the ledger, sorted by (suite, path, model), with LF line endings and a trailing newline.</summary>
    /// <param name="path">The ledger file's path.</param>
    /// <param name="entries">The entries to write.</param>
    public static void Save(string path, IEnumerable<LedgerEntry> entries) {
        var dtos = entries
            .OrderBy(
            keySelector: static entry => entry.Suite,
            comparer: StringComparer.Ordinal
        )
            .ThenBy(
            keySelector: static entry => entry.Path,
            comparer: StringComparer.Ordinal
        )
            .ThenBy(
            keySelector: static entry => entry.Model,
            comparer: StringComparer.Ordinal
        )
            .Select(selector: static entry => new EntryDto {
                DiffPixels = entry.DiffPixels,
                Model = entry.Model,
                Outcome = RenderOutcome(outcome: entry.Outcome),
                Path = entry.Path,
                Probe = entry.Probe,
                Reason = entry.Reason,
                RomHash = entry.RomHash,
                Suite = entry.Suite,
            })
            .ToArray();
        var json = JsonSerializer.Serialize(
            value: dtos,
            jsonTypeInfo: EntryDtoJsonContext.Default.EntryDtoArray
        ).Replace(
            oldValue: "\r\n",
            newValue: "\n"
        );

        File.WriteAllText(
            contents: (json + "\n"),
            path: path
        );
    }

    private static LedgerOutcome ParseOutcome(string text) =>
        text switch {
            "pass" => LedgerOutcome.Pass,
            "fail" => LedgerOutcome.Fail,
            "unrunnable" => LedgerOutcome.Unrunnable,
            _ => throw new InvalidDataException(message: $"Unknown ledger outcome '{text}'."),
        };
    private static string RenderOutcome(LedgerOutcome outcome) =>
        outcome switch {
            LedgerOutcome.Pass => "pass",
            LedgerOutcome.Fail => "fail",
            LedgerOutcome.Unrunnable => "unrunnable",
            _ => throw new NotSupportedException(message: $"Unhandled ledger outcome '{outcome}'."),
        };
}
