using Puck.Assets;
using Puck.Demo.Creator;
using Puck.Demo.World;

namespace Puck.Demo.Town;

/// <summary>
/// The <c>--forge-town</c> tool mode: builds "Puckton", the flagship town, as verified CONTENT — the world-scale
/// sibling of <see cref="Forge.RomForge.RunFlagshipsAsync"/>. For every town creation (<see cref="TownBuildings"/> +
/// <see cref="TownProps"/>) it asserts byte-identical regeneration against the committed
/// <c>docs/examples/creations/&lt;name&gt;.creation.json</c>, then assembles + bakes the <c>puck.world.v1</c> world
/// (<see cref="TownWorld.Build"/>) and asserts it too is byte-identical to the committed
/// <c>docs/examples/puckton.world.json</c>. Along the way it MATERIALIZES the creations into the runtime CAS store and
/// writes <c>./worlds/puckton.world.json</c> — the artifacts (gitignored runtime dirs) that a run document naming
/// <c>"world": "puckton"</c> (e.g. <c>docs/examples/overworld-town.json</c>) or the live <c>world.load puckton</c>
/// console verb load. No GPU: the town bakes no ROM.
/// <para>
/// The two determinism proofs run inline: TWO independent builds produce byte-identical world JSON (no wall-clock/RNG),
/// and the saved world reloads + re-serializes byte-identically (the committed-doctrine round-trip). A schema evolution
/// that legitimately changes the canonical bytes regenerates the committed files via <c>PUCK_TOWN_REGENERATE=1</c>
/// (narrated, then committed by a human), exactly as the flagships use <c>PUCK_FLAGSHIPS_REGENERATE=1</c>.
/// </para>
/// </summary>
public static class TownForge {
    /// <summary>Runs the town forge. Returns 0 on success; throws (loud, un-caught) on any drift or determinism break.</summary>
    /// <param name="args">The host args (unused — the town needs no GPU/backend selection).</param>
    /// <returns>The process exit code.</returns>
    public static int Run(string[] args) {
        _ = args;

        var store = new ContentAddressedStore(root: "store");

        foreach (var (name, document) in TownWorld.Creations()) {
            VerifyCreationRegeneration(document: document, name: name);

            var glyphs = (document.StampShapeCount() - (document.Shapes?.Count ?? 0));
            var signage = ((glyphs > 0) ? $" + {glyphs} engraved/embossed glyph(s)" : "");

            Console.WriteLine(value: $"town forge | {name} | {(document.Shapes?.Count ?? 0)} shape(s){signage} | regenerated byte-identical to docs/examples/creations/{name}.creation.json");
        }

        // Build twice from the same store: same creations → same content hashes → byte-identical world (determinism).
        var world = TownWorld.Build(store: store);
        var second = TownWorld.Build(store: store);

        if (!string.Equals(a: WorldDocumentStore.ToJson(document: world), b: WorldDocumentStore.ToJson(document: second), comparisonType: StringComparison.Ordinal)) {
            throw new InvalidOperationException(message: "town forge: two builds produced DIFFERENT world bytes — the town is not deterministic.");
        }

        // Materialize into ./worlds/ + the CAS 'worlds' ref (the runtime artifacts a run doc naming "world":"puckton",
        // or the world.load puckton verb, loads).
        var (savedPath, savedHash) = WorldDocumentStore.Save(document: world, name: TownWorld.Handle, store: store);
        var savedJson = File.ReadAllText(path: savedPath);

        // Round-trip: the saved bytes reload + re-serialize byte-for-byte (the bit-for-bit doctrine — a reloaded world
        // walks identically because it IS the same document, walk grid included).
        var reloaded = (WorldDocumentStore.Load(nameOrPath: savedPath)
            ?? throw new InvalidOperationException(message: "town forge: the just-saved world did not reload."));

        if (!string.Equals(a: savedJson, b: WorldDocumentStore.ToJson(document: reloaded), comparisonType: StringComparison.Ordinal)) {
            throw new InvalidOperationException(message: $"town forge: '{savedPath}' did not round-trip byte-identically — the bit-for-bit doctrine is broken.");
        }

        VerifyWorldRegeneration(savedJson: savedJson);

        var placementCount = (world.Placements?.Count ?? 0);
        var lightCount = (world.Lights?.Count ?? 0);
        var walkGrid = world.WalkGrid;

        Console.WriteLine(value: $"town forge | puckton | {placementCount} placement(s), {lightCount} light(s), walk grid {(walkGrid?.Width ?? 0)}×{(walkGrid?.Height ?? 0)} | regenerated byte-identical to docs/examples/puckton.world.json");
        Console.WriteLine(value: $"town forge | puckton | materialized: worlds/puckton.world.json + store/refs/worlds/puckton ({(savedHash ?? "no-cas")}) — walk it with: --run a document whose overworld node names \"world\": \"puckton\" (e.g. docs/examples/overworld-town.json; loaded at boot, the won intro's reveal reframes into it), or the live world.load puckton console verb; see the demo README's \"The town\"");

        return 0;
    }

    // Asserts a creation regenerates byte-identical to its committed docs/examples file (or rewrites it under
    // PUCK_TOWN_REGENERATE=1) — the CreationStore.ToJson canonical bytes, exactly the flagship proof.
    private static void VerifyCreationRegeneration(CreationDocument document, string name) {
        var path = Path.Combine(path1: "docs", path2: "examples", path3: "creations", path4: $"{name}.creation.json");

        RegenerateOrAssert(path: path, regenerated: CreationStore.ToJson(document: document), name: name);
    }

    // Asserts the saved world JSON is byte-identical to the committed docs/examples/puckton.world.json (or rewrites it
    // under PUCK_TOWN_REGENERATE=1).
    private static void VerifyWorldRegeneration(string savedJson) {
        RegenerateOrAssert(path: Path.Combine(path1: "docs", path2: "examples", path3: "puckton.world.json"), regenerated: savedJson, name: TownWorld.Handle);
    }
    private static void RegenerateOrAssert(string path, string regenerated, string name) {
        if (string.Equals(a: Environment.GetEnvironmentVariable(variable: "PUCK_TOWN_REGENERATE"), b: "1", comparisonType: StringComparison.Ordinal)) {
            _ = Directory.CreateDirectory(path: (Path.GetDirectoryName(path: path) ?? "."));
            File.WriteAllText(contents: regenerated, path: path);
            Console.WriteLine(value: $"town forge | {name} | committed content REGENERATED ({path})");

            return;
        }

        if (!File.Exists(path: path)) {
            throw new InvalidOperationException(message: $"town forge: no committed content at '{path}' to compare '{name}' against — first run with PUCK_TOWN_REGENERATE=1 to write it.");
        }

        if (!string.Equals(a: File.ReadAllText(path: path), b: regenerated, comparisonType: StringComparison.Ordinal)) {
            throw new InvalidOperationException(message: $"town forge: '{name}' regenerated DIFFERENT bytes than the committed '{path}' — the recipe drifted from its checked-in content (a deliberate schema evolution regenerates via PUCK_TOWN_REGENERATE=1).");
        }
    }
}
