using System.Numerics;

namespace Puck.Maths;

/// <summary>
/// The tiling word of a metallic-mean quasicrystal, generated by inflation for any index. The n-th metallic mean
/// <c>δₙ = (n + √(n² + 4)) / 2</c> is the quadratic irrational whose all-<c>n</c> continued fraction
/// <c>[n; n, n, …]</c> <see cref="QuadraticInflation"/> reads as the substitution matrix <c>[[n, 1], [1, 0]]</c>; the
/// two-letter substitution <c>long → longⁿ short</c>, <c>short → long</c> with that incidence matrix has a fixed point
/// that is exactly the aperiodic, never-repeating tiling. The golden case <c>n = 1</c> is the Fibonacci chain and the
/// silver case <c>n = 2</c> is the silver-mean (Pell) chain — unified here as two indices of one generator, with the
/// inflation factor <c>δₙ</c> supplied by the shared lens.
/// </summary>
/// <remarks>
/// <see cref="Word(int, Span{bool})"/> fills a run of the word — <see langword="false"/> for the short tile,
/// <see langword="true"/> for the long — as the fixed point of the substitution, so the sequence is self-similar under
/// inflation and identical on every machine. The tiles occur with frequency ratio <c>δₙ : 1</c> (long to short), the
/// right Perron eigenvector of the matrix. <see cref="InflationFactor(int)"/> is <c>δₙ</c> through
/// <see cref="QuadraticInflation.InflationFactor"/>, and <see cref="Positions(int, ReadOnlySpan{bool}, Span{FixedQ4816})"/>
/// lays the tiles on the line with the short tile as the unit and the long tile as <c>δₙ</c> — the one approximate seam,
/// the word above it is exact combinatorics. Beyond streaming, it addresses points by ring coordinate —
/// <see cref="Contains(int, long, long)"/>, <see cref="StartsLongTile(int, long, long)"/>, <see cref="Next(int, long, long)"/>,
/// <see cref="Previous(int, long, long)"/>, and <see cref="Position(int, long, long)"/> — the O(1) membership-and-traversal
/// surface the retired hand-coded golden and silver chains once carried, generalized to every index.
/// </remarks>
public static class MetallicQuasicrystal {
    /// <summary>Fills a leading run of the n-th metallic tiling word: the fixed point of <c>long → longⁿ short</c>, <c>short → long</c>.</summary>
    /// <param name="n">The metallic index; it must be positive. One is the golden (Fibonacci) word, two the silver (Pell) word.</param>
    /// <param name="tiles">Receives the tiling in physical order: <see langword="false"/> is the short tile, <see langword="true"/> the long. Every element is written.</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="n"/> is not positive.</exception>
    public static void Word(int n, Span<bool> tiles) {
        _ = Discriminant(n: n);

        // The fixed point starts with n long tiles. Avoid asking the general substitution composer to materialize an
        // n+1-element image when the requested prefix ends inside that first run (important for very large indices).
        if (tiles.Length <= n) {
            tiles.Fill(value: true);

            return;
        }

        // The metallic mean is the all-n continued fraction, whose single-term period [n] gives the substitution
        // long → longⁿ short, short → long. This is the period-[n] case of the general quadratic quasicrystal.
        QuadraticQuasicrystal.Word(p: n, q: 1L, d: (((long)n * n) + 4L), r: 2L, tiles: tiles);
    }
    /// <summary>Lays a run of the tiling word on the line, returning the start coordinate of each tile.</summary>
    /// <param name="n">The metallic index; it must be positive.</param>
    /// <param name="tiles">The tiling word — as filled by <see cref="Word(int, Span{bool})"/>.</param>
    /// <param name="positions">Receives the start coordinate of each tile, with the short tile as the unit and the long tile as <see cref="InflationFactor(int)"/>. It must be at least as long as <paramref name="tiles"/>.</param>
    /// <returns>The coordinate just past the final tile — the total length of the run.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="n"/> is not positive.</exception>
    /// <exception cref="ArgumentException"><paramref name="positions"/> is shorter than <paramref name="tiles"/>.</exception>
    /// <exception cref="OverflowException">The total length is outside the representable fixed-point range.</exception>
    public static FixedQ4816 Positions(int n, ReadOnlySpan<bool> tiles, Span<FixedQ4816> positions) {
        if (positions.Length < tiles.Length) {
            throw new ArgumentException(
                message: "the positions span must be at least as long as the tiling word",
                paramName: nameof(positions)
            );
        }

        var longTile = InflationFactor(n: n);
        var cursor = FixedQ4816.Zero;

        for (var index = 0; (index < tiles.Length); ++index) {
            positions[index] = cursor;
            cursor = checked(cursor + (tiles[index] ? longTile : FixedQ4816.One));
        }

        return cursor;
    }
    /// <summary>Returns the inflation factor <c>δₙ = (n + √(n² + 4)) / 2</c> — the long-to-short tile ratio and the self-similarity scale of the word.</summary>
    /// <param name="n">The metallic index; it must be positive.</param>
    /// <returns>The factor as a fixed-point value; the one approximate operation, read through <see cref="QuadraticInflation.InflationFactor"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="n"/> is not positive.</exception>
    public static FixedQ4816 InflationFactor(int n) {
        var d = Discriminant(n: n);

        // δₙ = n + 2/(n + √(n²+4)). At and above 2¹⁷ the positive correction is strictly below half of
        // one Q48.16 ULP, so the correctly rounded result is exactly n. This also avoids trying to represent n²+4 as a
        // Q48.16 input even though δₙ itself remains comfortably representable for every positive int n.
        if (n >= (1 << 17)) { return FixedQ4816.FromInteger(value: n); }

        // δₙ is the fundamental unit of the all-n continued fraction (n + √(n² + 4)) / 2.
        return QuadraticInflation.FromQuadraticIrrational(p: n, q: 1L, d: d, r: 2L).InflationFactor();
    }
    /// <summary>Determines whether the ring element <c>a + b·δₙ</c> is a vertex of the tiling — the O(1) membership test that addresses points by ring coordinate.</summary>
    /// <param name="n">The metallic index; it must be positive.</param>
    /// <param name="a">The integer part of the ring element.</param>
    /// <param name="b">The coefficient of <c>δₙ</c>.</param>
    /// <returns><see langword="true"/> when the element's Galois conjugate lies in the acceptance window <c>[0, wₙ)</c>. For <c>n = 1</c> this is exactly the classic golden (Fibonacci) membership test.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="n"/> is not positive.</exception>
    public static bool Contains(int n, long a, long b) {
        var d = Discriminant(n: n);

        return Contains(n: n, a: a, b: b, radicand: d);
    }
    /// <summary>Determines whether the longer tile begins at the vertex <c>a + b·δₙ</c>.</summary>
    /// <param name="n">The metallic index; it must be positive.</param>
    /// <param name="a">The integer part of the vertex.</param>
    /// <param name="b">The coefficient of <c>δₙ</c>.</param>
    /// <returns><see langword="true"/> when the tile starting here is the long one (length <c>δₙ²</c>); otherwise it is the short tile (length <c>δₙ</c>).</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="n"/> is not positive.</exception>
    public static bool StartsLongTile(int n, long a, long b) {
        var d = Discriminant(n: n);

        return StartsLongTile(n: n, a: a, b: b, radicand: d);
    }
    /// <summary>Returns the next vertex along the line — the far end of the tile that starts at <c>a + b·δₙ</c>.</summary>
    /// <param name="n">The metallic index; it must be positive.</param>
    /// <param name="a">The integer part of a vertex.</param>
    /// <param name="b">The coefficient of <c>δₙ</c>.</param>
    /// <returns>The next vertex, reached by adding <c>δₙ²</c> (a long tile) or <c>δₙ</c> (a short tile).</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="n"/> is not positive.</exception>
    /// <exception cref="OverflowException">The next vertex is outside the signed 64-bit ring-coordinate range.</exception>
    public static (long A, long B) Next(int n, long a, long b) {
        var d = Discriminant(n: n);

        // δₙ² = n·δₙ + 1, so the long step lands at (a + 1, b + n); the short step adds δₙ, landing at (a, b + 1).
        return StartsLongTile(n: n, a: a, b: b, radicand: d)
            ? (checked(a + 1L), checked(b + n))
            : (a, checked(b + 1L));
    }
    /// <summary>Returns the previous vertex along the line — the near end of the tile that ends at <c>a + b·δₙ</c>.</summary>
    /// <param name="n">The metallic index; it must be positive.</param>
    /// <param name="a">The integer part of a vertex.</param>
    /// <param name="b">The coefficient of <c>δₙ</c>.</param>
    /// <returns>The preceding vertex of the tiling.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="n"/> is not positive.</exception>
    /// <exception cref="OverflowException">The previous vertex is outside the signed 64-bit ring-coordinate range.</exception>
    public static (long A, long B) Previous(int n, long a, long b) {
        var d = Discriminant(n: n);
        var previousLongA = ((Int128)a - 1L);
        var previousLongB = ((Int128)b - n);

        // Of the two candidate predecessors, the true one is a vertex whose forward step lands on (a, b); a non-vertex
        // can also step here, so membership and the step must both be checked.
        return (
            Contains(n: n, a: previousLongA, b: previousLongB, radicand: d) &&
            StartsLongTile(n: n, a: previousLongA, b: previousLongB, radicand: d)
        )
            ? (checked((long)previousLongA), checked((long)previousLongB))
            : (a, checked(b - 1L));
    }
    /// <summary>Returns the position of the vertex <c>a + b·δₙ</c> along the line.</summary>
    /// <param name="n">The metallic index; it must be positive.</param>
    /// <param name="a">The integer part of the vertex.</param>
    /// <param name="b">The coefficient of <c>δₙ</c>.</param>
    /// <returns>The fixed-point coordinate <c>a + b·δₙ</c> — the one approximate value; membership and traversal are exact.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="n"/> is not positive, or a ring coordinate is outside the fixed-point integer range.</exception>
    /// <exception cref="OverflowException">The position is outside the representable fixed-point range.</exception>
    public static FixedQ4816 Position(int n, long a, long b) {
        var delta = InflationFactor(n: n);

        return checked(FixedQ4816.FromInteger(value: a) + (FixedQ4816.FromInteger(value: b) * delta));
    }

    /// <summary>Returns the positive discriminant <c>n² + 4</c> after validating the metallic index.</summary>
    private static long Discriminant(int n) {
        if (0 >= n) {
            throw new ArgumentOutOfRangeException(
                paramName: nameof(n),
                message: "the metallic index must be positive"
            );
        }

        return (((long)n * n) + 4L);
    }
    /// <summary>Tests membership for a possibly one-step-wider ring coordinate without narrowing it to <see cref="long"/>.</summary>
    private static bool Contains(int n, Int128 a, Int128 b, long radicand) {
        var wideN = ((Int128)n);

        // The conjugate is c = ((2a + bn) − b·√d) / 2. The density-correct acceptance-window width simplifies to
        // wₙ = (δₙ + 1)/δₙ² = (n² − n + 2 − (n − 1)·√d)/2. Thus 0 ≤ c < wₙ is exactly two
        // signs of small surds; unlike the former rationalized quotient, their products stay narrow for ordinary inputs.
        var conjugateRational = ((2 * a) + (b * wideN));

        if (SignSurd(rational: conjugateRational, coefficient: -b, radicand: radicand) < 0) { return false; }

        var residualRational = ((((wideN * wideN) - wideN) + 2) - conjugateRational);
        var residualSurd = (b - (wideN - 1));

        return (SignSurd(rational: residualRational, coefficient: residualSurd, radicand: radicand) > 0);
    }
    /// <summary>Classifies a tile without overflowing the virtual short-step candidate.</summary>
    private static bool StartsLongTile(int n, Int128 a, Int128 b, long radicand) =>
        // The short step adds δₙ, reaching (a, b + 1); when that is not a vertex the tile must be the long one instead.
        (Contains(n: n, a: a, b: (b + 1), radicand: radicand) == false);
    /// <summary>Returns the sign of <c>rational + coefficient·√radicand</c> exactly, with a fast fixed-width path.</summary>
    private static int SignSurd(Int128 rational, Int128 coefficient, long radicand) {
        if ((rational == Int128.Zero) && (coefficient == Int128.Zero)) { return 0; }
        if ((rational >= Int128.Zero) && (coefficient >= Int128.Zero)) { return 1; }
        if ((rational <= Int128.Zero) && (coefficient <= Int128.Zero)) { return -1; }

        // Opposite signs: compare rational² against radicand·coefficient². UInt128 covers the hot, ordinary-coordinate
        // path; extreme long coordinates and indices require more than 128 bits and fall back to exact BigInteger.
        var rationalMagnitude = Magnitude(value: rational);
        var coefficientMagnitude = Magnitude(value: coefficient);
        int comparison;

        if ((rationalMagnitude <= ulong.MaxValue) && (coefficientMagnitude <= ulong.MaxValue)) {
            var rationalSquare = (rationalMagnitude * rationalMagnitude);
            var coefficientSquare = (coefficientMagnitude * coefficientMagnitude);

            if (coefficientSquare <= (UInt128.MaxValue / (ulong)radicand)) {
                comparison = rationalSquare.CompareTo(coefficientSquare * (ulong)radicand);

                return SignFromSquareComparison(rationalPositive: (rational > Int128.Zero), comparison: comparison);
            }
        }

        var wideRational = ((BigInteger)rational);
        var wideCoefficient = ((BigInteger)coefficient);

        comparison = (wideRational * wideRational).CompareTo((wideCoefficient * wideCoefficient) * radicand);

        return SignFromSquareComparison(rationalPositive: (rational > Int128.Zero), comparison: comparison);
    }
    /// <summary>Returns an unsigned magnitude without overflowing at the signed minimum.</summary>
    private static UInt128 Magnitude(Int128 value) =>
        (value < Int128.Zero)
            ? ((UInt128)(-(value + Int128.One)) + UInt128.One)
            : ((UInt128)value);
    /// <summary>Restores the surd sign from the squared-magnitude comparison and the rational term's sign.</summary>
    private static int SignFromSquareComparison(bool rationalPositive, int comparison) =>
        rationalPositive
            ? ((comparison > 0) ? 1 : ((comparison < 0) ? -1 : 0))
            : ((comparison < 0) ? 1 : ((comparison > 0) ? -1 : 0));
}
