<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Test</PuckKind>
        <OutputType>Exe</OutputType>
        <IsAotCompatible>false</IsAotCompatible>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/Puck.World.Azure/Puck.World.Azure.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="../Shared/VirtualClock.cs" Link="VirtualClock.cs" />
    </ItemGroup>
</Project>
