<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Production</PuckKind>
        <PuckLayer>Optional extensions</PuckLayer>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Puck.World.Protocol\Puck.World.Protocol.csproj" />
        <ProjectReference Include="..\Puck.World.Schema\Puck.World.Schema.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Puck.State" />
    </ItemGroup>
</Project>
