// Generated by puck shaders generate from SdfIndirectLayout.
#ifndef SDF_INDIRECT_LAYOUT_HLSLI
#define SDF_INDIRECT_LAYOUT_HLSLI
static const uint SdfIndirectMaximumBounces = 4u;
static const uint SdfIndirectProbesPerBrick = 64u;
static const uint SdfIndirectBrickLevelMask = 255u;
static const uint SdfIndirectBrickClassified = 256u;
static const uint SdfIndirectProbeWords = 4u;
static const uint SdfIndirectCellWords = 3u;
static const uint SdfIndirectHitWords = 4u;
static const uint SdfIndirectProofWords = 7u;
static const uint SdfIndirectProofsPerCell = 8u;
static const uint SdfIndirectProofSlotBits = 3u;
static const uint SdfIndirectProofSlotsPerAxis = 8u;
static const uint SdfIndirectProofKeyLevelBits = 2u;
static const uint SdfIndirectTraceSteps = 64u;
static const uint SdfIndirectFeedbackSteps = 40u;
static const uint SdfIndirectLaunchSteps = 8u;
static const uint SdfIndirectSegmentSteps = 16u;
static const uint SdfIndirectClassMask = 3u;
static const uint SdfIndirectTracedShift = 4u;
static const uint SdfIndirectEpochShift = 8u;
static const uint SdfIndirectKindMask = 3u;
static const uint SdfIndirectProofMaskShift = 2u;
static const uint SdfIndirectProofLevelShift = 10u;
static const uint SdfIndirectLaunchHeightShift = 12u;
static const uint SdfIndirectLaunchHeightBits = 20u;
static const uint SdfIndirectLaunchHeightMask = 1048575u;
static const uint SdfIndirectLightingGenerations = 2u;
static const uint SdfIndirectIrradianceEdge = 8u;
static const uint SdfIndirectIrradianceTexels = 64u;
static const uint SdfIndirectSourceCount = 5u;
static const uint SdfIndirectRadianceWords = 5u;
static const uint SdfIndirectMaximumRaysPerProbe = 256u;
static const uint SdfIndirectLightRegionsPerLight = 2u;
static const uint SdfIndirectLightResolution = 512u;
static const uint SdfIndirectLightMaxMaps = 12u;
static const uint SdfIndirectLightMetadataRows = 7u;
static const uint SdfIndirectLightMarchSteps = 128u;
static const uint SdfIndirectLightMapBytes = 1048576u;
static const uint SdfIndirectAlternativeRays = 4u;
static const uint SdfIndirectAlternativeScreenSteps = 12u;
static const uint SdfIndirectAlternativeConeSteps = 24u;
static const uint SdfIndirectAlternativePhases = 4u;
static const float SdfIndirectAlternativeReach = 4;
static const float SdfIndirectAlternativeConeSlope = 0.25;
static const uint SdfIndirectNearSteps = 12u;
static const uint SdfIndirectNearPhases = 4u;
static const float SdfIndirectNearReach = 0.5;
static const uint SdfIndirectNearOutcomeNotAttempted = 0u;
static const uint SdfIndirectNearOutcomeUnresolved = 1u;
static const uint SdfIndirectNearOutcomeHit = 2u;
static const uint SdfIndirectNearOutcomeContinuation = 3u;
static const uint SdfIndirectTierOff = 0u;
static const uint SdfIndirectTierMedium = 1u;
static const uint SdfIndirectTierHigh = 2u;
static const uint SdfIndirectSourcesNone = 0u;
static const uint SdfIndirectSourcesDirect = 1u;
static const uint SdfIndirectSourcesFeedback = 2u;
static const uint SdfIndirectSourcesEmission = 4u;
static const uint SdfIndirectSourcesSky = 8u;
static const uint SdfIndirectSourcesScreens = 16u;
static const uint SdfIndirectSourcesAll = 31u;
static const uint SdfIndirectMethodCache = 0u;
static const uint SdfIndirectMethodScreen = 1u;
static const uint SdfIndirectMethodCone = 2u;
static const uint SdfIndirectClassDormant = 0u;
static const uint SdfIndirectClassActive = 1u;
static const uint SdfIndirectClassRelocated = 2u;
static const uint SdfIndirectClassInactive = 3u;
static const uint SdfIndirectKindHit = 0u;
static const uint SdfIndirectKindContinuation = 1u;
static const uint SdfIndirectKindExit = 2u;
static const uint SdfIndirectKindUnresolved = 3u;
static const uint SdfIndirectSourceDirect = 0u;
static const uint SdfIndirectSourceFeedback = 1u;
static const uint SdfIndirectSourceEmission = 2u;
static const uint SdfIndirectSourceSky = 3u;
static const uint SdfIndirectSourceScreens = 4u;
static const uint SdfIndirectPickWords = 72u;
uint sdfIndirectBrickCapacity(uint tier) { return tier == SdfIndirectTierHigh ? 512u : (tier == SdfIndirectTierMedium ? 256u : 0u); }
uint sdfIndirectProbeCapacity(uint tier) { return tier == SdfIndirectTierHigh ? 32768u : (tier == SdfIndirectTierMedium ? 16384u : 0u); }
uint sdfIndirectRaysPerProbe(uint tier) { return tier == SdfIndirectTierHigh ? 256u : (tier == SdfIndirectTierMedium ? 128u : 0u); }
uint sdfIndirectTraceBudget(uint tier) { return tier == SdfIndirectTierHigh ? 512u : (tier == SdfIndirectTierMedium ? 128u : 0u); }
uint sdfIndirectClassifyBudget(uint tier) { return tier == SdfIndirectTierHigh ? 8u : (tier == SdfIndirectTierMedium ? 4u : 0u); }
uint sdfIndirectShadeBudget(uint tier) { return tier == SdfIndirectTierHigh ? 8192u : (tier == SdfIndirectTierMedium ? 4096u : 0u); }
uint sdfIndirectReceiverProofBudget(uint tier) { return tier == SdfIndirectTierHigh ? 65536u : (tier == SdfIndirectTierMedium ? 32768u : 0u); }
uint sdfIndirectBounceLimit(uint tier) { return tier == SdfIndirectTierHigh ? 4u : (tier == SdfIndirectTierMedium ? 2u : 0u); }
uint sdfIndirectProofCapacity(uint tier) { return tier == SdfIndirectTierHigh ? 262144u : (tier == SdfIndirectTierMedium ? 131072u : 0u); }
uint sdfIndirectProbeWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 0u : (tier == SdfIndirectTierMedium ? 0u : 0u); }
uint sdfIndirectCellWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 131072u : (tier == SdfIndirectTierMedium ? 65536u : 0u); }
uint sdfIndirectHitWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 229376u : (tier == SdfIndirectTierMedium ? 114688u : 0u); }
uint sdfIndirectProofWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 33783808u : (tier == SdfIndirectTierMedium ? 8503296u : 0u); }
uint sdfIndirectRadianceProbeOffset(uint tier) { return tier == SdfIndirectTierHigh ? 0u : (tier == SdfIndirectTierMedium ? 12288u : 0u); }
uint sdfIndirectRadianceProbeCapacity(uint tier) { return tier == SdfIndirectTierHigh ? 32768u : (tier == SdfIndirectTierMedium ? 4096u : 0u); }
uint sdfIndirectRadianceWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 35618816u : (tier == SdfIndirectTierMedium ? 9420800u : 0u); }
uint sdfIndirectRadianceGenerationWords(uint tier) { return tier == SdfIndirectTierHigh ? 41943040u : (tier == SdfIndirectTierMedium ? 2621440u : 0u); }
uint sdfIndirectIrradianceWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 119504896u : (tier == SdfIndirectTierMedium ? 14663680u : 0u); }
uint sdfIndirectIrradianceGenerationWords(uint tier) { return tier == SdfIndirectTierHigh ? 10485760u : (tier == SdfIndirectTierMedium ? 5242880u : 0u); }
uint sdfIndirectPublicationWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 140476416u : (tier == SdfIndirectTierMedium ? 25149440u : 0u); }
uint sdfIndirectReceiverProofWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 140541952u : (tier == SdfIndirectTierMedium ? 25182208u : 0u); }
uint sdfIndirectWordCount(uint tier) { return tier == SdfIndirectTierHigh ? 140541954u : (tier == SdfIndirectTierMedium ? 25182210u : 0u); }
uint sdfIndirectTraceEvaluationCeiling(uint tier) { return tier == SdfIndirectTierHigh ? 3440640u : (tier == SdfIndirectTierMedium ? 860160u : 0u); }
uint sdfIndirectClassifyEvaluationCeiling(uint tier) { return tier == SdfIndirectTierHigh ? 460288u : (tier == SdfIndirectTierMedium ? 230144u : 0u); }
static const float SdfIndirectSurfaceEpsilon = 0.001;
static const float SdfIndirectRelocationAllowance = 0.45;
static const float SdfIndirectMinimumClearance = 0.1;
static const float SdfIndirectReceiverBias = 0.05;
static const float SdfIndirectPlaneTolerance = 0.1;
static const float SdfIndirectResolution = 1.52587890625E-05;
float sdfIndirectSpacing(uint tier, uint level) {
    if (tier == SdfIndirectTierHigh) {
        if (level == 0u) return 0.5;
        if (level == 1u) return 1.5;
        if (level == 2u) return 4.5;
    } else {
        if (level == 0u) return 1.5;
        if (level == 1u) return 4.5;
    }
    return 0.0;
}
float sdfIndirectReach(uint tier, uint level) {
    if (tier == SdfIndirectTierHigh) {
        if (level == 0u) return 3.0;
        if (level == 1u) return 9.0;
        if (level == 2u) return 0.0;
    } else {
        if (level == 0u) return 9.0;
        if (level == 1u) return 0.0;
    }
    return 0.0;
}
#endif
