// Generated by `puck shaders generate` from the sky's kind table (SdfSkyKindsHlsl.Kinds); regenerate it, never edit it.
#ifndef SDF_SKY_KINDS_HLSLI
#define SDF_SKY_KINDS_HLSLI

// The sky's capacities.
#define SDF_SKY_MAX_LAYERS 8u
#define SDF_SKY_VIEW_ROWS 5u
#define SDF_SKY_MAX_STOPS 4u
#define SDF_SKY_MAX_UPPER_FIELD_RUNS 2u
#define SDF_SKY_DETAIL_RUNS 3u
#define SDF_SKY_DETAIL_ATMOSPHERE 3u
#define SDF_SKY_DETAIL_INDIRECT 4u
#define SDF_SKY_DETAIL_INDIRECT_NEAR 5u

// Puck.SignedDistance.SdfSkyBlend.
#define SDF_SKY_BLEND_OVER 0u
#define SDF_SKY_BLEND_ADD 1u
#define SDF_SKY_BLEND_MULTIPLY 2u
#define SDF_SKY_BLEND_SCREEN 3u

// Puck.SignedDistance.SdfSkyMask.
#define SDF_SKY_MASK_NONE 0u
#define SDF_SKY_MASK_ELEVATION 1u
#define SDF_SKY_MASK_CONE 2u

// Puck.SignedDistance.SdfSkyVisibility.
#define SDF_SKY_VISIBILITY_NONE 0u
#define SDF_SKY_VISIBILITY_CAMERA 1u
#define SDF_SKY_VISIBILITY_LIGHTING 2u
#define SDF_SKY_VISIBILITY_BOTH 3u

// Puck.SignedDistance.SdfSkyTier.
#define SDF_SKY_TIER_LOW 0u
#define SDF_SKY_TIER_MEDIUM 1u
#define SDF_SKY_TIER_HIGH 2u

// Puck.SignedDistance.SdfSkyPatternShape.
#define SDF_SKY_PATTERN_CHECKER 0u
#define SDF_SKY_PATTERN_STRIPES 1u
#define SDF_SKY_PATTERN_GRID 2u

// Puck.SignedDistance.SdfSkyProjection.
#define SDF_SKY_PROJECTION_EQUIRECTANGULAR 0u
#define SDF_SKY_PROJECTION_OCTAHEDRAL 1u

// The kinds.
#define SDF_SKY_KIND_GRADIENT 0u
#define SDF_SKY_KIND_STARS 1u
#define SDF_SKY_KIND_CLOUDS 2u
#define SDF_SKY_KIND_AURORA 3u
#define SDF_SKY_KIND_NOISE 4u
#define SDF_SKY_KIND_PATTERN 5u
#define SDF_SKY_KIND_PANORAMA 6u
#define SDF_SKY_KIND_DISC 7u
#define SDF_SKY_KIND_PANEL 8u
#define SDF_SKY_KIND_VIEW 9u

// Whether a kind is a field kind, evaluated by the sky pass at its field extent and summarized with its run; a point
// kind is evaluated by the composite at each pixel.
bool sdfSkyKindIsField(uint kind) {
    switch (kind) {
    case SDF_SKY_KIND_GRADIENT:
    case SDF_SKY_KIND_CLOUDS:
    case SDF_SKY_KIND_AURORA:
    case SDF_SKY_KIND_NOISE:
    case SDF_SKY_KIND_PATTERN:
    case SDF_SKY_KIND_PANORAMA:
        return true;
    default:
        return false;
    }
}

// The gradient kind (SdfSkyGradient), a field kind.
struct SdfSkyGradient {
    float3 Color0;
    float Elevation0;
    float3 Color1;
    float Elevation1;
    float3 Color2;
    float Elevation2;
    float3 Color3;
    float Elevation3;
    uint Count;
};
SdfSkyGradient sdfSkyGradientOf(SdfSkyLayer layer) {
    SdfSkyGradient parameters;
    parameters.Color0 = layer.P0.xyz;
    parameters.Elevation0 = layer.P0.w;
    parameters.Color1 = layer.P1.xyz;
    parameters.Elevation1 = layer.P1.w;
    parameters.Color2 = layer.P2.xyz;
    parameters.Elevation2 = layer.P2.w;
    parameters.Color3 = layer.P3.xyz;
    parameters.Elevation3 = layer.P3.w;
    parameters.Count = asuint(layer.P4.x);
    return parameters;
}

// The stars kind (SdfSkyStars), a point kind.
struct SdfSkyStars {
    float Density;
    float Brightness;
    uint Seed;
    float TwinkleShare;
    float TwinkleDepth;
    float TwinklePhase;
    float Sparsity;
    float RadiusFraction;
    float LuminosityFloor;
    float Inset;
};
SdfSkyStars sdfSkyStarsOf(SdfSkyLayer layer) {
    SdfSkyStars parameters;
    parameters.Density = layer.P0.x;
    parameters.Brightness = layer.P0.y;
    parameters.Seed = asuint(layer.P0.z);
    parameters.TwinkleShare = layer.P0.w;
    parameters.TwinkleDepth = layer.P1.x;
    parameters.TwinklePhase = layer.P1.y;
    parameters.Sparsity = layer.P1.z;
    parameters.RadiusFraction = layer.P1.w;
    parameters.LuminosityFloor = layer.P2.x;
    parameters.Inset = layer.P2.y;
    return parameters;
}

// The clouds kind (SdfSkyClouds), a field kind.
struct SdfSkyClouds {
    float3 Color;
    float Coverage;
    float Softness;
    float Scale;
    uint Seed;
    float Curl;
    float2 DriftOffset;
    float2 ShearOffset;
    float3 LightDirection;
    float SpinAngle;
    float3 LightColor;
    float Warp;
    float Height;
    float Extinction;
    float SelfShadow;
    float SilverLining;
    float DomeRadius;
    float HorizonFade;
    float NormalTap;
    uint Octaves;
};
SdfSkyClouds sdfSkyCloudsOf(SdfSkyLayer layer) {
    SdfSkyClouds parameters;
    parameters.Color = layer.P0.xyz;
    parameters.Coverage = layer.P0.w;
    parameters.Softness = layer.P1.x;
    parameters.Scale = layer.P1.y;
    parameters.Seed = asuint(layer.P1.z);
    parameters.Curl = layer.P1.w;
    parameters.DriftOffset = layer.P2.xy;
    parameters.ShearOffset = layer.P2.zw;
    parameters.LightDirection = layer.P3.xyz;
    parameters.SpinAngle = layer.P3.w;
    parameters.LightColor = layer.P4.xyz;
    parameters.Warp = layer.P4.w;
    parameters.Height = layer.P5.x;
    parameters.Extinction = layer.P5.y;
    parameters.SelfShadow = layer.P5.z;
    parameters.SilverLining = layer.P5.w;
    parameters.DomeRadius = layer.P6.x;
    parameters.HorizonFade = layer.P6.y;
    parameters.NormalTap = layer.P6.z;
    parameters.Octaves = asuint(layer.P6.w);
    return parameters;
}

// The aurora kind (SdfSkyAurora), a field kind.
struct SdfSkyAurora {
    float3 Color;
    float Intensity;
    float3 TopColor;
    float Base;
    float Height;
    float Fold;
    float Rays;
    uint Seed;
    float Waves;
};
SdfSkyAurora sdfSkyAuroraOf(SdfSkyLayer layer) {
    SdfSkyAurora parameters;
    parameters.Color = layer.P0.xyz;
    parameters.Intensity = layer.P0.w;
    parameters.TopColor = layer.P1.xyz;
    parameters.Base = layer.P1.w;
    parameters.Height = layer.P2.x;
    parameters.Fold = layer.P2.y;
    parameters.Rays = layer.P2.z;
    parameters.Seed = asuint(layer.P2.w);
    parameters.Waves = layer.P3.x;
    return parameters;
}

// The noise kind (SdfSkyNoise), a field kind.
struct SdfSkyNoise {
    float3 ColorLow;
    float Scale;
    float3 ColorHigh;
    uint Seed;
    uint Octaves;
    float Gain;
    float Coverage;
    float Softness;
};
SdfSkyNoise sdfSkyNoiseOf(SdfSkyLayer layer) {
    SdfSkyNoise parameters;
    parameters.ColorLow = layer.P0.xyz;
    parameters.Scale = layer.P0.w;
    parameters.ColorHigh = layer.P1.xyz;
    parameters.Seed = asuint(layer.P1.w);
    parameters.Octaves = asuint(layer.P2.x);
    parameters.Gain = layer.P2.y;
    parameters.Coverage = layer.P2.z;
    parameters.Softness = layer.P2.w;
    return parameters;
}

// The pattern kind (SdfSkyPattern), a field kind.
struct SdfSkyPattern {
    float3 ColorA;
    uint Shape;
    float3 ColorB;
    float Cells;
    float Line;
    float Softness;
};
SdfSkyPattern sdfSkyPatternOf(SdfSkyLayer layer) {
    SdfSkyPattern parameters;
    parameters.ColorA = layer.P0.xyz;
    parameters.Shape = asuint(layer.P0.w);
    parameters.ColorB = layer.P1.xyz;
    parameters.Cells = layer.P1.w;
    parameters.Line = layer.P2.x;
    parameters.Softness = layer.P2.y;
    return parameters;
}

// The panorama kind (SdfSkyPanorama), a field kind.
struct SdfSkyPanorama {
    int Screen;
    uint Projection;
    float Intensity;
};
SdfSkyPanorama sdfSkyPanoramaOf(SdfSkyLayer layer) {
    SdfSkyPanorama parameters;
    parameters.Screen = asint(layer.P0.x);
    parameters.Projection = asuint(layer.P0.y);
    parameters.Intensity = layer.P0.z;
    return parameters;
}

// The disc kind (SdfSkyDisc), a point kind.
struct SdfSkyDisc {
    float3 Direction;
    float Intensity;
    float3 Color;
    float Exponent;
    float Radius;
    int Light;
    int Screen;
};
SdfSkyDisc sdfSkyDiscOf(SdfSkyLayer layer) {
    SdfSkyDisc parameters;
    parameters.Direction = layer.P0.xyz;
    parameters.Intensity = layer.P0.w;
    parameters.Color = layer.P1.xyz;
    parameters.Exponent = layer.P1.w;
    parameters.Radius = layer.P2.x;
    parameters.Light = asint(layer.P2.y);
    parameters.Screen = asint(layer.P2.z);
    return parameters;
}

// The panel kind (SdfSkyPanel), a point kind.
struct SdfSkyPanel {
    float3 Direction;
    float Intensity;
    float3 Color;
    float2 Size;
    float Blur;
};
SdfSkyPanel sdfSkyPanelOf(SdfSkyLayer layer) {
    SdfSkyPanel parameters;
    parameters.Direction = layer.P0.xyz;
    parameters.Intensity = layer.P0.w;
    parameters.Color = layer.P1.xyz;
    parameters.Size = layer.P2.xy;
    parameters.Blur = layer.P2.z;
    return parameters;
}

// The view kind (SdfSkyView), a point kind.
struct SdfSkyView {
    float3 Right;
    float Intensity;
    float3 Up;
    int ImageSlot;
    float3 Forward;
    uint Coverage;
    float4 Rect;
    float3 Fallback;
};
SdfSkyView sdfSkyViewOf(SdfSkyLayer layer) {
    SdfSkyView parameters;
    parameters.Right = layer.P0.xyz;
    parameters.Intensity = layer.P0.w;
    parameters.Up = layer.P1.xyz;
    parameters.ImageSlot = asint(layer.P1.w);
    parameters.Forward = layer.P2.xyz;
    parameters.Coverage = asuint(layer.P2.w);
    parameters.Rect = layer.P3.xyzw;
    parameters.Fallback = layer.P4.xyz;
    return parameters;
}

#endif // SDF_SKY_KINDS_HLSLI
