// Generated by puck shaders generate from SdfIndirectLayout.
#ifndef SDF_INDIRECT_LAYOUT_HLSLI
#define SDF_INDIRECT_LAYOUT_HLSLI
static const uint SdfIndirectProbesPerBrick = 64u;
static const uint SdfIndirectProbeWords = 4u;
static const uint SdfIndirectCellWords = 3u;
static const uint SdfIndirectHitWords = 4u;
static const uint SdfIndirectProofWords = 7u;
static const uint SdfIndirectProofsPerCell = 8u;
static const uint SdfIndirectProofSlotBits = 3u;
static const uint SdfIndirectProofSlotsPerAxis = 8u;
static const uint SdfIndirectProofKeyLevelBits = 2u;
static const uint SdfIndirectTraceSteps = 64u;
static const uint SdfIndirectFeedbackSteps = 40u;
static const uint SdfIndirectLaunchSteps = 8u;
static const uint SdfIndirectSegmentSteps = 16u;
static const uint SdfIndirectClassMask = 3u;
static const uint SdfIndirectTracedShift = 4u;
static const uint SdfIndirectEpochShift = 8u;
static const uint SdfIndirectKindMask = 3u;
static const uint SdfIndirectProofMaskShift = 2u;
static const uint SdfIndirectProofLevelShift = 10u;
static const uint SdfIndirectLaunchHeightShift = 12u;
static const uint SdfIndirectLaunchHeightBits = 20u;
static const uint SdfIndirectLaunchHeightMask = 1048575u;
static const uint SdfIndirectLightRegionsPerLight = 2u;
static const uint SdfIndirectLightResolution = 512u;
static const uint SdfIndirectLightMaxMaps = 12u;
static const uint SdfIndirectLightMetadataRows = 7u;
static const uint SdfIndirectLightMarchSteps = 128u;
static const uint SdfIndirectLightMapBytes = 1048576u;
static const uint SdfIndirectTierOff = 0u;
static const uint SdfIndirectTierMedium = 1u;
static const uint SdfIndirectTierHigh = 2u;
static const uint SdfIndirectClassDormant = 0u;
static const uint SdfIndirectClassActive = 1u;
static const uint SdfIndirectClassRelocated = 2u;
static const uint SdfIndirectClassInactive = 3u;
static const uint SdfIndirectKindHit = 0u;
static const uint SdfIndirectKindContinuation = 1u;
static const uint SdfIndirectKindExit = 2u;
static const uint SdfIndirectKindUnresolved = 3u;
uint sdfIndirectBrickCapacity(uint tier) { return tier == SdfIndirectTierHigh ? 512u : (tier == SdfIndirectTierMedium ? 256u : 0u); }
uint sdfIndirectProbeCapacity(uint tier) { return tier == SdfIndirectTierHigh ? 32768u : (tier == SdfIndirectTierMedium ? 16384u : 0u); }
uint sdfIndirectRaysPerProbe(uint tier) { return tier == SdfIndirectTierHigh ? 256u : (tier == SdfIndirectTierMedium ? 128u : 0u); }
uint sdfIndirectTraceBudget(uint tier) { return tier == SdfIndirectTierHigh ? 512u : (tier == SdfIndirectTierMedium ? 128u : 0u); }
uint sdfIndirectClassifyBudget(uint tier) { return tier == SdfIndirectTierHigh ? 8u : (tier == SdfIndirectTierMedium ? 4u : 0u); }
uint sdfIndirectProofCapacity(uint tier) { return tier == SdfIndirectTierHigh ? 262144u : (tier == SdfIndirectTierMedium ? 131072u : 0u); }
uint sdfIndirectProbeWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 0u : (tier == SdfIndirectTierMedium ? 0u : 0u); }
uint sdfIndirectCellWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 131072u : (tier == SdfIndirectTierMedium ? 65536u : 0u); }
uint sdfIndirectHitWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 229376u : (tier == SdfIndirectTierMedium ? 114688u : 0u); }
uint sdfIndirectProofWordOffset(uint tier) { return tier == SdfIndirectTierHigh ? 33783808u : (tier == SdfIndirectTierMedium ? 8503296u : 0u); }
uint sdfIndirectWordCount(uint tier) { return tier == SdfIndirectTierHigh ? 35618816u : (tier == SdfIndirectTierMedium ? 9420800u : 0u); }
uint sdfIndirectTraceEvaluationCeiling(uint tier) { return tier == SdfIndirectTierHigh ? 3440640u : (tier == SdfIndirectTierMedium ? 860160u : 0u); }
uint sdfIndirectClassifyEvaluationCeiling(uint tier) { return tier == SdfIndirectTierHigh ? 460288u : (tier == SdfIndirectTierMedium ? 230144u : 0u); }
static const float SdfIndirectSurfaceEpsilon = 0.001;
static const float SdfIndirectRelocationAllowance = 0.45;
static const float SdfIndirectMinimumClearance = 0.1;
static const float SdfIndirectReceiverBias = 0.05;
static const float SdfIndirectPlaneTolerance = 0.1;
static const float SdfIndirectResolution = 1.52587890625E-05;
float sdfIndirectSpacing(uint tier, uint level) {
    if (tier == SdfIndirectTierHigh) {
        if (level == 0u) return 0.5;
        if (level == 1u) return 1.5;
        if (level == 2u) return 4.5;
    } else {
        if (level == 0u) return 1.5;
        if (level == 1u) return 4.5;
    }
    return 0.0;
}
float sdfIndirectReach(uint tier, uint level) {
    if (tier == SdfIndirectTierHigh) {
        if (level == 0u) return 3.0;
        if (level == 1u) return 9.0;
        if (level == 2u) return 0.0;
    } else {
        if (level == 0u) return 9.0;
        if (level == 1u) return 0.0;
    }
    return 0.0;
}
#endif
