// Generated by `puck shaders generate` from the SDF instruction set's C# model; regenerate it, never edit it.
#ifndef SDF_ISA_HLSLI
#define SDF_ISA_HLSLI

// Puck.SignedDistance.SdfOp.
#define SDF_OP_RESET_POINT       0u
#define SDF_OP_TRANSLATE         1u
#define SDF_OP_ROTATE            2u
#define SDF_OP_SCALE             3u
#define SDF_OP_TRANSFORM_DYNAMIC 4u
#define SDF_OP_ROTATE_PLANE      5u
#define SDF_OP_ELONGATE          8u
#define SDF_OP_SHAPE_BLEND       9u
#define SDF_OP_REPEAT            11u
#define SDF_OP_REPEAT_LIMITED    12u
#define SDF_OP_ONION             16u
#define SDF_OP_DILATE            17u
#define SDF_OP_WALLPAPER_FOLD    18u
#define SDF_OP_LOG_SPHERE        21u
#define SDF_OP_CELL_JITTER       22u
#define SDF_OP_REPEAT_POLAR      23u
#define SDF_OP_DISPLACE          24u
#define SDF_OP_DOMAIN_WARP       25u
#define SDF_OP_SYMMETRY_PLANE    26u
#define SDF_OP_PUSH_FIELD        27u
#define SDF_OP_POP_FIELD         28u
#define SDF_OP_NOISE_DISPLACE    29u
#define SDF_OP_AXIAL_PROFILE     30u
#define SDF_OP_SHEAR             31u
#define SDF_OP_GAUSSIAN_PUSH     32u
#define SDF_OP_LANE_ERODE        34u
#define SDF_OP_CELL_DISPLACE     35u

// Puck.SignedDistance.SdfShapeType.
#define SDF_SHAPE_BOX                 0u
#define SDF_SHAPE_CAPSULE             1u
#define SDF_SHAPE_SPHERE              2u
#define SDF_SHAPE_TORUS               3u
#define SDF_SHAPE_CYLINDER            4u
#define SDF_SHAPE_PLANE               5u
#define SDF_SHAPE_VESICA              7u
#define SDF_SHAPE_ROUNDED_RECTANGLE   8u
#define SDF_SHAPE_REGULAR_POLYGON     9u
#define SDF_SHAPE_STAR                10u
#define SDF_SHAPE_ROUND_CONE          11u
#define SDF_SHAPE_TRAPEZOID           12u
#define SDF_SHAPE_ELLIPSE             13u
#define SDF_SHAPE_SCREEN_SLAB         14u
#define SDF_SHAPE_GLYPH               15u
#define SDF_SHAPE_SAMPLED_REGION      16u
#define SDF_SHAPE_CHAMFERED_RECTANGLE 17u
#define SDF_SHAPE_SUPERELLIPSOID      18u
#define SDF_SHAPE_CONVEX_POLYGON      19u
#define SDF_SHAPE_SWEEP               20u
#define SDF_SHAPE_PATH                21u

// Puck.SignedDistance.SdfBlendOp.
#define SDF_BLEND_UNION                0u
#define SDF_BLEND_SMOOTH_UNION         1u
#define SDF_BLEND_SUBTRACTION          2u
#define SDF_BLEND_INTERSECTION         3u
#define SDF_BLEND_XOR                  4u
#define SDF_BLEND_SMOOTH_INTERSECTION  5u
#define SDF_BLEND_SMOOTH_SUBTRACTION   6u
#define SDF_BLEND_CHAMFER_UNION        7u
#define SDF_BLEND_CHAMFER_INTERSECTION 8u
#define SDF_BLEND_CHAMFER_SUBTRACTION  9u
#define SDF_BLEND_GROOVE_UNION         10u
#define SDF_BLEND_PIPE_UNION           11u
#define SDF_BLEND_MORPH                12u
#define SDF_BLEND_GROOVE_SUBTRACTION   13u
#define SDF_BLEND_PIPE_SUBTRACTION     14u
#define SDF_BLEND_STAIRS_UNION         15u
#define SDF_BLEND_STAIRS_SUBTRACTION   16u

// Puck.SignedDistance.SdfLift.
#define SDF_LIFT_REVOLVE 0u
#define SDF_LIFT_EXTRUDE 1u

// Puck.SignedDistance.SdfNoiseFlavor.
#define SDF_NOISE_WHITE    0u
#define SDF_NOISE_BLUE     1u
#define SDF_NOISE_GAUSSIAN 2u

// Puck.SignedDistance.SdfCellMode.
#define SDF_CELL_MODE_F1          0u
#define SDF_CELL_MODE_F2_MINUS_F1 1u

// Puck.SignedDistance.SdfAxis.
#define SDF_AXIS_X 0u
#define SDF_AXIS_Y 1u
#define SDF_AXIS_Z 2u

// Puck.SignedDistance.SdfPlane.
#define SDF_PLANE_XZ 0u
#define SDF_PLANE_XY 1u
#define SDF_PLANE_YZ 2u

// Puck.SignedDistance.SdfWallpaperGroup.
#define SDF_WPG_P1   0u
#define SDF_WPG_P2   1u
#define SDF_WPG_PM   2u
#define SDF_WPG_PG   3u
#define SDF_WPG_CM   4u
#define SDF_WPG_PMM  5u
#define SDF_WPG_PMG  6u
#define SDF_WPG_PGG  7u
#define SDF_WPG_CMM  8u
#define SDF_WPG_P4   9u
#define SDF_WPG_P4M  10u
#define SDF_WPG_P4G  11u
#define SDF_WPG_P3   12u
#define SDF_WPG_P3M1 13u
#define SDF_WPG_P31M 14u
#define SDF_WPG_P6   15u
#define SDF_WPG_P6M  16u

// The program header, the first vector of the word stream: the vectors before the instruction headers, and each lane's accessor.
#define SDF_PROGRAM_HEADER_VECTORS       1u
#define SDF_PROGRAM_INSTRUCTION_COUNT(v) ((v).x)
#define SDF_PROGRAM_MATERIAL_COUNT(v)    ((v).y)
#define SDF_PROGRAM_DATA_OFFSET(v)       ((v).z)
#define SDF_PROGRAM_MATERIAL_OFFSET(v)   ((v).w)

// An instruction: its header's lane accessors, and the data vectors each instruction holds in the data table.
#define SDF_INSTRUCTION_OP(v)        ((v).x)
#define SDF_INSTRUCTION_SHAPE(v)     ((v).y)
#define SDF_INSTRUCTION_BLEND(v)     ((v).z)
#define SDF_INSTRUCTION_MATERIAL(v)  ((v).w)
#define SDF_INSTRUCTION_DATA_VECTORS 2u

// The bound records and the directories: a record's vectors, a directory's header vectors, and its header's lane accessors.
#define SDF_BOUND_RECORD_VECTORS         2u
#define SDF_DIRECTORY_HEADER_VECTORS     1u
#define SDF_SEGMENT_COUNT(v)             ((v).x)
#define SDF_SEGMENT_STEP_SCALE(v)        ((v).y)
#define SDF_SEGMENT_RIGID_PLAN_OFFSET(v) ((v).z)
#define SDF_INSTANCE_COUNT(v)            ((v).x)
#define SDF_INSTANCE_PART_PROGRAMS(v)    ((v).y)
#define SDF_INSTANCE_FLAGS(v)            ((v).z)
#define SDF_WORLD_SEGMENT_COUNT(v)       ((v).x)

// Shape-lane flags and the type mask on a ShapeBlend instruction's header.
#define SDF_SHAPE_DETAIL_FLAG       0x80000000u
#define SDF_SHAPE_NO_SECONDARY_FLAG 0x40000000u
#define SDF_SHAPE_TYPE_MASK         0x3FFFFFFFu

// Bound modes, and the flags and masks packed beside them in bound, segment and instance records.
#define SDF_BOUND_NONE                      0u
#define SDF_BOUND_STATIC                    1u
#define SDF_BOUND_DYNAMIC                   2u
#define SDF_SEGMENT_RIGID_PLAN              0x80000000u
#define SDF_SEGMENT_BOUND_MASK              0x000000FFu
#define SDF_INSTANCE_SHADOW_TRANSPARENT_BIT 0x80000000u
#define SDF_INSTANCE_CAMERA_HIDDEN_BIT      0x40000000u
#define SDF_INSTANCE_SEGMENT_END_MASK       0x3FFFFFFFu
#define SDF_NO_DETAIL_SHAPES_FLAG           0x00000001u

// The rigid-leaf plan.
#define SDF_RIGID_LEAF_IDENTITY_ROTATION 0x80000000u
#define SDF_RIGID_LEAF_FOLDED            0x40000000u
#define SDF_RIGID_LEAF_SHAPE_MASK        0x3FFFFFFFu
#define SDF_RIGID_LEAF_MAX_FOLD_RUN      8u

// The sampled-region shape's packed dims.
#define SDF_SAMPLED_REGION_DIM_MASK 0x000003FFu

// Program capacities, strides and floors.
#define SDF_MAX_INSTANCES              65536u
#define SDF_MATERIAL_VECTORS_PER_ENTRY 20u
#define SDF_GRID_HEADER_WORDS          16u
#define SDF_GRID_MAX_DIM               64u
#define SDF_MAX_FIELD_SCOPE_DEPTH      1u
#define SDF_FLARE_MIN_SCALE            0.05
#define SDF_LANE_ERODE_RAGGED_AMOUNT   0.35
#define SDF_SCREEN_MATERIAL            65535
#define SDF_MAX_SCREEN_SURFACES        32u
#define SDF_MINIMUM_NEAR               0.02
#define SDF_NOISE_PERIOD_CELLS         4096u

// Puck.Abstractions.Gpu.GpuSamplerFilter.
#define SDF_FILTER_NEAREST 0u
#define SDF_FILTER_LINEAR  1u

// Puck.SdfVm.GridOverlayFlags.
#define SDF_GRID_NONE    0u
#define SDF_GRID_WORLD   1u
#define SDF_GRID_OBJECT  2u
#define SDF_GRID_SURFACE 4u

// Puck.SignedDistance.SdfLightKind.
#define SDF_LIGHT_DIRECTIONAL 0u
#define SDF_LIGHT_RIM         1u
#define SDF_LIGHT_POINT       2u
#define SDF_LIGHT_OCCLUDER    3u

// Puck.SdfVm.SdfVisibilityKind.
#define SDF_VISIBILITY_KIND_BACKGROUND 0u
#define SDF_VISIBILITY_KIND_SDF        1u
#define SDF_VISIBILITY_KIND_MESH       2u

// The visibility record's identity fields, transform-slot lane and currency box (SdfVisibility).
#define SDF_VISIBILITY_KIND_SHIFT             30u
#define SDF_VISIBILITY_SOURCE_MASK            0x3FFFFFFFu
#define SDF_TRANSFORM_SLOT_NONE               -1
#define SDF_VISIBILITY_BOX_EDGE               8u
#define SDF_VISIBILITY_AMBIENT_QUERIES_WORD   9u
#define SDF_VISIBILITY_SHADOW_QUERIES_WORD    10u
#define SDF_VISIBILITY_CURRENT(pixel, bounds) (((pixel).x >= ((bounds)[0] * SDF_VISIBILITY_BOX_EDGE)) && ((pixel).y >= ((bounds)[1] * SDF_VISIBILITY_BOX_EDGE)) && ((pixel).x < ((bounds)[2] * SDF_VISIBILITY_BOX_EDGE)) && ((pixel).y < ((bounds)[3] * SDF_VISIBILITY_BOX_EDGE)))
#define SDF_SHADOW_BITS                       8u
#define SDF_SHADOW_MASK                       0x000000FFu
#define SDF_SHADOW_SLOTS                      4u
#define SDF_SHADOW_FADE_CAPACITY              2u

// The packed transform-slot word a rigid segment and a part binding store (SdfProgram.PackTransformSlot).
#define SDF_TRANSFORM_SLOT_STATIC_WORD  0u
#define SDF_TRANSFORM_SLOT_UNPACK(word) ((int)(word) + SDF_TRANSFORM_SLOT_NONE)

#endif // SDF_ISA_HLSLI
