using System.Numerics;

namespace Puck.Maths;

/// <summary>
/// Digital <c>(0, m, 2)</c>-nets over the two-element field: an index-to-point map whose stratification is a theorem
/// rather than a measurement. Every point is the exclusive-or of the direction vectors selected by the set bits of its
/// index, so a point is a pure function of that index — stateless, seekable, and pure integer, with no accumulator to
/// snapshot and no rounding to disagree about.
/// </summary>
/// <remarks>
/// <para>
/// The construction is Sobol's: dimension zero is the radical-inverse (van der Corput)
/// matrix — plain bit reversal — and each further dimension is generated by a linear recurrence whose characteristic
/// polynomial is primitive over the two-element field. Two such dimensions form a <c>(0, 2)</c>-sequence: for every
/// <c>m</c>, the first <c>2^m</c> points place exactly one point in every dyadic box of area <c>2^-m</c>. That is what
/// distinguishes this from <see cref="LowDiscrepancy"/>'s additive recurrences, which equidistribute but stratify
/// nothing exactly.
/// </para>
/// <para>
/// Two randomizations preserve the net property exactly, which is why they are the only ones offered. A digital shift —
/// exclusive-or by a fixed vector — is an affine bijection of the coordinate's bits, so it
/// carries dyadic boxes onto dyadic boxes of the same shape and the one-point-per-box count survives. Re-indexing
/// through <see cref="NestedDyadicPermutation"/> carries an aligned block of <c>2^m</c> indices onto an aligned block
/// of <c>2^m</c> indices, and every such block of a <c>(0, 2)</c>-sequence is itself a <c>(0, m, 2)</c>-net, so a
/// consumer's own first <c>2^m</c> draws are stratified whatever its salt. An arbitrary mixing bijection does neither
/// and is not offered.
/// </para>
/// </remarks>
public static class DigitalNetSampler {
    /// <summary>The number of direction numbers one dimension carries, which is the coordinate's bit count.</summary>
    public const int DirectionNumberCount = 32;
    /// <summary>The number of direction numbers the two-dimensional net carries, dimension zero first.</summary>
    public const int PlaneDirectionNumberCount = (2 * DirectionNumberCount);
    /// <summary>Separates the two coordinates' digital shifts when both are derived from one key.</summary>
    private const uint ScrambleSeparation = 0xA5A5A5A5U;
    /// <summary>The odd stride that separates streams before they are mixed; odd, so stream indexing stays injective.</summary>
    private const uint StreamStride = 0x9E3779B9U;

    /// <summary>Gets the generator of the net's second dimension, the primitive polynomial <c>t + 1</c>.</summary>
    /// <remarks>Degree one is the smallest generator there is, and it is exactly what a <c>(0, 2)</c>-sequence needs; its direction matrix is Pascal's triangle modulo two.</remarks>
    public static BinaryPolynomial PlaneGenerator => new(bits: 0b11UL);

    /// <summary>Writes the radical-inverse direction numbers, which are the net's dimension zero.</summary>
    /// <param name="destination">Receives exactly <see cref="DirectionNumberCount"/> direction numbers, lowest index bit first.</param>
    /// <remarks>The matrix is the anti-diagonal, so the coordinate is the index with its bits reversed — the van der Corput sequence, written as a digital net.</remarks>
    /// <exception cref="ArgumentException"><paramref name="destination"/> is not <see cref="DirectionNumberCount"/> long.</exception>
    public static void BuildBitReversalDirectionNumbers(Span<uint> destination) {
        if (DirectionNumberCount != destination.Length) {
            throw new ArgumentException(message: $"A dimension's direction numbers occupy exactly {DirectionNumberCount} words.", paramName: nameof(destination));
        }

        for (var index = 0; (index < DirectionNumberCount); ++index) {
            destination[index] = (1U << ((DirectionNumberCount - 1) - index));
        }
    }
    /// <summary>Writes one dimension's direction numbers from a primitive generator and its initial values.</summary>
    /// <param name="generator">The primitive polynomial driving the recurrence; its degree is the recurrence's order.</param>
    /// <param name="initialNumbers">The leading numerators, one per degree of <paramref name="generator"/>; entry <c>k</c> (zero-based) must be odd and below <c>2^(k+1)</c>.</param>
    /// <param name="destination">Receives exactly <see cref="DirectionNumberCount"/> direction numbers, lowest index bit first.</param>
    /// <remarks>
    /// The recurrence is <c>m_k = 2·a_1·m_(k-1) ^ … ^ 2^(s-1)·a_(s-1)·m_(k-s+1) ^ 2^s·m_(k-s) ^ m_(k-s)</c> for a
    /// generator <c>t^s + a_1·t^(s-1) + … + a_(s-1)·t + 1</c>, and the direction number is the numerator left-aligned in
    /// the coordinate. Primitivity is checked here rather than assumed: a merely irreducible generator gives the shift
    /// register a short period and silently destroys the net property, and this runs once at table-build time.
    /// </remarks>
    /// <exception cref="ArgumentException"><paramref name="generator"/> is not primitive, a span has the wrong length, or an initial value is even or too large.</exception>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="generator"/> has degree below one or above <see cref="DirectionNumberCount"/>.</exception>
    public static void BuildDirectionNumbers(BinaryPolynomial generator, ReadOnlySpan<uint> initialNumbers, Span<uint> destination) {
        var order = generator.Degree;

        ArgumentOutOfRangeException.ThrowIfLessThan(value: order, other: 1);
        ArgumentOutOfRangeException.ThrowIfGreaterThan(value: order, other: DirectionNumberCount);

        if (DirectionNumberCount != destination.Length) {
            throw new ArgumentException(message: $"A dimension's direction numbers occupy exactly {DirectionNumberCount} words.", paramName: nameof(destination));
        }

        if (order != initialNumbers.Length) {
            throw new ArgumentException(message: "The recurrence needs exactly one initial numerator per degree of the generator.", paramName: nameof(initialNumbers));
        }

        if (!generator.IsPrimitive()) {
            throw new ArgumentException(message: $"The generator {generator} is not primitive, so its recurrence does not have full period.", paramName: nameof(generator));
        }

        Span<uint> numerators = stackalloc uint[DirectionNumberCount];

        for (var index = 0; (index < order); ++index) {
            var initial = initialNumbers[index];

            // The bound is taken in the wider type because at the top degree the exclusive upper bound is 2^32 itself.
            if ((0U == (initial & 1U)) || (((ulong)initial) >= (1UL << (index + 1)))) {
                throw new ArgumentException(message: $"Initial numerator {index} must be odd and below 2^{index + 1}.", paramName: nameof(initialNumbers));
            }

            numerators[index] = initial;
        }

        for (var index = order; (index < DirectionNumberCount); ++index) {
            var previous = numerators[index - order];
            var value = (previous ^ (previous << order));

            for (var lag = 1; (lag < order); ++lag) {
                if (0UL != ((generator.Bits >>> (order - lag)) & 1UL)) {
                    value ^= (numerators[index - lag] << lag);
                }
            }

            numerators[index] = value;
        }

        for (var index = 0; (index < DirectionNumberCount); ++index) {
            destination[index] = (numerators[index] << ((DirectionNumberCount - 1) - index));
        }
    }
    /// <summary>Writes the two-dimensional net's direction numbers: dimension zero, then dimension one.</summary>
    /// <param name="destination">Receives exactly <see cref="PlaneDirectionNumberCount"/> direction numbers.</param>
    /// <remarks>This is the shipped <c>(0, 2)</c>-sequence — bit reversal against the <see cref="PlaneGenerator"/> recurrence — and the pair a GPU sampler table carries verbatim.</remarks>
    /// <exception cref="ArgumentException"><paramref name="destination"/> is not <see cref="PlaneDirectionNumberCount"/> long.</exception>
    public static void BuildPlaneDirectionNumbers(Span<uint> destination) {
        if (PlaneDirectionNumberCount != destination.Length) {
            throw new ArgumentException(message: $"The two-dimensional net's direction numbers occupy exactly {PlaneDirectionNumberCount} words.", paramName: nameof(destination));
        }

        BuildBitReversalDirectionNumbers(destination: destination[..DirectionNumberCount]);
        BuildDirectionNumbers(generator: PlaneGenerator, initialNumbers: [1U], destination: destination[DirectionNumberCount..]);
    }
    /// <summary>Derives the two coordinates' digital shifts from one key.</summary>
    /// <param name="key">The key, which should already be mixed — <see cref="DeriveKey(uint, uint, uint)"/> produces one.</param>
    /// <returns>The digital shift for each coordinate.</returns>
    /// <remarks>The second shift is a mix of the key against a fixed separator rather than the key itself, so the two coordinates are not shifted by correlated vectors.</remarks>
    public static (uint X, uint Y) DeriveScramble(uint key) =>
        (X: key, Y: UnitriangularBitMix.Mix(value: (key ^ ScrambleSeparation)));
    /// <summary>Derives a per-lattice-site key from a two-dimensional site and a stream index.</summary>
    /// <param name="x">The site's first coordinate, which must fit sixteen bits.</param>
    /// <param name="y">The site's second coordinate, which must fit sixteen bits.</param>
    /// <param name="stream">A stream index separating independent consumers of the same site.</param>
    /// <returns>The mixed key.</returns>
    /// <remarks>Packing then mixing is injective for sites within sixteen bits: the packing is injective and the mix is a bijection, so distinct sites in one stream never share a key.</remarks>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="x"/> or <paramref name="y"/> exceeds sixteen bits, where the packing would overlap and alias distinct sites onto one key.</exception>
    public static uint DeriveKey(uint x, uint y, uint stream) {
        if (0xFFFFU < (x | y)) {
            throw new ArgumentOutOfRangeException(
                paramName: ((0xFFFFU < x) ? nameof(x) : nameof(y)),
                message: "Each site coordinate must fit sixteen bits; a wider coordinate overlaps the packing and collides with another site's key."
            );
        }

        return UnitriangularBitMix.Mix(value: ((x | (y << 16)) ^ unchecked((stream * StreamStride))));
    }
    /// <summary>Returns one coordinate of the digitally shifted net point at an index.</summary>
    /// <param name="index">The point index; the sequence is seekable, so no preceding index need be visited.</param>
    /// <param name="directionNumbers">One dimension's <see cref="DirectionNumberCount"/> direction numbers.</param>
    /// <param name="scramble">The digital shift, which preserves the net property; pass zero for the unshifted net.</param>
    /// <returns>The coordinate as a UQ0.32 fraction's raw bits.</returns>
    /// <exception cref="ArgumentException"><paramref name="directionNumbers"/> is not <see cref="DirectionNumberCount"/> long.</exception>
    public static uint Sample(uint index, ReadOnlySpan<uint> directionNumbers, uint scramble) {
        if (DirectionNumberCount != directionNumbers.Length) {
            throw new ArgumentException(message: $"A dimension's direction numbers occupy exactly {DirectionNumberCount} words.", paramName: nameof(directionNumbers));
        }

        var remaining = index;
        var result = scramble;

        while (0U != remaining) {
            result ^= directionNumbers[BitOperations.TrailingZeroCount(value: remaining)];
            remaining &= (remaining - 1U);
        }

        return result;
    }
    /// <summary>Returns both coordinates of the digitally shifted two-dimensional net point at an index.</summary>
    /// <param name="index">The point index.</param>
    /// <param name="directionNumbers">The <see cref="PlaneDirectionNumberCount"/> direction numbers, dimension zero first.</param>
    /// <param name="scramble">The two coordinates' digital shifts.</param>
    /// <returns>The point, each coordinate a UQ0.32 fraction's raw bits.</returns>
    /// <exception cref="ArgumentException"><paramref name="directionNumbers"/> is not <see cref="PlaneDirectionNumberCount"/> long.</exception>
    public static (uint X, uint Y) SamplePlane(uint index, ReadOnlySpan<uint> directionNumbers, (uint X, uint Y) scramble) {
        if (PlaneDirectionNumberCount != directionNumbers.Length) {
            throw new ArgumentException(message: $"The two-dimensional net's direction numbers occupy exactly {PlaneDirectionNumberCount} words.", paramName: nameof(directionNumbers));
        }

        return (
            X: Sample(index: index, directionNumbers: directionNumbers[..DirectionNumberCount], scramble: scramble.X),
            Y: Sample(index: index, directionNumbers: directionNumbers[DirectionNumberCount..], scramble: scramble.Y)
        );
    }
    /// <summary>Permutes the index a consumer draws, so that neighbouring lattice sites walk the same net in different orders.</summary>
    /// <param name="index">The consumer's own running index.</param>
    /// <param name="salt">The site's key.</param>
    /// <returns>The net index to sample.</returns>
    /// <remarks>
    /// A general mixing bijection would be wrong here: it scatters a consumer's first <c>2^m</c> indices across the
    /// whole index space, and the resulting point set is not a net at all.
    /// <see cref="NestedDyadicPermutation"/> is used instead precisely because it carries an aligned dyadic block onto
    /// an aligned dyadic block, and every such block of a <c>(0, 2)</c>-sequence is itself a <c>(0, m, 2)</c>-net.
    /// </remarks>
    public static uint ShuffleIndex(uint index, uint salt) =>
        NestedDyadicPermutation.Permute(index: index, seed: salt);
}
