using System.Runtime.CompilerServices;

namespace Puck.Maths;

/// <summary>Coordinates and multiplication in the eight units modulo thirty.</summary>
/// <remarks>
/// <para>
/// A channel is <c>a | (b &lt;&lt; 2)</c> for the residue <c>7^a 11^b</c>, with <c>0 ≤ a &lt; 4</c> and
/// <c>0 ≤ b &lt; 2</c>. Algebraic channels differ from ascending residue positions.
/// </para>
/// <para>
/// The wheel's numbers come from E₈ (see <see cref="SymmetryLattice"/>). The <see cref="Modulus"/> is E₈'s Coxeter
/// number <see cref="SymmetryLattice.CycleOrder"/>, and the residues a prime above five can occupy, the units modulo 30,
/// are exactly E₈'s exponents <see cref="SymmetryLattice.CycleExponents"/>: there are <see cref="ChannelCount"/> =
/// rank = φ(30) = 8 of them. The unit group U(30) ≅ C₄ × C₂, generated by 7 (order four) and 11 (order two), is the
/// Galois group of the 30th roots of unity and permutes the eigenvalues of E₈'s Coxeter element. The sieve sees the same
/// action: marking the multiples of a prime <c>p ≡ r (mod 30)</c> sends the multiplier in channel <c>c</c> to the
/// product in channel <c>r · c</c>, a permutation of the eight channels. <see cref="Multiply(byte, byte)"/>,
/// <see cref="Inverse(byte)"/> and <see cref="PermuteMask(byte, byte)"/> implement that action.
/// </para>
/// <para>
/// Thirty is also the largest very round number (OEIS A048597; Schatunowsky and Wolfskehl): every unit below 30 is
/// 1 or a prime, so before any sieving every candidate bit of the first block other than the one for 1 is a prime. The
/// next primorial, 210, fails, because 121 = 11² is coprime to it. One 64-bit word holds eight bytes of thirty
/// integers, <see cref="WordIntegers"/> = 240 integers. That count equals E₈'s root count
/// <see cref="SymmetryLattice.NodeCount"/> = rank × h as a number; no correspondence between words and roots is implied.
/// </para>
/// </remarks>
public static class PrimeWheel30 {
    /// <summary>The wheel modulus: thirty, E₈'s Coxeter number <see cref="SymmetryLattice.CycleOrder"/>. One wheel byte
    /// covers this many consecutive integers.</summary>
    public const int Modulus = SymmetryLattice.CycleOrder;
    /// <summary>The number of channels, the units modulo <see cref="Modulus"/>: eight, E₈'s rank
    /// <see cref="SymmetryLattice.Dimension"/>, one per exponent. One wheel byte holds one bit per channel.</summary>
    public const int ChannelCount = SymmetryLattice.Dimension;
    /// <summary>The number of consecutive integers one 64-bit word of wheel bytes covers: eight bytes of
    /// <see cref="Modulus"/> integers, 240. The value equals <see cref="SymmetryLattice.NodeCount"/> numerically.</summary>
    public const int WordIntegers = (sizeof(ulong) * Modulus);

    /// <summary>Gets residues in algebraic channel order.</summary>
    public static ReadOnlySpan<byte> Residues => [1, 7, 19, 13, 11, 17, 29, 23];
    /// <summary>Gets residues in ascending numerical order: E₈'s exponents, <see cref="SymmetryLattice.CycleExponents"/>.</summary>
    public static ReadOnlySpan<byte> NumericResidues => SymmetryLattice.CycleExponents;
    /// <summary>Gets the algebraic channels corresponding to ascending residue positions.</summary>
    public static ReadOnlySpan<byte> NumericChannels => [0, 1, 4, 3, 5, 2, 7, 6];

    /// <summary>Gets the residue of an algebraic channel.</summary>
    /// <param name="channel">A channel from zero through seven.</param>
    /// <returns>The representative between one and twenty-nine.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="channel"/> exceeds seven.</exception>
    public static byte Residue(byte channel) {
        ValidateChannel(channel: channel);
        return Residues[channel];
    }
    /// <summary>Attempts to convert a residue representative to its algebraic channel.</summary>
    /// <param name="residue">A representative between zero and twenty-nine; other values are rejected.</param>
    /// <param name="channel">The channel on success; zero on failure.</param>
    /// <returns>Whether the representative is a unit modulo thirty.</returns>
    public static bool TryChannel(byte residue, out byte channel) {
        channel = residue switch {
            1 => 0,
            7 => 1,
            19 => 2,
            13 => 3,
            11 => 4,
            17 => 5,
            29 => 6,
            23 => 7,
            _ => byte.MaxValue,
        };
        if (channel != byte.MaxValue) {
            return true;
        }
        channel = 0;
        return false;
    }
    /// <summary>Gets the ascending residue position of an algebraic channel.</summary>
    /// <param name="channel">A channel from zero through seven.</param>
    /// <returns>A position from zero through seven.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="channel"/> exceeds seven.</exception>
    public static byte NumericIndex(byte channel) {
        ValidateChannel(channel: channel);
        ReadOnlySpan<byte> positions = [0, 1, 5, 3, 2, 4, 7, 6];

        return positions[channel];
    }
    /// <summary>Gets the algebraic channel at an ascending residue position.</summary>
    /// <param name="index">A position from zero through seven.</param>
    /// <returns>The channel of that numerical position.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="index"/> exceeds seven.</exception>
    public static byte ChannelAtNumericIndex(byte index) {
        ArgumentOutOfRangeException.ThrowIfGreaterThan(index, ((byte)(ChannelCount - 1)));
        return NumericChannels[index];
    }
    /// <summary>Multiplies two algebraic channels without residue multiplication or division.</summary>
    /// <param name="left">The first channel, from zero through seven.</param>
    /// <param name="right">The second channel, from zero through seven.</param>
    /// <returns>The channel of the product modulo thirty.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Either channel exceeds seven.</exception>
    public static byte Multiply(byte left, byte right) {
        ArgumentOutOfRangeException.ThrowIfGreaterThan(left, ((byte)(ChannelCount - 1)));
        ArgumentOutOfRangeException.ThrowIfGreaterThan(right, ((byte)(ChannelCount - 1)));
        return ((byte)(((left + right) & 3) | ((left ^ right) & 4)));
    }
    /// <summary>Inverts an algebraic channel.</summary>
    /// <param name="channel">A channel from zero through seven.</param>
    /// <returns>The channel of the multiplicative inverse modulo thirty.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="channel"/> exceeds seven.</exception>
    public static byte Inverse(byte channel) {
        ValidateChannel(channel: channel);
        return ((byte)(((-channel) & 3) | (channel & 4)));
    }
    /// <summary>Permutes an algebraic bit mask by multiplication by a channel.</summary>
    /// <param name="mask">A mask whose bit positions are algebraic channels.</param>
    /// <param name="channel">The multiplying channel, from zero through seven.</param>
    /// <returns>The mask after rotating both nibbles and, when required, swapping them.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="channel"/> exceeds seven.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte PermuteMask(byte mask, byte channel) {
        ValidateChannel(channel: channel);
        return PermuteMask(mask: mask, rotation: channel & 3, swap: ((channel & 4) != 0));
    }
    /// <summary>Acts on an algebraic mask by an arbitrary power of seven and an optional factor of eleven.</summary>
    /// <param name="mask">A mask whose bit positions are algebraic channels.</param>
    /// <param name="rotation">The exponent of seven, reduced modulo four, including negative exponents.</param>
    /// <param name="swap">Whether multiplication also includes eleven, which swaps the two nibbles.</param>
    /// <returns>The mask acted on by <c>7^rotation</c>, also multiplied by eleven when <paramref name="swap"/> is true.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte PermuteMask(byte mask, int rotation, bool swap) {
        var shift = rotation & 3;
        var low = mask & 15;
        var high = (mask >> 4);

        low = ((low << shift) | (low >> (4 - shift))) & 15;
        high = ((high << shift) | (high >> (4 - shift))) & 15;
        return ((byte)(swap ? high | (low << 4) : low | (high << 4)));
    }

    // The wheel walk: crossing off p = 30q + r visits p·m for the multipliers m coprime to 30 in ascending order, and
    // eight steps advance exactly p bytes. The members below derive every wheel table the sieves read (step gaps,
    // carries, lifts, target bits, clear masks and prefix masks) as small closed forms over NumericResidues; the JIT
    // folds a call with constant arguments to a constant. Tables built at type initialization call them. A table a hot loop
    // indexes by a variable position, and constants that constant-residue marking code folds while importing, are
    // written out instead, and prime-exploration.wheel-tables-match-their-derivation proves each equals the derivation.

    /// <summary>Gets <see cref="Gap(int)"/> for every phase, 6, 4, 2, 4, 2, 4, 6, 2, as constant data for loops that
    /// index it by a variable phase.</summary>
    /// <remarks>The values are written out so a read costs one load from a constant address; the law
    /// <c>prime-exploration.wheel-tables-match-their-derivation</c> proves they equal the derivation.</remarks>
    internal static ReadOnlySpan<byte> Gaps => [6, 4, 2, 4, 2, 4, 6, 2];
    /// <summary>Gets <see cref="PrefixMask(int)"/> for every remainder from zero through twenty-nine, as constant data
    /// for loops that index it by a variable remainder.</summary>
    /// <remarks>The values are written out so a read costs one load from a constant address; the law
    /// <c>prime-exploration.wheel-tables-match-their-derivation</c> proves they equal the derivation.</remarks>
    internal static ReadOnlySpan<byte> PrefixMasks => [
        0, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 7, 7, 15, 15,
        15, 15, 31, 31, 63, 63, 63, 63, 127, 127, 127, 127, 127, 127, 255,
    ];

    /// <summary>Gets the multiplier at a wheel phase: the ascending unit at phases zero through seven, and the next
    /// cycle's first unit, <c>Modulus + 1</c>, at phase eight.</summary>
    /// <param name="phase">A phase from zero through <see cref="ChannelCount"/>.</param>
    /// <returns>The multiplier.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static int Multiplier(int phase) =>
        ((phase < ChannelCount) ? NumericResidues[phase] : (Modulus + NumericResidues[0]));
    /// <summary>Gets the gap from one multiplier to the next, the step pattern 6, 4, 2, 4, 2, 4, 6, 2.</summary>
    /// <param name="phase">A phase from zero through seven.</param>
    /// <returns>The difference between the multipliers at <c>phase + 1</c> and <paramref name="phase"/>.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static int Gap(int phase) =>
        (Multiplier(phase: (phase + 1)) - Multiplier(phase: phase));
    /// <summary>Gets the whole wheel bytes the residue part of a product advances: <c>⌊r·m / 30⌋</c>.</summary>
    /// <param name="residue">The prime's residue <c>r</c>.</param>
    /// <param name="multiplier">The multiplier <c>m</c>.</param>
    /// <returns>The byte lift; <c>p·m</c> lies <c>q·m</c> plus this many bytes from the origin.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static int Lift(int residue, int multiplier) =>
        ((residue * multiplier) / Modulus);
    /// <summary>Gets the carry of one wheel step: the bytes beyond <c>q·Gap(phase)</c> that moving from the multiplier at
    /// <paramref name="phase"/> to the next one advances.</summary>
    /// <param name="residue">The prime's residue <c>r</c>.</param>
    /// <param name="phase">A phase from zero through seven.</param>
    /// <returns><c>⌊r·m₍ₖ₊₁₎ / 30⌋ − ⌊r·mₖ / 30⌋</c>.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static int Carry(int residue, int phase) =>
        (((residue * Multiplier(phase: (phase + 1))) / Modulus) - ((residue * Multiplier(phase: phase)) / Modulus));
    /// <summary>Gets the numeric index of a unit residue: the number of smaller units.</summary>
    /// <param name="residue">A unit modulo thirty, from one through twenty-nine.</param>
    /// <returns>The ascending position from zero through seven.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static int NumericBit(int residue) {
        var numeric = NumericResidues;

        return ((((((((numeric[0] < residue) ? 1 : 0) + ((numeric[1] < residue) ? 1 : 0)) + ((numeric[2] < residue) ? 1 : 0))
            + ((numeric[3] < residue) ? 1 : 0)) + ((numeric[4] < residue) ? 1 : 0)) + ((numeric[5] < residue) ? 1 : 0))
            + (((numeric[6] < residue) ? 1 : 0) + ((numeric[7] < residue) ? 1 : 0)));
    }
    /// <summary>Gets the numeric bit a step lands on: the position of <c>r·m mod 30</c> for the multiplier at
    /// <paramref name="phase"/>.</summary>
    /// <param name="residue">The prime's residue <c>r</c>, a unit.</param>
    /// <param name="phase">A phase from zero through seven.</param>
    /// <returns>The numeric bit from zero through seven.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static int TargetBit(int residue, int phase) =>
        NumericBit(residue: ((residue * Multiplier(phase: phase)) % Modulus));
    /// <summary>Gets the byte mask of the units no greater than a remainder, in numeric bit order.</summary>
    /// <param name="remainder">A remainder from zero through twenty-nine.</param>
    /// <returns>Bit <c>k</c> is set exactly when the <c>k</c>-th ascending unit is at most <paramref name="remainder"/>.</returns>
    internal static byte PrefixMask(int remainder) =>
        ((byte)((1 << NumericBit(residue: (remainder + 1))) - 1));
    /// <summary>Gets the word mask of the units no greater than an offset inside one 64-bit word of wheel bytes.</summary>
    /// <param name="offset">An offset from zero through <c><see cref="WordIntegers"/> − 1</c>.</param>
    /// <returns>Every bit of the bytes below the offset's byte, and that byte's <see cref="PrefixMask(int)"/>.</returns>
    internal static ulong WordPrefixMask(int offset) {
        var shift = ((offset / Modulus) * ChannelCount);

        return (((1UL << shift) - 1UL)) | (((ulong)PrefixMask(remainder: (offset % Modulus))) << shift);
    }

    private static void ValidateChannel(byte channel) {
        ArgumentOutOfRangeException.ThrowIfGreaterThan(channel, ((byte)(ChannelCount - 1)));
    }
}
