namespace Puck.Maths;

/// <summary>
/// The tiling word of the quasicrystal beneath any quadratic irrational, generated by inflation for an arbitrary
/// continued-fraction period. The period <c>[b₀, …, b_{ℓ-1}]</c> that <see cref="ContinuedFraction"/> reads becomes the
/// composed two-letter substitution <c>τ_{b₀} ∘ … ∘ τ_{b_{ℓ-1}}</c>, where each factor <c>τₖ</c> sends
/// <c>long → longᵏ short</c> and <c>short → long</c>; its incidence matrix is exactly the substitution matrix
/// <see cref="QuadraticInflation"/> reads from the same period, so the two lenses agree by construction. The fixed point
/// of the composed substitution is the aperiodic, never-repeating tiling — a genuine one-dimensional quasicrystal
/// (Sturmian word) of the slope the irrational sets. This is the general form the metallic siblings specialize: the
/// golden Fibonacci word of <see cref="MetallicQuasicrystal"/> is the period <c>[1]</c> and its silver Pell word is the
/// period <c>[2]</c>.
/// </summary>
/// <remarks>
/// <see cref="Word(long, long, long, long, Span{bool})"/> streams a run of the word — <see langword="false"/> for the
/// short tile, <see langword="true"/> for the long — in amortized constant time per tile: it precomputes the two letter
/// images of the composed substitution once, then reads the growing output as its own expansion queue, allocating nothing
/// per tile. The word is self-similar under inflation, has complexity <c>k + 1</c> for every factor length <c>k</c> (the
/// defining Sturmian property), and the long tile is the frequent letter, outnumbering the short by the inflation factor.
/// <see cref="InflationFactor(long, long, long, long)"/> is that factor through
/// <see cref="QuadraticInflation.InflationFactor"/>, and <see cref="Positions(long, long, long, long, ReadOnlySpan{bool}, Span{FixedQ4816})"/>
/// lays the tiles on the line with the short tile as the unit and the long tile as <see cref="LongTileLength(long, long, long, long)"/> —
/// the one approximate seam, matching <see cref="MetallicQuasicrystal.Position(int, long, long)"/>; the word above it is exact combinatorics.
/// Beyond streaming, the nested <see cref="Chain"/> addresses the same tiling's vertices by ring coordinate in O(1) —
/// the general membership-and-traversal surface the metallic family carries only for single-term periods.
/// </remarks>
public static class QuadraticQuasicrystal {
    /// <summary>Fills a leading run of the tiling word of <c>(p + q·√d) / r</c>: the fixed point of the substitution its continued-fraction period composes.</summary>
    /// <param name="p">The rational part of the numerator.</param>
    /// <param name="q">The coefficient of the surd; it must be positive.</param>
    /// <param name="d">The radicand; it must be at least two and not a perfect square.</param>
    /// <param name="r">The denominator; it must be non-zero.</param>
    /// <param name="tiles">Receives the tiling in physical order: <see langword="false"/> is the short tile, <see langword="true"/> the long. Every element is written.</param>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="q"/> is not positive, <paramref name="d"/> is below two or a perfect square, or <paramref name="r"/> is zero.</exception>
    public static void Word(long p, long q, long d, long r, Span<bool> tiles) {
        if (tiles.IsEmpty) { return; }

        Span<long> terms = stackalloc long[128];
        var written = ContinuedFraction.Expand(
            p: p,
            q: q,
            d: d,
            r: r,
            terms: terms,
            periodStart: out var periodStart,
            periodLength: out var periodLength
        );
        var period = terms.Slice(start: periodStart, length: periodLength);

        // The composed substitution acts on two letters, so its whole action is the two images σ(long) and σ(short),
        // built once. The long image begins with the long tile, so the fixed point seeds from it.
        var longImage = ComposeImage(period: period, seedLong: true);
        var shortImage = ComposeImage(period: period, seedLong: false);

        // Stream the fixed point w = σ(w) = σ(w₀) σ(w₁) … : the output doubles as its own expansion queue. Each already
        // written tile is expanded once, in order, and appended — amortized O(1) per tile with no per-tile allocation.
        var write = Emit(image: longImage, tiles: tiles, at: 0);
        var read = 1;

        while (write < tiles.Length) {
            write = Emit(image: (tiles[read] ? longImage : shortImage), tiles: tiles, at: write);
            read += 1;
        }
    }
    /// <summary>Lays a run of the tiling word on the line, returning the start coordinate of each tile.</summary>
    /// <param name="p">The rational part of the numerator.</param>
    /// <param name="q">The coefficient of the surd; it must be positive.</param>
    /// <param name="d">The radicand; it must be at least two and not a perfect square.</param>
    /// <param name="r">The denominator; it must be non-zero.</param>
    /// <param name="tiles">The tiling word — as filled by <see cref="Word(long, long, long, long, Span{bool})"/>.</param>
    /// <param name="positions">Receives the start coordinate of each tile, with the short tile as the unit and the long tile as <see cref="LongTileLength(long, long, long, long)"/>. It must be at least as long as <paramref name="tiles"/>.</param>
    /// <returns>The coordinate just past the final tile — the total length of the run.</returns>
    /// <exception cref="ArgumentException"><paramref name="positions"/> is shorter than <paramref name="tiles"/>.</exception>
    /// <exception cref="ArgumentOutOfRangeException">The surd parameters are out of range — see <see cref="ContinuedFraction.Expand"/>.</exception>
    public static FixedQ4816 Positions(long p, long q, long d, long r, ReadOnlySpan<bool> tiles, Span<FixedQ4816> positions) {
        if (positions.Length < tiles.Length) {
            throw new ArgumentException(
                message: "the positions span must be at least as long as the tiling word",
                paramName: nameof(positions)
            );
        }

        var longTile = LongTileLength(p: p, q: q, d: d, r: r);
        var cursor = FixedQ4816.Zero;

        for (var index = 0; (index < tiles.Length); ++index) {
            positions[index] = cursor;
            cursor += (tiles[index] ? longTile : FixedQ4816.One);
        }

        return cursor;
    }
    /// <summary>Returns the length of the long tile with the short tile as the unit — the ratio that makes the tiling self-similar under inflation.</summary>
    /// <param name="p">The rational part of the numerator.</param>
    /// <param name="q">The coefficient of the surd; it must be positive.</param>
    /// <param name="d">The radicand; it must be at least two and not a perfect square.</param>
    /// <param name="r">The denominator; it must be non-zero.</param>
    /// <returns>The long-tile length <c>C / (λ − A)</c> from the substitution matrix — the left Perron eigenvector, which coincides with <see cref="InflationFactor(long, long, long, long)"/> only for a single-term period. The one approximate operation.</returns>
    /// <exception cref="ArgumentOutOfRangeException">The surd parameters are out of range — see <see cref="ContinuedFraction.Expand"/>.</exception>
    public static FixedQ4816 LongTileLength(long p, long q, long d, long r) {
        // The tile lengths are the left Perron eigenvector (ℓ_long, ℓ_short) of the substitution matrix: ℓ_long·A + ℓ_short·C
        // = λ·ℓ_long gives ℓ_long / ℓ_short = C / (λ − A). It is λ itself only when the period is a single term (A = trace).
        var inflation = QuadraticInflation.FromQuadraticIrrational(p: p, q: q, d: d, r: r);

        return (FixedQ4816.FromInteger(value: inflation.C) / (inflation.InflationFactor() - FixedQ4816.FromInteger(value: inflation.A)));
    }
    /// <summary>Returns the inflation factor — the long-to-short tile ratio and the self-similarity scale — of the quasicrystal of <c>(p + q·√d) / r</c>.</summary>
    /// <param name="p">The rational part of the numerator.</param>
    /// <param name="q">The coefficient of the surd; it must be positive.</param>
    /// <param name="d">The radicand; it must be at least two and not a perfect square.</param>
    /// <param name="r">The denominator; it must be non-zero.</param>
    /// <returns>The factor as a fixed-point value, read through <see cref="QuadraticInflation.InflationFactor"/>; the one approximate operation.</returns>
    /// <exception cref="ArgumentOutOfRangeException">The surd parameters are out of range — see <see cref="ContinuedFraction.Expand"/>.</exception>
    public static FixedQ4816 InflationFactor(long p, long q, long d, long r) =>
        QuadraticInflation.FromQuadraticIrrational(p: p, q: q, d: d, r: r).InflationFactor();

    /// <summary>Builds one letter image of the composed substitution by applying the period's factors from the innermost outward.</summary>
    /// <param name="period">The continued-fraction period; each entry <c>k</c> is the factor <c>τₖ</c>: <c>long → longᵏ short</c>, <c>short → long</c>.</param>
    /// <param name="seedLong">The seed letter — <see langword="true"/> for the long image, <see langword="false"/> for the short.</param>
    /// <returns>The image of the seed letter under the whole period.</returns>
    private static bool[] ComposeImage(ReadOnlySpan<long> period, bool seedLong) {
        var current = new List<bool>(capacity: 4) { seedLong };

        // σ = τ_{b₀} ∘ … ∘ τ_{b_{ℓ-1}} applies the last factor first, so its incidence matrix is the period product
        // ∏ [[bᵢ, 1], [1, 0]] — the very matrix QuadraticInflation reads from the same period.
        for (var index = (period.Length - 1); (index >= 0); --index) {
            var factor = period[index];
            var next = new List<bool>(capacity: (current.Count * 2));

            foreach (var isLong in current) {
                if (isLong) {
                    for (var repeat = 0L; (repeat < factor); ++repeat) { next.Add(item: true); }

                    next.Add(item: false);
                } else {
                    next.Add(item: true);
                }
            }

            current = next;
        }

        return current.ToArray();
    }
    /// <summary>Copies as much of a letter image as fits into the output, returning the new write cursor.</summary>
    /// <param name="image">The letter image to append.</param>
    /// <param name="tiles">The output word.</param>
    /// <param name="at">The write cursor.</param>
    /// <returns>The advanced write cursor, clamped to the output length.</returns>
    private static int Emit(ReadOnlySpan<bool> image, Span<bool> tiles, int at) {
        var count = Math.Min(image.Length, (tiles.Length - at));

        image.Slice(start: 0, length: count).CopyTo(destination: tiles.Slice(start: at, length: count));

        return (at + count);
    }

    /// <summary>
    /// Ring-coordinate random access into the same tiling <see cref="Word(long, long, long, long, Span{bool})"/> streams:
    /// the O(1) membership-and-traversal surface that <see cref="MetallicQuasicrystal"/> carries for the single-term
    /// (metallic) periods, generalized to every continued-fraction period. The tiling's vertices form a cut-and-project set
    /// whose two-tile step lattice is the abelianization <c>ℤ²</c> of the long/short letter counts; a lattice point
    /// <c>(a, b) = (longCount, shortCount)</c> is a vertex exactly when its Galois-conjugate internal coordinate falls in a
    /// bounded acceptance window. Build one with <see cref="FromQuadraticIrrational(long, long, long, long)"/> and reuse it —
    /// the period is expanded once and the substitution matrix cached, so each query is a handful of integer operations.
    /// </summary>
    /// <remarks>
    /// The physical tile lengths are the left Perron eigenvector of the substitution matrix <c>M = [[A, B], [C, D]]</c>:
    /// long <c>∝ C</c>, short <c>∝ λ − A</c> (with <c>λ</c> the inflation factor). Applying the field's Galois conjugation
    /// sends <c>λ ↦ λ'</c> (the other root of <c>x² − Trace·x + Determinant</c>), giving the internal (star) coordinate
    /// <c>s(a, b) = C·a + (λ' − A)·b</c>. The acceptance window is the half-open interval <c>[0, C + A − λ')</c> — its length
    /// is the sum of the two internal tile lengths, the covolume the cut-and-project set demands, with the origin at the left
    /// edge. Both internal tile lengths are irrational surds (the naive <c>ℓ_short = 1</c> would make the short tile rational
    /// and unbound the window, so the tiles are taken as the eigenvector components <c>C</c> and <c>λ − A</c>), so the window
    /// is genuinely bounded and <see cref="Contains(long, long)"/> is decisive. Only <see cref="Position(long, long)"/> crosses
    /// the approximate seam; membership and traversal are exact integer surd signs. For a single-term period the walk
    /// reproduces the same tiling language as <see cref="MetallicQuasicrystal"/> — but in tile-count coordinates, whereas
    /// <see cref="MetallicQuasicrystal"/> keeps the ring coordinate <c>a + b·δₙ</c> that matches the former golden and silver
    /// files; general periods (with <c>C &gt; 1</c>) admit no such ring embedding, which is why this surface addresses by
    /// tile count.
    /// </remarks>
    public readonly record struct Chain {
        private Chain(QuadraticInflation inflation, FixedQ4816 inflationFactor) {
            Inflation = inflation;
            InflationFactor = inflationFactor;
        }

        /// <summary>Gets the inflation lens beneath the chain — the exact substitution matrix and its conjugacy invariants.</summary>
        public QuadraticInflation Inflation { get; }
        /// <summary>Gets the inflation factor <c>λ</c> — the Perron eigenvalue and the self-similarity scale — as a fixed-point value; the one approximate seam, used only by <see cref="Position(long, long)"/>.</summary>
        public FixedQ4816 InflationFactor { get; }

        /// <summary>Builds the ring-coordinate chain of the quadratic irrational <c>(p + q·√d) / r</c> from its continued-fraction period.</summary>
        /// <param name="p">The rational part of the numerator.</param>
        /// <param name="q">The coefficient of the surd; it must be positive.</param>
        /// <param name="d">The radicand; it must be at least two and not a perfect square.</param>
        /// <param name="r">The denominator; it must be non-zero.</param>
        /// <returns>The chain, with the substitution matrix and inflation factor read from the period.</returns>
        /// <exception cref="ArgumentOutOfRangeException"><paramref name="q"/> is not positive, <paramref name="d"/> is below two or a perfect square, or <paramref name="r"/> is zero.</exception>
        /// <exception cref="OverflowException">A partial-quotient product exceeds <see cref="long"/> — the period is too long for the width.</exception>
        public static Chain FromQuadraticIrrational(long p, long q, long d, long r) {
            var inflation = QuadraticInflation.FromQuadraticIrrational(p: p, q: q, d: d, r: r);

            return new Chain(inflation: inflation, inflationFactor: inflation.InflationFactor());
        }

        /// <summary>Determines whether the lattice point <c>(a, b) = (longCount, shortCount)</c> is a vertex of the tiling — the O(1) membership test that addresses points by ring coordinate.</summary>
        /// <param name="a">The long-tile count of the vertex — the number of long tiles from the origin.</param>
        /// <param name="b">The short-tile count of the vertex — the number of short tiles from the origin.</param>
        /// <returns><see langword="true"/> when the point's internal (Galois-conjugate) coordinate lies in the acceptance window <c>[0, C + A − λ')</c>.</returns>
        public bool Contains(long a, long b) {
            var matrixA = Inflation.A;
            var matrixC = Inflation.C;
            var discriminant = Inflation.Discriminant;

            // The internal coordinate is s = C·a + (λ' − A)·b, with λ' = (Trace − √Δ) / 2, so 2·s = (2C·a + (D − A)·b) − b·√Δ.
            // Membership is 0 ≤ s: the lower edge is closed, so the origin (0, 0) at s = 0 is the left endpoint of the window.
            if (SignSurd128(rational: (((Int128)(2L * matrixC) * a) + ((Int128)(Inflation.D - matrixA) * b)), coefficient: (Int128)(-b), radicand: discriminant) < 0) {
                return false;
            }

            // The window length is |W| = C + A − λ', so 2(|W| − s) = (2C·(1 − a) + (A − D)·(1 + b)) + (1 + b)·√Δ; the upper edge
            // is open, keeping the single lattice point that lands exactly on it (the far singular point) out of the set.
            return (SignSurd128(rational: (((Int128)(2L * matrixC) * (1L - a)) + ((Int128)(matrixA - Inflation.D) * (1L + b))), coefficient: (Int128)(1L + b), radicand: discriminant) > 0);
        }
        /// <summary>Determines whether the longer-count step begins at the vertex <c>(a, b)</c> — that is, whether the next tile is a long one.</summary>
        /// <param name="a">The long-tile count of the vertex.</param>
        /// <param name="b">The short-tile count of the vertex.</param>
        /// <returns><see langword="true"/> when the tile starting here is the long one; otherwise it is the short tile.</returns>
        public bool StartsLongTile(long a, long b) =>
            // The short step reaches (a, b + 1); when that is not a vertex the tile starting here must be the long one instead.
            (Contains(a: a, b: (b + 1L)) == false);
        /// <summary>Returns the next vertex along the line — the far end of the tile that starts at <c>(a, b)</c>.</summary>
        /// <param name="a">The long-tile count of a vertex.</param>
        /// <param name="b">The short-tile count of a vertex.</param>
        /// <returns>The next vertex, reached by a long step <c>(a + 1, b)</c> or a short step <c>(a, b + 1)</c>.</returns>
        public (long A, long B) Next(long a, long b) =>
            (StartsLongTile(a: a, b: b) ? (a + 1L, b) : (a, b + 1L));
        /// <summary>Returns the previous vertex along the line — the near end of the tile that ends at <c>(a, b)</c>.</summary>
        /// <param name="a">The long-tile count of a vertex.</param>
        /// <param name="b">The short-tile count of a vertex.</param>
        /// <returns>The preceding vertex of the tiling.</returns>
        public (long A, long B) Previous(long a, long b) =>
            // Of the two candidate predecessors, the true one is a vertex whose forward step lands on (a, b); a non-vertex can
            // also step here, so membership and the step must both be checked — the long candidate first, else the short one.
            ((Contains(a: (a - 1L), b: b) && (Next(a: (a - 1L), b: b) == (a, b))) ? (a - 1L, b) : (a, b - 1L));
        /// <summary>Returns the position of the vertex <c>(a, b)</c> along the line.</summary>
        /// <param name="a">The long-tile count of the vertex.</param>
        /// <param name="b">The short-tile count of the vertex.</param>
        /// <returns>The fixed-point coordinate <c>C·a + (λ − A)·b</c> — the physical length swept by the long and short tiles; the one approximate value, membership and traversal being exact.</returns>
        public FixedQ4816 Position(long a, long b) =>
            // The physical tile lengths are the left Perron eigenvector (long ∝ C, short ∝ λ − A), so the swept length is
            // C·a + (λ − A)·b = (C·a − A·b) + λ·b — increasing at every step, both tile lengths being positive.
            (FixedQ4816.FromInteger(value: ((Inflation.C * a) - (Inflation.A * b))) + (InflationFactor * FixedQ4816.FromInteger(value: b)));

        /// <summary>Returns the sign of the real number <c>rational + coefficient·√radicand</c>, exactly, at full width.</summary>
        private static int SignSurd128(Int128 rational, Int128 coefficient, long radicand) {
            if ((rational == Int128.Zero) && (coefficient == Int128.Zero)) { return 0; }
            if ((rational >= Int128.Zero) && (coefficient >= Int128.Zero)) { return 1; }
            if ((rational <= Int128.Zero) && (coefficient <= Int128.Zero)) { return -1; }

            // Opposite signs: compare rational² against radicand·coefficient² at full width, then read off by rational's sign.
            var comparison = (rational * rational).CompareTo((coefficient * coefficient) * radicand);

            return ((rational > Int128.Zero)
                ? ((comparison > 0) ? 1 : ((comparison < 0) ? -1 : 0))
                : ((comparison < 0) ? 1 : ((comparison > 0) ? -1 : 0)));
        }
    }
}
