// Generated by puck shaders generate from WorldSkyKinds. Do not edit.
#ifndef SDF_SKY_KINDS_GENERATED_HLSLI
#define SDF_SKY_KINDS_GENERATED_HLSLI
#define SDF_SKY_MASK_NONE 0u
#define SDF_SKY_MASK_ELEVATION 1u
#define SDF_SKY_MASK_CONE 2u
#define SDF_SKY_BLEND_OVER 0u
#define SDF_SKY_BLEND_ADD 1u
#define SDF_SKY_BLEND_MULTIPLY 2u
#define SDF_SKY_BLEND_SCREEN 3u
#define SDF_SKY_VISIBILITY_CAMERA 1u
#define SDF_SKY_VISIBILITY_LIGHTING 2u
#define SDF_SKY_VISIBILITY_BOTH 3u
#define SDF_SKY_QUALITY_LOW 0u
#define SDF_SKY_QUALITY_MEDIUM 1u
#define SDF_SKY_QUALITY_HIGH 2u
#define SDF_SKY_RUNTIME 1
#include "kinds/aurora.hlsli"
#include "kinds/clouds.hlsli"
#include "kinds/gradient.hlsli"
#include "kinds/noise.hlsli"
#include "kinds/panorama.hlsli"
#include "kinds/pattern.hlsli"
#include "kinds/stars.hlsli"

// The common wrapper admits masks, tier and inspection before dispatching any kind work.
float4 sdfEvaluateSkyKind(uint kind, SdfSkyContext context, uint parameterIndex, inout SdfSkyWork work) {
    switch (kind) {
        case 0u: return sdfSkyKindAurora(context, parameterIndex, work);
        case 1u: return sdfSkyKindClouds(context, parameterIndex, work);
        case 2u: return sdfSkyKindGradient(context, parameterIndex, work);
        case 3u: return sdfSkyKindNoise(context, parameterIndex, work);
        case 4u: return sdfSkyKindPanorama(context, parameterIndex, work);
        case 5u: return sdfSkyKindPattern(context, parameterIndex, work);
        case 6u: return sdfSkyKindStars(context, parameterIndex, work);
        default: return 0.0;
    }
}
#undef SDF_SKY_RUNTIME
#endif
