// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.HumbleGamingBrick.Forge.Framework {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>PbakBundle.SupportedVersion</c>, declared in <c>src/Puck.HumbleGamingBrick.Forge/Framework/PbakBundle.cs</c>.</summary>
        public const string PbakBundleSupportedVersion = "b854d69da30847d2";
    }
}
