// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.HumbleGamingBrick {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>MachineIdentity.CurrentVersion</c>, declared in <c>src/Puck.HumbleGamingBrick/MachineSnapshot.cs</c>.</summary>
        public const string MachineIdentityCurrentVersion = "dc396ea0670ca382";
    }
}
