<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Production</PuckKind>
        <PuckLayer>Optional extensions</PuckLayer>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Azure.ResourceManager" Version="[1.*,2.0)" />
        <ProjectReference Include="..\Puck.World.Server\Puck.World.Server.csproj" />
    </ItemGroup>
</Project>
