// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Cli {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldArtifactKey.Schema</c>, declared in <c>src/Puck.Cli/WorldArtifactKey.cs</c>.</summary>
        public const string WorldArtifactKeySchema = "6b245d8afcd28e61";
    }
}

namespace Puck.Cli.Affected {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AffectedCoverage.Schema</c>, declared in <c>src/Puck.Cli/Affected/AffectedCoverage.cs</c>.</summary>
        public const string AffectedCoverageSchema = "9c347371e4c99d56";
    }
}

namespace Puck.Cli.Automation {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldReleaseExerciseResult.CurrentSchema</c>, declared in <c>src/Puck.Cli/Automation/WorldReleaseExerciseCommand.cs</c>.</summary>
        public const string WorldReleaseExerciseResultCurrentSchema = "7ed366704cc0f19e";
        /// <summary>The shape fingerprint of <c>WorldReleaseQualificationRunner.Marker</c>, declared in <c>src/Puck.Cli/Automation/WorldReleaseQualificationRunner.cs</c>.</summary>
        public const string WorldReleaseQualificationRunnerMarker = "38ccc886fb84d9ab";
    }
}

namespace Puck.Cli.Azure {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldReleaseDeploymentStore.Schema</c>, declared in <c>src/Puck.Cli/Azure/WorldReleaseDeploymentStore.cs</c>.</summary>
        public const string WorldReleaseDeploymentStoreSchema = "4523eb115f202a06";
    }
}

namespace Puck.Cli.Branding {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>BrandingCommand.ManifestSchema</c>, declared in <c>src/Puck.Cli/Branding/BrandingCommand.cs</c>.</summary>
        public const string BrandingCommandManifestSchema = "d5db24c0f47fc8b2";
    }
}

namespace Puck.Cli.Canary {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>CanaryCeilingsLedger.Format</c>, declared in <c>src/Puck.Cli/Canary/CanaryCeilingsLedger.cs</c>.</summary>
        public const string CanaryCeilingsLedgerFormat = "0bad76a4c3a56821";
    }
}

namespace Puck.Cli.Formats {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>FormatVersionsLedger.Format</c>, declared in <c>src/Puck.Cli/Formats/FormatVersionsLedger.cs</c>.</summary>
        public const string FormatVersionsLedgerFormat = "3ce3a22c899f1a69";
    }
}

namespace Puck.Cli.Parity {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>ParityManifestLoader.ContractSchema</c>, declared in <c>src/Puck.Cli/Parity/ParityManifestLoader.cs</c>.</summary>
        public const string ParityManifestLoaderContractSchema = "ec949a77a0ee5231";
    }
}

namespace Puck.Cli.Qualification {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>QualificationReport.SchemaVersion</c>, declared in <c>src/Puck.Cli/Qualification/QualificationReport.cs</c>.</summary>
        public const string QualificationReportSchemaVersion = "40a2ec90645d5a9e";
        /// <summary>The shape fingerprint of <c>ReleaseProfile.SchemaVersion</c>, declared in <c>src/Puck.Cli/Qualification/ReleaseProfile.cs</c>.</summary>
        public const string ReleaseProfileSchemaVersion = "9c69037b8f5a87e5";
    }
}
