// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Cli {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldArtifactKey.Schema</c>, declared in <c>src/Puck.Cli/WorldArtifactKey.cs</c>.</summary>
        public const string WorldArtifactKeySchema = "f6ae54aa0a05f9b3";
    }
}

namespace Puck.Cli.Affected {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AffectedCoverage.Schema</c>, declared in <c>src/Puck.Cli/Affected/AffectedCoverage.cs</c>.</summary>
        public const string AffectedCoverageSchema = "4397b4cc13c9d5af";
    }
}

namespace Puck.Cli.Automation {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldReleaseExerciseResult.CurrentSchema</c>, declared in <c>src/Puck.Cli/Automation/WorldReleaseExerciseCommand.cs</c>.</summary>
        public const string WorldReleaseExerciseResultCurrentSchema = "7af050f784d473c5";
        /// <summary>The shape fingerprint of <c>WorldReleaseQualificationRunner.Marker</c>, declared in <c>src/Puck.Cli/Automation/WorldReleaseQualificationRunner.cs</c>.</summary>
        public const string WorldReleaseQualificationRunnerMarker = "2b8f77ee9173c72c";
    }
}

namespace Puck.Cli.Azure {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldReleaseDeploymentStore.Schema</c>, declared in <c>src/Puck.Cli/Azure/WorldReleaseDeploymentStore.cs</c>.</summary>
        public const string WorldReleaseDeploymentStoreSchema = "0ae69dba0c02136c";
    }
}

namespace Puck.Cli.Branding {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>BrandingCommand.ManifestSchema</c>, declared in <c>src/Puck.Cli/Branding/BrandingCommand.cs</c>.</summary>
        public const string BrandingCommandManifestSchema = "8f4b96c3f365c407";
    }
}

namespace Puck.Cli.Canary {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>CanaryCeilingsLedger.Format</c>, declared in <c>src/Puck.Cli/Canary/CanaryCeilingsLedger.cs</c>.</summary>
        public const string CanaryCeilingsLedgerFormat = "704107433b8ecf5b";
    }
}

namespace Puck.Cli.Determinism {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>DeterminismManifest.Schema</c>, declared in <c>src/Puck.Cli/Determinism/DeterminismManifest.cs</c>.</summary>
        public const string DeterminismManifestSchema = "9e42b4cbef589ac9";
        /// <summary>The shape fingerprint of <c>DeterminismStream.Version</c>, declared in <c>src/Puck.Cli/Determinism/DeterminismStream.cs</c>.</summary>
        public const string DeterminismStreamVersion = "e998f8680234aaa2";
    }
}

namespace Puck.Cli.Formats {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>FormatVersionsLedger.Format</c>, declared in <c>src/Puck.Cli/Formats/FormatVersionsLedger.cs</c>.</summary>
        public const string FormatVersionsLedgerFormat = "25f1a8892b71cdd6";
    }
}

namespace Puck.Cli.Parity {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>ParityManifestLoader.ContractSchema</c>, declared in <c>src/Puck.Cli/Parity/ParityManifestLoader.cs</c>.</summary>
        public const string ParityManifestLoaderContractSchema = "9e3d4ce6adbf2207";
    }
}

namespace Puck.Cli.Qualification {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>QualificationReport.SchemaVersion</c>, declared in <c>src/Puck.Cli/Qualification/QualificationReport.cs</c>.</summary>
        public const string QualificationReportSchemaVersion = "f4defeca10504554";
        /// <summary>The shape fingerprint of <c>ReleaseProfile.SchemaVersion</c>, declared in <c>src/Puck.Cli/Qualification/ReleaseProfile.cs</c>.</summary>
        public const string ReleaseProfileSchemaVersion = "33b7377faadf6d4c";
    }
}
