<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Tool</PuckKind>
    </PropertyGroup>
    <PropertyGroup>
        <IsAotCompatible>false</IsAotCompatible>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <OutputType>Exe</OutputType>
        <RootNamespace>Puck.Cli</RootNamespace>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <ServerGarbageCollection>true</ServerGarbageCollection>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="[0.15.*, )" />
        <PackageReference Include="FSharp.Core" Version="[10.*, )" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="[5.*, )" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="[5.*, )" />
        <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="[5.*, )" />
        <PackageReference Include="Resharp" Version="[1.*, )" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Puck.Maths\Puck.Maths.csproj" />
        <ProjectReference Include="..\Puck.Scripting\Puck.Scripting.csproj" />
        <ProjectReference Include="..\Puck.World.Data\Puck.World.Data.csproj" />
    </ItemGroup>
    <Target Name="PublishPuckLauncher" AfterTargets="Publish">
        <Copy
            DestinationFiles="$(PublishDir)puck.exe"
            SourceFiles="$(PublishDir)$(AssemblyName).exe"
        />
    </Target>
</Project>
