// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Networking {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>LocalEndpointCapability.Revision</c>, declared in <c>src/Puck.Networking/LocalEndpointCapability.cs</c>.</summary>
        public const string LocalEndpointCapabilityRevision = "07ced790d73d1e65";
    }
}

namespace Puck.Networking.Peers {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>PeerWireProtocol.ProtocolKey</c>, declared in <c>src/Puck.Networking/Peers/PeerWireProtocol.cs</c>.</summary>
        public const string PeerWireProtocolProtocolKey = "79c9c10493b48e46";
    }
}
