<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Production</PuckKind>
        <PuckLayer>Shared substrate</PuckLayer>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Puck.Attestation\Puck.Attestation.csproj" />
        <ProjectReference Include="..\Puck.Maths\Puck.Maths.csproj" />
    </ItemGroup>
</Project>
