import React, { useState, useMemo } from "react";
import {
  Card,
  Group,
  Text,
  Badge,
  Paper,
  ScrollArea,
  SimpleGrid,
  Button,
} from "@mantine/core";
import {
  RiCompass3Fill,
  RiFocus3Line,
  RiArrowRightLine,
  RiFlashlightLine,
} from "@remixicon/react";
import {
  TopologyDefinition,
  boardShift,
  getTopologyCoordinates,
} from "../../engine/evaluator";

export interface LatticeRayStudioProps {
  topology: TopologyDefinition;
  onSelectRayBeam?: (rayName: string, cells: number[]) => void;
  activeRayName?: string | null;
}

export const LatticeRayStudio: React.FC<LatticeRayStudioProps> = ({
  topology,
  onSelectRayBeam,
  activeRayName,
}) => {
  const directions = topology.directions ?? [];
  const coords = useMemo(() => getTopologyCoordinates(topology), [topology]);

  const [selectedDirectionName, setSelectedDirectionName] = useState<string>(
    activeRayName ?? directions[0]?.name ?? "L8"
  );
  const [selectedLineIndex, setSelectedLineIndex] = useState<number>(0);

  const activeDirection = directions.find((d) => d.name === selectedDirectionName) ?? directions[0];

  // Calculate all complete 4-cell collinear lines generated by this direction
  const collinearLines = useMemo(() => {
    if (!activeDirection || coords.length === 0) return [];

    const lines: Array<{ origin: number; cells: number[] }> = [];
    const visited = new Set<string>();

    for (let origin = 0; origin < coords.length; origin++) {
      let currentMask = 1n << BigInt(origin);
      const chain: number[] = [origin];
      let valid = true;

      for (let step = 0; step < 3; step++) {
        const nextMask = boardShift(currentMask, topology, activeDirection.name);
        if (nextMask === 0n) {
          valid = false;
          break;
        }

        // Find which cell has this bit set
        let foundCell = -1;
        for (let j = 0; j < coords.length; j++) {
          if ((nextMask & (1n << BigInt(j))) !== 0n) {
            foundCell = j;
            break;
          }
        }

        if (foundCell === -1) {
          valid = false;
          break;
        }

        chain.push(foundCell);
        currentMask = nextMask;
      }

      if (valid && chain.length === 4) {
        const key = chain.join(",");
        if (!visited.has(key)) {
          visited.add(key);
          lines.push({ origin, cells: chain });
        }
      }
    }

    return lines;
  }, [activeDirection, topology, coords]);

  // Handle line selection and beam projection
  const handleSelectLine = (lineIdx: number) => {
    setSelectedLineIndex(lineIdx);
    const line = collinearLines[lineIdx];
    if (line && onSelectRayBeam && activeDirection) {
      onSelectRayBeam(activeDirection.name, line.cells);
    }
  };

  const handleSelectDirection = (dirName: string) => {
    setSelectedDirectionName(dirName);
    setSelectedLineIndex(0);
    // Find lines for this new direction and select first one
    setTimeout(() => {
      const activeDir = directions.find((d) => d.name === dirName);
      if (activeDir && onSelectRayBeam) {
        // Find origin line
        for (let origin = 0; origin < coords.length; origin++) {
          let mask = 1n << BigInt(origin);
          const chain = [origin];
          let valid = true;
          for (let s = 0; s < 3; s++) {
            const next = boardShift(mask, topology, dirName);
            if (next === 0n) { valid = false; break; }
            for (let j = 0; j < coords.length; j++) {
              if ((next & (1n << BigInt(j))) !== 0n) {
                chain.push(j);
                mask = next;
                break;
              }
            }
          }
          if (valid && chain.length === 4) {
            onSelectRayBeam(dirName, chain);
            break;
          }
        }
      }
    }, 10);
  };

  const currentActiveLine = collinearLines[selectedLineIndex] ?? collinearLines[0];

  return (
    <Card withBorder radius="md" p="sm" style={{ background: "var(--paper-2)", borderColor: "var(--rule)" }}>
      {/* Header */}
      <Group justify="space-between" mb="xs">
        <Group gap="xs">
          <RiCompass3Fill size={18} color="var(--accent-2)" />
          <Text fw={600} size="sm" style={{ fontFamily: '"Lora", Georgia, serif', color: "var(--ink)" }}>
            3D Lattice Ray Prober & Vector Inspector
          </Text>
          <Badge variant="light" color="jade" size="xs" style={{ fontFamily: '"JetBrains Mono", monospace' }}>
            {directions.length} DIRECTIONS
          </Badge>
        </Group>

        {activeDirection && (
          <Badge size="xs" color="coral" variant="filled" style={{ fontFamily: '"JetBrains Mono", monospace' }}>
            {activeDirection.name}: ({activeDirection.x}, {activeDirection.y}, {activeDirection.z})
          </Badge>
        )}
      </Group>

      {/* Direction Selection Grid */}
      <Paper p="xs" mb="xs" radius="sm" style={{ background: "var(--code-bg)", border: "1px solid var(--rule)" }}>
        <Text size="xs" fw={600} mb={6} style={{ fontFamily: '"JetBrains Mono", monospace', color: "var(--ink-soft)" }}>
          Select Lattice Direction Ray:
        </Text>
        <Group gap={6} wrap="wrap">
          {directions.map((d) => {
            const isSelected = d.name === selectedDirectionName;
            return (
              <Button
                key={d.name}
                size="compact-xs"
                variant={isSelected ? "filled" : "light"}
                color={isSelected ? "coral" : "gray"}
                onClick={() => handleSelectDirection(d.name)}
                style={{ fontFamily: '"JetBrains Mono", monospace', fontSize: 11 }}
              >
                {d.name} ({d.x},{d.y},{d.z})
              </Button>
            );
          })}
        </Group>
      </Paper>

      {/* Collinear Lines Generated by this Direction */}
      <Group justify="space-between" mb={4}>
        <Group gap={6}>
          <RiFocus3Line size={14} color="var(--accent)" />
          <Text size="xs" fw={600} style={{ fontFamily: '"JetBrains Mono", monospace' }}>
            Collinear Winning Lines along {selectedDirectionName}: {collinearLines.length} Lines
          </Text>
        </Group>
        <Text size="xs" style={{ fontFamily: '"JetBrains Mono", monospace', fontSize: 10, color: "var(--ink-faint)" }}>
          Click line to project 3D beam
        </Text>
      </Group>

      <ScrollArea h={140} mb="xs" offsetScrollbars>
        <SimpleGrid cols={{ base: 1, sm: 2 }} spacing={6}>
          {collinearLines.map((line, idx) => {
            const isSelected = idx === selectedLineIndex;
            return (
              <Paper
                key={idx}
                p={6}
                radius="xs"
                onClick={() => handleSelectLine(idx)}
                style={{
                  cursor: "pointer",
                  background: isSelected ? "var(--accent-ink)" : "var(--paper-3)",
                  border: isSelected ? "2px solid var(--accent)" : "1px solid var(--rule)",
                  transition: "all 0.15s ease",
                }}
              >
                <Group justify="space-between">
                  <Text size="xs" fw={600} style={{ fontFamily: '"JetBrains Mono", monospace', color: isSelected ? "var(--accent)" : "var(--ink)" }}>
                    Line #{idx + 1}:
                  </Text>
                  <Text size="xs" style={{ fontFamily: '"JetBrains Mono", monospace', color: "var(--ink-soft)" }}>
                    [{line.cells.join(" ➔ ")}]
                  </Text>
                </Group>
              </Paper>
            );
          })}
        </SimpleGrid>
      </ScrollArea>

      {/* Coordinate Traversal Breakdown */}
      {currentActiveLine && (
        <Paper p="xs" radius="sm" style={{ background: "var(--paper-3)", border: "1px solid var(--rule)" }}>
          <Group gap={6} mb={4}>
            <RiFlashlightLine size={13} color="var(--accent)" />
            <Text size="xs" fw={600} style={{ fontFamily: '"JetBrains Mono", monospace', color: "var(--ink)" }}>
              Beam Traversal Coordinates:
            </Text>
          </Group>
          <Group gap={8} wrap="wrap">
            {currentActiveLine.cells.map((cIdx, step) => {
              const cCoord = coords[cIdx] ?? { x: 0, y: 0, z: 0 };
              return (
                <Group key={step} gap={4}>
                  <Badge size="xs" color="jade" variant="outline" style={{ fontFamily: '"JetBrains Mono", monospace' }}>
                    Step {step + 1}: #{cIdx} ({cCoord.x}, {cCoord.y}, {cCoord.z})
                  </Badge>
                  {step < 3 && <RiArrowRightLine size={12} color="var(--ink-faint)" />}
                </Group>
              );
            })}
          </Group>
        </Paper>
      )}
    </Card>
  );
};

export default LatticeRayStudio;
