namespace Puck.Platform;

public enum InputKind {
    Text,
    Submit,
    ToggleConsole,
    Backspace,
    RecallPrevious,
    RecallNext,
    CopyInput,
    SelectAll,
    CycleFocus,
    ToggleMainMenu,
    FailsafeReset,
    Custom,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    MouseMove,
    Function1,
    Function2,
    Function3,
    Function4,
    Function5,
    Function6,
    Function7,
    Function8,
}
