<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PuckKind>Production</PuckKind>
        <PuckLayer>Engine services</PuckLayer>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Puck.Commands\Puck.Commands.csproj" />
        <ProjectReference Include="..\Puck.Launcher\Puck.Launcher.csproj" />
        <ProjectReference Include="..\Puck.Networking\Puck.Networking.csproj" />
        <ProjectReference Include="..\Puck.World.Protocol\Puck.World.Protocol.csproj" />
        <ProjectReference Include="..\Puck.World.Schema\Puck.World.Schema.csproj" />
        <ProjectReference Include="..\Puck.World.Server\Puck.World.Server.csproj" />
    </ItemGroup>
</Project>
