using System.CommandLine;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;

namespace Puck.Cli.Analysis;

public static class DerivationsCommand {
    private const string OutputPath = "src/Puck.SignedDistance/Baking/DerivationFingerprint.cs";
    private const string ProducerProject = "src/Puck.World.Authoring/Puck.World.Authoring.csproj";

    public static int Write(IReadOnlyList<DerivationResult> derivations, string repositoryRoot, bool check, TextWriter output) {
        var bake = (derivations.SingleOrDefault(predicate: derivation => (derivation.Name == "bake"))
            ?? throw new InvalidOperationException(message: "derivations: no bake entry points found"));

        if (derivations.Any(predicate: derivation => (derivation.Name != "bake"))) {
            throw new InvalidOperationException(message: "derivations: only bake has a generated destination");
        }
        var generated = ($$"""
            // <auto-generated/> Generated by puck derivations.
            namespace Puck.SignedDistance.Baking;

            /// <summary>Source provenance of derived bake products.</summary>
            public static class DerivationFingerprint {
                /// <summary>The bake producer's transitive csharp-tokens-v1 SHA-256.</summary>
                public const string Bake = "{{bake.Fingerprint}}";
                /// <summary>The first four fingerprint bytes, interpreted as an unsigned big-endian integer.</summary>
                public const uint BakeChunkVersion = 0x{{bake.Fingerprint[..8]}};
            }
            """ + "\n");
        var path = Path.Combine(path1: repositoryRoot, path2: OutputPath);

        if (check) {
            if (!File.Exists(path: path) || (File.ReadAllText(path: path) != generated)) {
                output.WriteLine(value: $"derivations: stale bake: {OutputPath}; run puck derivations");
                return 1;
            }
            output.WriteLine(value: $"derivations: bake current ({bake.Fingerprint})");
            return 0;
        }
        Directory.CreateDirectory(path: Path.GetDirectoryName(path: path)!);
        File.WriteAllText(contents: generated, path: path);
        foreach (var derivation in derivations) {
            output.WriteLine(value: $"{derivation.Name}: {derivation.Fingerprint}");
            foreach (var assembly in derivation.Symbols.GroupBy(keySelector: symbol => (symbol.Assembly, symbol.External)).OrderBy(keySelector: group => group.Key.Assembly, comparer: StringComparer.Ordinal)) {
                output.WriteLine(value: $"  {assembly.Key.Assembly} ({assembly.Count()} symbols{(assembly.Key.External ? ", external" : "")})");
                foreach (var symbol in assembly.OrderBy(keySelector: symbol => symbol.Id, comparer: StringComparer.Ordinal)) {
                    output.WriteLine(value: $"    {symbol.Id}");
                }
            }
        }
        return 0;
    }

    private static async Task<int> RunAsync(bool check) {
        if (!CliPaths.TryGetRepositoryRoot(repositoryRoot: out var root)) { return 2; }
        var manifest = XDocument.Load(uri: Path.Combine(path1: root, path2: "Puck.slnx"));

        if (!manifest.Descendants(name: "Project").Any(predicate: project => (((string?)project.Attribute(name: "Path")) == ProducerProject))) {
            throw new InvalidOperationException(message: $"derivations: solution does not contain producer {ProducerProject}");
        }
        using var workspace = new AnalysisWorkspace(configuration: "Release", verb: "derivations");
        var solution = await workspace.OpenAsync(target: Path.Combine(path1: root, path2: ProducerProject), project: true);

        if (workspace.Failed) { throw new InvalidOperationException(message: "derivations: workspace load failed; refusing an incomplete reach"); }
        var compilations = new List<Compilation>();

        foreach (var project in solution.Projects) {
            if (project.Language != LanguageNames.CSharp) { continue; }
            if (await project.GetCompilationAsync() is { } compilation) { compilations.Add(item: compilation); }
        }
        return Write(derivations: DerivationReach.Compute(compilations: compilations), repositoryRoot: root, check: check, output: Console.Out);
    }

    public static Command Create() {
        var check = CliOptions.Check(description: "Compare generated fingerprints against source; write nothing and exit 1 naming each stale derivation.");
        var command = new Command(
            description: "Generate or check bake fingerprints from their transitive source dependencies, and list the reach by assembly.",
            name: "derivations"
        ) { check };

        command.Detail(detail: """
            Loads the solution's bake producer and its full Release project reference graph, rebinding metadata to source. The shared
            csharp-tokens-v1 token framing hashes declaration ids, syntax and ordered semantic bindings in canonical order. Type headers are
            separate from member bodies; partial declarations, implicit calls and in-repo virtual/interface dispatch
            are included, as are callbacks on reached source types and public parameterless constructors of concrete generic arguments.
            Partial type initializers retain their compilation order. BCL and package symbols are listed as external, with assembly identity, and stop the walk.
            The generated fingerprint declaration is excluded from its own reach.

            Writes src/Puck.SignedDistance/Baking/DerivationFingerprint.cs. Bake keys use the full SHA-256;
            BAKE chunk and pack entry versions use the first four bytes as an unsigned big-endian integer.
            Run after changing producer dependencies, then build consumers. --check checks source freshness.

            Next slices: other compiled-world chunk versions, shader packages, GpuPipelineCacheStore content keys,
            and kernel sets. External implementation changes, reflection and dynamic dispatch are outside this
            source-syntax fingerprint; source is evaluated in the solution's Release configuration.
            """);

        command.SetAction(action: async parseResult => await RunAsync(check: parseResult.GetValue(option: check)));
        return command;
    }
}
