// Generated by puck shaders generate from WorldSkyKinds. Do not edit.
namespace Puck.Shaders;

/// <summary>Native sky tables generated from the authored kind inventory.</summary>
public static class SdfSkyKindBindings {
    /// <summary>Every registered kind in stable tag order; absent kinds use the ordinary empty region.</summary>
    public static IReadOnlyList<SdfSkyKindBinding> All { get; } = [
        new("aurora", 0u, ShaderInterfaceMember.ReadOnlyBuffer(group: ShaderInterfaceGroup.World, name: "skyAurora",
            structure: ShaderInterfaceStructure.From<SdfSkyAuroraData>())),
        new("clouds", 1u, ShaderInterfaceMember.ReadOnlyBuffer(group: ShaderInterfaceGroup.World, name: "skyClouds",
            structure: ShaderInterfaceStructure.From<SdfSkyCloudsData>())),
        new("gradient", 2u, ShaderInterfaceMember.ReadOnlyBuffer(group: ShaderInterfaceGroup.World, name: "skyGradient",
            structure: ShaderInterfaceStructure.From<SdfSkyGradientData>())),
        new("noise", 3u, ShaderInterfaceMember.ReadOnlyBuffer(group: ShaderInterfaceGroup.World, name: "skyNoise",
            structure: ShaderInterfaceStructure.From<SdfSkyNoiseData>())),
        new("panorama", 4u, ShaderInterfaceMember.ReadOnlyBuffer(group: ShaderInterfaceGroup.World, name: "skyPanorama",
            structure: ShaderInterfaceStructure.From<SdfSkyPanoramaData>())),
        new("pattern", 5u, ShaderInterfaceMember.ReadOnlyBuffer(group: ShaderInterfaceGroup.World, name: "skyPattern",
            structure: ShaderInterfaceStructure.From<SdfSkyPatternData>())),
        new("stars", 6u, ShaderInterfaceMember.ReadOnlyBuffer(group: ShaderInterfaceGroup.World, name: "skyStars",
            structure: ShaderInterfaceStructure.From<SdfSkyStarsData>())),
    ];
}
