// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.World.Transpiler.Assets {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AssetLock.SupportedFormat</c>, declared in <c>src/Puck.World.Transpiler/Assets/AssetLock.cs</c>.</summary>
        public const string AssetLockSupportedFormat = "f502582a8ff1fe38";
    }
}

namespace Puck.World.Transpiler.Composition {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>WorldCompileCache.Magic</c>, declared in <c>src/Puck.World.Transpiler/Composition/WorldCompileCache.cs</c>.</summary>
        public const string WorldCompileCacheMagic = "429b78eedf001161";
    }
}

namespace Puck.World.Transpiler.Embeddings {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>EmbeddingLock.SupportedFormat</c>, declared in <c>src/Puck.World.Transpiler/Embeddings/EmbeddingLock.cs</c>.</summary>
        public const string EmbeddingLockSupportedFormat = "c2ec76a06fd4dbef";
    }
}
