using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Operations;

namespace Puck.Analyzers;

/// <summary>
/// Refuses a read of the process environment that <see cref="EnvironmentReadAllowlist"/> does not name
/// (<see cref="Env001UnlistedEnvironmentRead"/>). Nothing in Puck is switched by an environment variable: a generated
/// file is regenerated by a <c>puck</c> verb with a <c>--check</c> twin, a runtime toggle is a flag, a document or
/// host setting, or a release-profile row, and a test's knob is its own fixture configuration.
/// <para>
/// <b>What counts as a read.</b> A call to <c>System.Environment.GetEnvironmentVariable</c> (every overload),
/// <c>GetEnvironmentVariables</c>, or <c>ExpandEnvironmentVariables</c>. A variable name must be a compile-time
/// constant naming an allowlisted variable whose entry admits the reading assembly. A name computed at run time is
/// refused, because the gate cannot see what it reads; so is <c>GetEnvironmentVariables</c>, which reads every
/// variable at once. <c>ExpandEnvironmentVariables</c> is accepted only over a constant whose every <c>%NAME%</c>
/// token is allowlisted for the assembly.
/// </para>
/// <para>
/// Writing a child process's environment (<c>ProcessStartInfo.Environment</c>) or the process's own
/// (<c>SetEnvironmentVariable</c>) is not a read and is not inspected; what the child does with it is its own
/// assembly's gate.
/// </para>
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class EnvironmentReadAnalyzer : DiagnosticAnalyzer {
    private const string Category = "Puck.Environment";

    /// <summary>ENV001: a read of the process environment that the allowlist does not admit.</summary>
    public static readonly DiagnosticDescriptor Env001UnlistedEnvironmentRead = new(
        id: "ENV001",
        title: "Environment read outside the allowlist",
        messageFormat: "'{0}' {1}; nothing in Puck is switched by an environment variable: make it a puck verb with --check, a flag, a document or profile setting, or a test fixture, or add an OS- or CI-provided variable to EnvironmentReadAllowlist with its reason",
        category: Category,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Puck reads the process environment only for values the operating system, the .NET SDK or the CI host defines, each named with its reason in one allowlist. A PUCK_* switch, a record mode or a test knob read from the environment is refused, as is any read whose variable name is not a compile-time constant."
    );

    /// <inheritdoc/>
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics { get; } =
        ImmutableArray.Create(item: Env001UnlistedEnvironmentRead);

    /// <inheritdoc/>
    public override void Initialize(AnalysisContext context) {
        context.EnableConcurrentExecution();
        // A generated read switches the process exactly as a hand-written one does.
        context.ConfigureGeneratedCodeAnalysis(analysisMode: GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics);
        context.RegisterOperationAction(
            action: AnalyzeInvocation,
            operationKinds: OperationKind.Invocation
        );
    }

    private static void AnalyzeInvocation(OperationAnalysisContext context) {
        var invocation = ((IInvocationOperation)context.Operation);
        var method = invocation.TargetMethod;

        if (
            (method.ContainingType?.Name != "Environment") ||
            (method.ContainingType.ContainingNamespace?.ToDisplayString() != "System")
        ) {
            return;
        }

        var assembly = (context.Compilation.AssemblyName ?? string.Empty);
        string? refusal;

        switch (method.Name) {
            case "GetEnvironmentVariable":
                refusal = RefuseName(
                    argument: invocation.Arguments.FirstOrDefault(),
                    assembly: assembly
                );
                break;
            case "GetEnvironmentVariables":
                refusal = "reads every environment variable at once";
                break;
            case "ExpandEnvironmentVariables":
                refusal = RefuseExpansion(
                    argument: invocation.Arguments.FirstOrDefault(),
                    assembly: assembly
                );
                break;
            default:
                return;
        }

        if (refusal is null) {
            return;
        }

        context.ReportDiagnostic(diagnostic: Diagnostic.Create(
            descriptor: Env001UnlistedEnvironmentRead,
            location: invocation.Syntax.GetLocation(),
            messageArgs: [("Environment." + method.Name), refusal]
        ));
    }
    private static string? RefuseExpansion(IArgumentOperation? argument, string assembly) {
        if (
            (argument?.Value.ConstantValue is not { HasValue: true, Value: string text })
        ) {
            return "expands a string that is not a compile-time constant";
        }

        var start = text.IndexOf(value: '%');

        while (start >= 0) {
            var end = text.IndexOf(
                startIndex: (start + 1),
                value: '%'
            );

            if (end < 0) {
                break;
            }

            var name = text.Substring(
                length: ((end - start) - 1),
                startIndex: (start + 1)
            );

            if (!EnvironmentReadAllowlist.Admits(
                assembly: assembly,
                name: name
            )) {
                return $"expands '%{name}%', which is not allowlisted for {assembly}";
            }

            start = text.IndexOf(
                startIndex: (end + 1),
                value: '%'
            );
        }

        return null;
    }
    private static string? RefuseName(IArgumentOperation? argument, string assembly) {
        if (argument?.Value.ConstantValue is not { HasValue: true, Value: string name }) {
            return "reads a variable whose name is not a compile-time constant";
        }

        return (EnvironmentReadAllowlist.Admits(
            assembly: assembly,
            name: name
        )
            ? null
            : $"reads '{name}', which is not allowlisted for {assembly}"
        );
    }
}
