// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Analyzers {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>RatchetLedger.Format</c>, declared in <c>src/Puck.Analyzers/RatchetLedger.cs</c>.</summary>
        public const string RatchetLedgerFormat = "502b64b1a7fdfb39";
        /// <summary>The shape fingerprint of <c>VerifiedCodeManifest.SupportedFormat</c>, declared in <c>src/Puck.Analyzers/VerifiedCodeManifest.cs</c>.</summary>
        public const string VerifiedCodeManifestSupportedFormat = "7e37cba0af1e4d6a";
        /// <summary>The shape fingerprint of <c>VerifiedCodeManifest.TokenAlgorithm</c>, declared in <c>src/Puck.Analyzers/VerifiedCodeManifest.cs</c>.</summary>
        public const string VerifiedCodeManifestTokenAlgorithm = "e73ea86e926391c3";
    }
}
