// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Analyzers {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>RatchetLedger.Format</c>, declared in <c>src/Puck.Analyzers/RatchetLedger.cs</c>.</summary>
        public const string RatchetLedgerFormat = "ac0c375b5bb35099";
        /// <summary>The shape fingerprint of <c>VerifiedCodeManifest.SupportedFormat</c>, declared in <c>src/Puck.Analyzers/VerifiedCodeManifest.cs</c>.</summary>
        public const string VerifiedCodeManifestSupportedFormat = "35feece16a3f486b";
        /// <summary>The shape fingerprint of <c>VerifiedCodeManifest.TokenAlgorithm</c>, declared in <c>src/Puck.Analyzers/VerifiedCodeManifest.cs</c>.</summary>
        public const string VerifiedCodeManifestTokenAlgorithm = "35feece16a3f486b";
    }
}
