// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Assets {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AutomaticIntegerSequenceCodec.Magic</c>, declared in <c>src/Puck.Assets/AutomaticSequenceCodec.cs</c>.</summary>
        public const string AutomaticIntegerSequenceCodecMagic = "95f53d3a5445b007";
        /// <summary>The shape fingerprint of <c>AutomaticIntegerSequenceCodec.Version</c>, declared in <c>src/Puck.Assets/AutomaticSequenceCodec.cs</c>.</summary>
        public const string AutomaticIntegerSequenceCodecVersion = "95f53d3a5445b007";
        /// <summary>The shape fingerprint of <c>WasmBinaryFormat.Magic</c>, declared in <c>src/Puck.Assets/WasmBinaryFormat.cs</c>.</summary>
        public const string WasmBinaryFormatMagic = "efcac5ab09c64267";
    }
}

namespace Puck.Assets.Documents {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AudioDocument.CurrentSchema</c>, declared in <c>src/Puck.Assets/Documents/AudioDocument.cs</c>.</summary>
        public const string AudioDocumentCurrentSchema = "dc1219fc0e63322f";
        /// <summary>The shape fingerprint of <c>SynthPatchDocument.CurrentSchema</c>, declared in <c>src/Puck.Assets/Documents/SynthPatchDocument.cs</c>.</summary>
        public const string SynthPatchDocumentCurrentSchema = "e6ddcc987e88eebf";
    }
}
