// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Assets {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AutomaticIntegerSequenceCodec.Magic</c>, declared in <c>src/Puck.Assets/AutomaticSequenceCodec.cs</c>.</summary>
        public const string AutomaticIntegerSequenceCodecMagic = "2191675f60663a9f";
        /// <summary>The shape fingerprint of <c>AutomaticIntegerSequenceCodec.Version</c>, declared in <c>src/Puck.Assets/AutomaticSequenceCodec.cs</c>.</summary>
        public const string AutomaticIntegerSequenceCodecVersion = "2191675f60663a9f";
    }
}

namespace Puck.Assets.Documents {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AudioDocument.CurrentSchema</c>, declared in <c>src/Puck.Assets/Documents/AudioDocument.cs</c>.</summary>
        public const string AudioDocumentCurrentSchema = "86fae063b05bb1a7";
        /// <summary>The shape fingerprint of <c>SynthPatchDocument.CurrentSchema</c>, declared in <c>src/Puck.Assets/Documents/SynthPatchDocument.cs</c>.</summary>
        public const string SynthPatchDocumentCurrentSchema = "26a8894f24ed9843";
    }
}
