// <auto-generated/>
// Generated by `puck formats` from the shape digests recorded in FormatVersions.json; do not hand-edit.
// `puck formats --check` fails when this file disagrees with the source.
#nullable enable

namespace Puck.Assets {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AutomaticIntegerSequenceCodec.Magic</c>, declared in <c>src/Puck.Assets/AutomaticSequenceCodec.cs</c>.</summary>
        public const string AutomaticIntegerSequenceCodecMagic = "d22890e94ba81023";
        /// <summary>The shape fingerprint of <c>AutomaticIntegerSequenceCodec.Version</c>, declared in <c>src/Puck.Assets/AutomaticSequenceCodec.cs</c>.</summary>
        public const string AutomaticIntegerSequenceCodecVersion = "d22890e94ba81023";
        /// <summary>The shape fingerprint of <c>WasmBinaryFormat.Magic</c>, declared in <c>src/Puck.Assets/WasmBinaryFormat.cs</c>.</summary>
        public const string WasmBinaryFormatMagic = "293a4f56b6458d75";
    }
}

namespace Puck.Assets.Documents {
    /// <summary>The shape fingerprint of each format this namespace declares: the digest <c>puck formats</c> records for it.
    /// A codec writes its constant in its header or handshake and refuses any other value by name.</summary>
    internal static class FormatShapes {
        /// <summary>The shape fingerprint of <c>AudioDocument.CurrentSchema</c>, declared in <c>src/Puck.Assets/Documents/AudioDocument.cs</c>.</summary>
        public const string AudioDocumentCurrentSchema = "ee1681a93b47384d";
        /// <summary>The shape fingerprint of <c>SynthPatchDocument.CurrentSchema</c>, declared in <c>src/Puck.Assets/Documents/SynthPatchDocument.cs</c>.</summary>
        public const string SynthPatchDocumentCurrentSchema = "785cc2a006e0c9ad";
    }
}
