using System.Globalization;
using System.Reflection;
using System.Text;
using Puck.SignedDistance;
using Puck.SignedDistance.Illumination;

namespace Puck.SdfVm;

/// <summary>Generates the radiance cache's strides, offsets, tier constants and terminal vocabulary.</summary>
public static class SdfIndirectHlsl {
    /// <summary>The generated layout include.</summary>
    public const string Path = "src/Puck.SdfVm/Assets/Shaders/Sdf/isa/sdf-indirect-layout.hlsli";

    /// <summary>Writes the layout from its host declaration.</summary>
    /// <returns>The shader declaration.</returns>
    public static string Generate() {
        var text = new StringBuilder(value: "// Generated by puck shaders generate from SdfIndirectLayout.\n#ifndef SDF_INDIRECT_LAYOUT_HLSLI\n#define SDF_INDIRECT_LAYOUT_HLSLI\n");

        foreach (var field in typeof(SdfIndirectLayout).GetFields(bindingAttr: BindingFlags.Public | BindingFlags.Static).Where(predicate: static field => field.IsLiteral)) {
            text.Append(CultureInfo.InvariantCulture, $"static const uint SdfIndirect{field.Name} = {field.GetRawConstantValue()}u;\n");
        }
        Enum<SdfIndirectTier>(prefix: "SdfIndirectTier");
        Enum<IrradianceProbeClass>(prefix: "SdfIndirectClass");
        Enum<IrradianceHitKind>(prefix: "SdfIndirectKind");
        var medium = new SdfIndirectLayout(tier: SdfIndirectTier.Medium);
        var high = new SdfIndirectLayout(tier: SdfIndirectTier.High);

        foreach (var property in typeof(SdfIndirectLayout).GetProperties().Where(predicate: static property => (property.PropertyType == typeof(int)))) {
            text.Append(CultureInfo.InvariantCulture,
                $"uint sdfIndirect{property.Name}(uint tier) {{ return tier == SdfIndirectTierHigh ? {property.GetValue(obj: high)}u : (tier == SdfIndirectTierMedium ? {property.GetValue(obj: medium)}u : 0u); }}\n");
        }
        text.Append(CultureInfo.InvariantCulture, $"static const float SdfIndirectSurfaceEpsilon = {IrradianceAcceptance.SurfaceEpsilon:R};\n");
        text.Append(CultureInfo.InvariantCulture, $"static const float SdfIndirectRelocationAllowance = {IrradianceCells.RelocationAllowance:R};\n");
        text.Append(CultureInfo.InvariantCulture, $"static const float SdfIndirectMinimumClearance = {IrradianceCells.MinimumClearance:R};\n");
        text.Append(CultureInfo.InvariantCulture, $"static const float SdfIndirectReceiverBias = {IrradianceCells.ReceiverBias:R};\n");
        text.Append(CultureInfo.InvariantCulture, $"static const float SdfIndirectPlaneTolerance = {IrradianceCells.PlaneTolerance:R};\n");
        text.Append(CultureInfo.InvariantCulture, $"static const float SdfIndirectResolution = {IrradianceField.Resolution:R};\n");
        text.Append(value: "float sdfIndirectSpacing(uint tier, uint level) {\n");
        Levels(member: "Spacing");
        text.Append(value: "float sdfIndirectReach(uint tier, uint level) {\n");
        Levels(member: "Reach");
        text.Append(value: "#endif\n");
        return text.ToString();

        void Enum<T>(string prefix) where T : struct, System.Enum {
            foreach (var item in System.Enum.GetValues<T>()) {
                text.Append(CultureInfo.InvariantCulture, $"static const uint {prefix}{item} = {Convert.ToUInt32(value: item, provider: CultureInfo.InvariantCulture)}u;\n");
            }
        }
        void Levels(string member) {
            text.Append(value: "    if (tier == SdfIndirectTierHigh) {\n");
            Write(layout: high);
            text.Append(value: "    } else {\n");
            Write(layout: medium);
            text.Append(value: "    }\n    return 0.0;\n}\n");
            void Write(SdfIndirectLayout layout) {
                for (var index = 0; (index < layout.Levels.Count); index++) {
                    var level = layout.Levels[index];
                    var value = ((member == "Spacing") ? level.Spacing : level.Reach);

                    text.Append(CultureInfo.InvariantCulture, $"        if (level == {index}u) return {value:0.0################};\n");
                }
            }
        }
    }
}
