namespace Puck.HumbleGamingDeck;

public sealed partial class HgdCpu<TBus> {
    private enum Operation : byte {
        Brk,
        Ora,
        Jam,
        Slo,
        Nop,
        Asl,
        Php,
        Anc,
        Bpl,
        Clc,
        Jsr,
        And,
        Rla,
        Bit,
        Rol,
        Plp,
        Bmi,
        Sec,
        Rti,
        Eor,
        Sre,
        Lsr,
        Pha,
        Alr,
        Jmp,
        Bvc,
        Cli,
        Rts,
        Adc,
        Rra,
        Ror,
        Pla,
        Arr,
        Bvs,
        Sei,
        Sta,
        Sax,
        Sty,
        Stx,
        Dey,
        Txa,
        Xaa,
        Bcc,
        Ahx,
        Tya,
        Txs,
        Tas,
        Shy,
        Shx,
        Ldy,
        Lda,
        Ldx,
        Lax,
        Tay,
        Tax,
        Lxa,
        Bcs,
        Clv,
        Tsx,
        Las,
        Cpy,
        Cmp,
        Dcp,
        Dec,
        Iny,
        Dex,
        Axs,
        Bne,
        Cld,
        Cpx,
        Sbc,
        Isc,
        Inc,
        Inx,
        Beq,
        Sed,
    }
    private enum AddressMode : byte {
        Special,
        IndirectX,
        ZeroPage,
        Immediate,
        Accumulator,
        Absolute,
        Relative,
        IndirectY,
        ZeroPageX,
        Implied,
        AbsoluteY,
        AbsoluteX,
        Indirect,
        ZeroPageY,
    }
    private readonly record struct Instruction(Operation Operation, AddressMode Mode);

    // Every opcode indexes exactly one operation and bus sequence; the table order is the byte encoding.
    private static readonly Instruction[] Instructions = [
        new(Mode: AddressMode.Special, Operation: Operation.Brk),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Ora),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Slo),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Ora),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Asl),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Slo),
        new(Mode: AddressMode.Special, Operation: Operation.Php),
        new(Mode: AddressMode.Immediate, Operation: Operation.Ora),
        new(Mode: AddressMode.Accumulator, Operation: Operation.Asl),
        new(Mode: AddressMode.Immediate, Operation: Operation.Anc),
        new(Mode: AddressMode.Absolute, Operation: Operation.Nop),
        new(Mode: AddressMode.Absolute, Operation: Operation.Ora),
        new(Mode: AddressMode.Absolute, Operation: Operation.Asl),
        new(Mode: AddressMode.Absolute, Operation: Operation.Slo),
        new(Mode: AddressMode.Relative, Operation: Operation.Bpl),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Ora),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Slo),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Ora),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Asl),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Slo),
        new(Mode: AddressMode.Implied, Operation: Operation.Clc),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Ora),
        new(Mode: AddressMode.Implied, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Slo),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Ora),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Asl),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Slo),
        new(Mode: AddressMode.Special, Operation: Operation.Jsr),
        new(Mode: AddressMode.IndirectX, Operation: Operation.And),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Rla),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Bit),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.And),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Rol),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Rla),
        new(Mode: AddressMode.Special, Operation: Operation.Plp),
        new(Mode: AddressMode.Immediate, Operation: Operation.And),
        new(Mode: AddressMode.Accumulator, Operation: Operation.Rol),
        new(Mode: AddressMode.Immediate, Operation: Operation.Anc),
        new(Mode: AddressMode.Absolute, Operation: Operation.Bit),
        new(Mode: AddressMode.Absolute, Operation: Operation.And),
        new(Mode: AddressMode.Absolute, Operation: Operation.Rol),
        new(Mode: AddressMode.Absolute, Operation: Operation.Rla),
        new(Mode: AddressMode.Relative, Operation: Operation.Bmi),
        new(Mode: AddressMode.IndirectY, Operation: Operation.And),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Rla),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.And),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Rol),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Rla),
        new(Mode: AddressMode.Implied, Operation: Operation.Sec),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.And),
        new(Mode: AddressMode.Implied, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Rla),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.And),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Rol),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Rla),
        new(Mode: AddressMode.Special, Operation: Operation.Rti),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Eor),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Sre),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Eor),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Lsr),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Sre),
        new(Mode: AddressMode.Special, Operation: Operation.Pha),
        new(Mode: AddressMode.Immediate, Operation: Operation.Eor),
        new(Mode: AddressMode.Accumulator, Operation: Operation.Lsr),
        new(Mode: AddressMode.Immediate, Operation: Operation.Alr),
        new(Mode: AddressMode.Absolute, Operation: Operation.Jmp),
        new(Mode: AddressMode.Absolute, Operation: Operation.Eor),
        new(Mode: AddressMode.Absolute, Operation: Operation.Lsr),
        new(Mode: AddressMode.Absolute, Operation: Operation.Sre),
        new(Mode: AddressMode.Relative, Operation: Operation.Bvc),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Eor),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Sre),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Eor),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Lsr),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Sre),
        new(Mode: AddressMode.Implied, Operation: Operation.Cli),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Eor),
        new(Mode: AddressMode.Implied, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Sre),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Eor),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Lsr),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Sre),
        new(Mode: AddressMode.Special, Operation: Operation.Rts),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Adc),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Rra),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Adc),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Ror),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Rra),
        new(Mode: AddressMode.Special, Operation: Operation.Pla),
        new(Mode: AddressMode.Immediate, Operation: Operation.Adc),
        new(Mode: AddressMode.Accumulator, Operation: Operation.Ror),
        new(Mode: AddressMode.Immediate, Operation: Operation.Arr),
        new(Mode: AddressMode.Indirect, Operation: Operation.Jmp),
        new(Mode: AddressMode.Absolute, Operation: Operation.Adc),
        new(Mode: AddressMode.Absolute, Operation: Operation.Ror),
        new(Mode: AddressMode.Absolute, Operation: Operation.Rra),
        new(Mode: AddressMode.Relative, Operation: Operation.Bvs),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Adc),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Rra),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Adc),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Ror),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Rra),
        new(Mode: AddressMode.Implied, Operation: Operation.Sei),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Adc),
        new(Mode: AddressMode.Implied, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Rra),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Adc),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Ror),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Rra),
        new(Mode: AddressMode.Immediate, Operation: Operation.Nop),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Sta),
        new(Mode: AddressMode.Immediate, Operation: Operation.Nop),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Sax),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Sty),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Sta),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Stx),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Sax),
        new(Mode: AddressMode.Implied, Operation: Operation.Dey),
        new(Mode: AddressMode.Immediate, Operation: Operation.Nop),
        new(Mode: AddressMode.Implied, Operation: Operation.Txa),
        new(Mode: AddressMode.Immediate, Operation: Operation.Xaa),
        new(Mode: AddressMode.Absolute, Operation: Operation.Sty),
        new(Mode: AddressMode.Absolute, Operation: Operation.Sta),
        new(Mode: AddressMode.Absolute, Operation: Operation.Stx),
        new(Mode: AddressMode.Absolute, Operation: Operation.Sax),
        new(Mode: AddressMode.Relative, Operation: Operation.Bcc),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Sta),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Ahx),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Sty),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Sta),
        new(Mode: AddressMode.ZeroPageY, Operation: Operation.Stx),
        new(Mode: AddressMode.ZeroPageY, Operation: Operation.Sax),
        new(Mode: AddressMode.Implied, Operation: Operation.Tya),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Sta),
        new(Mode: AddressMode.Implied, Operation: Operation.Txs),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Tas),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Shy),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Sta),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Shx),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Ahx),
        new(Mode: AddressMode.Immediate, Operation: Operation.Ldy),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Lda),
        new(Mode: AddressMode.Immediate, Operation: Operation.Ldx),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Lax),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Ldy),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Lda),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Ldx),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Lax),
        new(Mode: AddressMode.Implied, Operation: Operation.Tay),
        new(Mode: AddressMode.Immediate, Operation: Operation.Lda),
        new(Mode: AddressMode.Implied, Operation: Operation.Tax),
        new(Mode: AddressMode.Immediate, Operation: Operation.Lxa),
        new(Mode: AddressMode.Absolute, Operation: Operation.Ldy),
        new(Mode: AddressMode.Absolute, Operation: Operation.Lda),
        new(Mode: AddressMode.Absolute, Operation: Operation.Ldx),
        new(Mode: AddressMode.Absolute, Operation: Operation.Lax),
        new(Mode: AddressMode.Relative, Operation: Operation.Bcs),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Lda),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Lax),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Ldy),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Lda),
        new(Mode: AddressMode.ZeroPageY, Operation: Operation.Ldx),
        new(Mode: AddressMode.ZeroPageY, Operation: Operation.Lax),
        new(Mode: AddressMode.Implied, Operation: Operation.Clv),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Lda),
        new(Mode: AddressMode.Implied, Operation: Operation.Tsx),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Las),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Ldy),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Lda),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Ldx),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Lax),
        new(Mode: AddressMode.Immediate, Operation: Operation.Cpy),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Cmp),
        new(Mode: AddressMode.Immediate, Operation: Operation.Nop),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Dcp),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Cpy),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Cmp),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Dec),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Dcp),
        new(Mode: AddressMode.Implied, Operation: Operation.Iny),
        new(Mode: AddressMode.Immediate, Operation: Operation.Cmp),
        new(Mode: AddressMode.Implied, Operation: Operation.Dex),
        new(Mode: AddressMode.Immediate, Operation: Operation.Axs),
        new(Mode: AddressMode.Absolute, Operation: Operation.Cpy),
        new(Mode: AddressMode.Absolute, Operation: Operation.Cmp),
        new(Mode: AddressMode.Absolute, Operation: Operation.Dec),
        new(Mode: AddressMode.Absolute, Operation: Operation.Dcp),
        new(Mode: AddressMode.Relative, Operation: Operation.Bne),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Cmp),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Dcp),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Cmp),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Dec),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Dcp),
        new(Mode: AddressMode.Implied, Operation: Operation.Cld),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Cmp),
        new(Mode: AddressMode.Implied, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Dcp),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Cmp),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Dec),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Dcp),
        new(Mode: AddressMode.Immediate, Operation: Operation.Cpx),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Sbc),
        new(Mode: AddressMode.Immediate, Operation: Operation.Nop),
        new(Mode: AddressMode.IndirectX, Operation: Operation.Isc),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Cpx),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Sbc),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Inc),
        new(Mode: AddressMode.ZeroPage, Operation: Operation.Isc),
        new(Mode: AddressMode.Implied, Operation: Operation.Inx),
        new(Mode: AddressMode.Immediate, Operation: Operation.Sbc),
        new(Mode: AddressMode.Implied, Operation: Operation.Nop),
        new(Mode: AddressMode.Immediate, Operation: Operation.Sbc),
        new(Mode: AddressMode.Absolute, Operation: Operation.Cpx),
        new(Mode: AddressMode.Absolute, Operation: Operation.Sbc),
        new(Mode: AddressMode.Absolute, Operation: Operation.Inc),
        new(Mode: AddressMode.Absolute, Operation: Operation.Isc),
        new(Mode: AddressMode.Relative, Operation: Operation.Beq),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Sbc),
        new(Mode: AddressMode.Special, Operation: Operation.Jam),
        new(Mode: AddressMode.IndirectY, Operation: Operation.Isc),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Nop),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Sbc),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Inc),
        new(Mode: AddressMode.ZeroPageX, Operation: Operation.Isc),
        new(Mode: AddressMode.Implied, Operation: Operation.Sed),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Sbc),
        new(Mode: AddressMode.Implied, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteY, Operation: Operation.Isc),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Nop),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Sbc),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Inc),
        new(Mode: AddressMode.AbsoluteX, Operation: Operation.Isc),
    ];

    private Operation CurrentOperation => Instructions[m_opcode].Operation;
    private AddressMode CurrentMode => Instructions[m_opcode].Mode;
    private bool IsStore => (CurrentOperation is Operation.Sta or Operation.Stx or Operation.Sty or Operation.Sax or Operation.Ahx or Operation.Shx or Operation.Shy or Operation.Tas);
    private bool IsModify => (CurrentOperation is Operation.Asl or Operation.Lsr or Operation.Rol or Operation.Ror or Operation.Inc or Operation.Dec or Operation.Slo or Operation.Sre or Operation.Rla or Operation.Rra or Operation.Dcp or Operation.Isc);
}
