namespace Puck.Maths;

/// <summary>
/// A magma term: an n-ary planar tree over generator symbols. Words are the flat normal form the associative regime
/// produces; they are never the foundation.
/// </summary>
/// <remarks>
/// A node's symbol is either <see cref="Product"/> — the bracket itself, carrying no factor — or a generator symbol,
/// in which case that generator is the node's first factor and its children follow in order. A leaf is the node with
/// no children. A default-initialized term is not a valid term; obtain one from <see cref="Leaf"/>,
/// <see cref="Node"/>, or <see cref="Unit"/>.
/// </remarks>
public readonly struct Term {
    /// <summary>The symbol of a bracket that carries no factor of its own.</summary>
    public const int Product = -1;

    private readonly Term[] m_children;

    private Term(int symbol, Term[] children) {
        var degree = ((Product == symbol) ? 0 : 1);

        foreach (var child in children) { degree += child.Degree; }

        Degree = degree;
        Symbol = symbol;
        m_children = children;
    }

    /// <summary>Gets the children, in planar order.</summary>
    public ReadOnlySpan<Term> Children => m_children;
    /// <summary>Gets the number of generator occurrences in the tree — the length of the word it flattens to.</summary>
    public int Degree { get; }
    /// <summary>Gets the node's symbol: a generator, or <see cref="Product"/> for a bare bracket.</summary>
    public int Symbol { get; }
    /// <summary>Gets the empty product — the unit term.</summary>
    public static Term Unit => new(symbol: Product, children: []);

    /// <summary>Creates a leaf term: one generator, no children.</summary>
    /// <param name="symbol">The generator's symbol.</param>
    /// <returns>The leaf.</returns>
    public static Term Leaf(int symbol) =>
        new(symbol: symbol, children: []);
    /// <summary>Creates an interior term: a head symbol followed by its children in planar order.</summary>
    /// <param name="symbol">A generator's symbol, or <see cref="Product"/> for a bare bracket.</param>
    /// <param name="children">The children, in planar order; arity is data, never two.</param>
    /// <returns>The node.</returns>
    public static Term Node(int symbol, ReadOnlySpan<Term> children) =>
        new(symbol: symbol, children: children.ToArray());
}

/// <summary>
/// The generated dense product table: the result keys and charges of every ordered pair of normal-form keys. It is
/// GENERATED by the interpreted normalizer, never authored beside it, and it is eager and immutable, so no lazy build
/// can race.
/// </summary>
/// <typeparam name="TValue">The material's carrier.</typeparam>
/// <remarks>A cell is a charged combination, not necessarily a single term: a monic reduction of degree two or more
/// sends one pair to several normal forms. The two-argument <see cref="Target(long, long)"/> and
/// <see cref="Charge(long, long)"/> read the cell's leading entry, which is the whole cell exactly when
/// <see cref="TargetCount"/> is one; the indexed overloads read the rest. An empty cell is annihilation — the
/// charge-zero mechanism a degenerate generator already uses.</remarks>
public readonly struct CompiledProduct<TValue> {
    private readonly TValue[] m_charge;
    private readonly long[] m_start;
    private readonly long[] m_target;
    private readonly TValue m_zero;

    internal CompiledProduct(int keyCount, long[] start, long[] target, TValue[] charge, TValue zero) {
        KeyCount = keyCount;
        m_charge = charge;
        m_start = start;
        m_target = target;
        m_zero = zero;
    }

    /// <summary>Gets the number of ordered key pairs the table covers.</summary>
    public int CellCount => (KeyCount * KeyCount);
    /// <summary>Gets the number of normal-form keys.</summary>
    public int KeyCount { get; }

    /// <summary>Gets the charge on a cell's leading entry, or the material's zero when the cell is annihilated.</summary>
    /// <param name="leftKey">The left key.</param>
    /// <param name="rightKey">The right key.</param>
    /// <returns>The charge.</returns>
    /// <exception cref="ArgumentOutOfRangeException">A key is outside the normal-form range.</exception>
    public TValue Charge(long leftKey, long rightKey) =>
        ((0 == TargetCount(leftKey: leftKey, rightKey: rightKey))
            ? m_zero
            : Charge(leftKey: leftKey, rightKey: rightKey, index: 0));
    /// <summary>Gets the charge on one entry of a cell.</summary>
    /// <param name="leftKey">The left key.</param>
    /// <param name="rightKey">The right key.</param>
    /// <param name="index">The entry's index, below <see cref="TargetCount"/>.</param>
    /// <returns>The charge.</returns>
    /// <exception cref="ArgumentOutOfRangeException">A key or the index is outside its range.</exception>
    public TValue Charge(long leftKey, long rightKey, int index) =>
        m_charge[EntryOffset(leftKey: leftKey, rightKey: rightKey, index: index)];
    /// <summary>Gets the target key of a cell's leading entry, or <c>-1</c> when the cell is annihilated.</summary>
    /// <param name="leftKey">The left key.</param>
    /// <param name="rightKey">The right key.</param>
    /// <returns>The target key.</returns>
    /// <exception cref="ArgumentOutOfRangeException">A key is outside the normal-form range.</exception>
    public long Target(long leftKey, long rightKey) =>
        ((0 == TargetCount(leftKey: leftKey, rightKey: rightKey))
            ? -1L
            : Target(leftKey: leftKey, rightKey: rightKey, index: 0));
    /// <summary>Gets the target key of one entry of a cell.</summary>
    /// <param name="leftKey">The left key.</param>
    /// <param name="rightKey">The right key.</param>
    /// <param name="index">The entry's index, below <see cref="TargetCount"/>.</param>
    /// <returns>The target key.</returns>
    /// <exception cref="ArgumentOutOfRangeException">A key or the index is outside its range.</exception>
    public long Target(long leftKey, long rightKey, int index) =>
        m_target[EntryOffset(leftKey: leftKey, rightKey: rightKey, index: index)];
    /// <summary>Gets the number of normal forms one ordered key pair reduces to.</summary>
    /// <param name="leftKey">The left key.</param>
    /// <param name="rightKey">The right key.</param>
    /// <returns>The entry count; zero when the cell is annihilated.</returns>
    /// <exception cref="ArgumentOutOfRangeException">A key is outside the normal-form range.</exception>
    public int TargetCount(long leftKey, long rightKey) {
        var cell = CellIndex(leftKey: leftKey, rightKey: rightKey);

        return ((int)(m_start[(cell + 1)] - m_start[cell]));
    }

    private long CellIndex(long leftKey, long rightKey) {
        if ((leftKey < 0L) || (leftKey >= KeyCount)) {
            throw new ArgumentOutOfRangeException(paramName: nameof(leftKey), message: "The key names no normal form of this presentation.");
        }

        if ((rightKey < 0L) || (rightKey >= KeyCount)) {
            throw new ArgumentOutOfRangeException(paramName: nameof(rightKey), message: "The key names no normal form of this presentation.");
        }

        return ((leftKey * KeyCount) + rightKey);
    }
    private long EntryOffset(long leftKey, long rightKey, int index) {
        var cell = CellIndex(leftKey: leftKey, rightKey: rightKey);
        var start = m_start[cell];

        ArgumentOutOfRangeException.ThrowIfNegative(value: index);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(value: (start + index), other: m_start[(cell + 1)], paramName: nameof(index));

        return (start + index);
    }
}

/// <summary>
/// The presented charged algebra over a material: one graft-and-normalize product, its generated compiled form, and
/// the guarded sum. Every instance in this library differs from every other ONLY by its presentation value and its
/// material type argument — there is no dispatch table and no per-instance kernel.
/// </summary>
/// <typeparam name="TValue">The material's carrier.</typeparam>
/// <typeparam name="TOps">The material.</typeparam>
/// <remarks>
/// <para>
/// <b>Where the product comes from.</b> The product of two normal forms is graft-and-normalize: the two words are
/// grafted into one term and rewritten under the charged rules. When the presentation has finitely many normal forms
/// that resolution is performed once, at construction, for every ordered key pair — the eager
/// <see cref="CompiledProduct{TValue}"/> — so the running product is a table read followed by exactly one
/// <see cref="IMaterialOps{TValue, TOps}.FusedChargedSum"/> per distinct result key, and the rounding discipline is one
/// rounding per returned coefficient. When the normal-form set is not finite the same normalizer runs per support pair
/// instead. <see cref="TryNormalize"/> always runs it directly, and the compiled cells are proved equal to it — not as
/// an independent oracle, since <see cref="Compile"/> returns cells that same rewriter produced at construction, but as
/// the interpreted route: what that agreement pins is the term-tree flatten and rebalance path, the compiled table's
/// indexing and transposed rebuild, and the dense fold the running product uses.
/// </para>
/// <para>
/// <b>Buffers and threads.</b> Every working buffer the dense product needs — the operand scatter, the per-key term
/// spans sized by <see cref="ChargedPresentation{TValue, TOps}.MaximumCellTerms"/>, and the compaction scratch — is
/// allocated once, at construction. A product therefore allocates only its result support, and squaring in a loop
/// allocates nothing else. Those buffers are mutable state, so ONE instance is not safe for concurrent use; the
/// presentation it wraps is immutable and shareable, and <see cref="Create"/> is cheap.
/// </para>
/// <para>
/// <b>Charges and rounding.</b> The rule charges along one derivation are multiplied in the material. Over an exact
/// material, and over the house scalar at <see cref="ChargeLane.Exact"/>, that is exact; over the house scalar at
/// <see cref="ChargeLane.General"/> a derivation that applies two or more charged rules rounds once per rule, so the
/// one-rounding contract covers a General-lane presentation exactly when its reductions are single-step — which every
/// rank-two relation is.
/// </para>
/// </remarks>
public sealed partial class PresentedAlgebra<TValue, TOps>
    where TOps : struct, IMaterialOps<TValue, TOps> {
    private readonly TValue[] m_compactCoefficients;
    private readonly long[] m_compactKeys;
    private readonly CompiledProduct<TValue> m_compiled;
    private readonly TValue[] m_denseLeft;
    private readonly TValue[] m_denseRight;
    private readonly Element[] m_generatorElements;
    private readonly bool m_exactSemiringLicensed;
    private readonly long[] m_fullKeys;
    private readonly bool m_idempotentLicensed;
    private readonly bool m_isDense;
    private readonly int m_keyCount;
    private readonly ChargeLane m_lane;
    private readonly TOps m_material;
    private readonly ISignedMaterial<TValue, TOps>? m_signed;
    private readonly TValue[] m_targetCharge;
    private readonly int[] m_targetLeft;
    private readonly int[] m_targetRight;
    private readonly int[] m_targetStart;
    private readonly TValue[] m_termCharge;
    private readonly TValue[] m_termLeft;
    private readonly TValue[] m_termRight;
    private readonly ChargedPresentation<TValue, TOps>.KeyedCombination m_supportScratch = new();
    private TValue[] m_sumCoefficients = [];
    private long[] m_sumKeys = [];

    private PresentedAlgebra(ChargedPresentation<TValue, TOps> presentation) {
        var material = presentation.Material;

        Presentation = presentation;
        m_exactSemiringLicensed = (material is IExactSemiringMaterial<TValue, TOps>);
        m_idempotentLicensed = (material is IIdempotentMaterial<TValue, TOps>);
        m_isDense = presentation.HasCompiledNormalFormBasis;
        m_keyCount = presentation.NormalFormCount;
        m_lane = presentation.Lane;
        m_material = material;
        m_signed = (material as ISignedMaterial<TValue, TOps>);
        m_compactCoefficients = new TValue[m_keyCount];
        m_compactKeys = new long[m_keyCount];
        m_denseLeft = new TValue[m_keyCount];
        m_denseRight = new TValue[m_keyCount];
        m_fullKeys = new long[m_keyCount];
        m_termCharge = new TValue[presentation.MaximumCellTerms];
        m_termLeft = new TValue[presentation.MaximumCellTerms];
        m_termRight = new TValue[presentation.MaximumCellTerms];

        for (var key = 0; (key < m_keyCount); ++key) {
            m_denseLeft[key] = material.Zero;
            m_denseRight[key] = material.Zero;
            m_fullKeys[key] = key;
        }

        var cellStarts = presentation.CellStarts;
        var cellTargets = presentation.CellTargets;
        var cellCharges = presentation.CellCharges;
        var entryCount = ((0 == cellStarts.Length) ? 0 : ((int)cellStarts[(cellStarts.Length - 1)]));

        m_targetCharge = new TValue[entryCount];
        m_targetLeft = new int[entryCount];
        m_targetRight = new int[entryCount];
        m_targetStart = new int[(m_keyCount + 1)];

        for (var entry = 0; (entry < entryCount); ++entry) { ++m_targetStart[((int)cellTargets[entry] + 1)]; }

        for (var key = 0; (key < m_keyCount); ++key) { m_targetStart[(key + 1)] += m_targetStart[key]; }

        var cursor = new int[m_keyCount];

        for (var left = 0; (left < m_keyCount); ++left) {
            for (var right = 0; (right < m_keyCount); ++right) {
                var cell = ((left * m_keyCount) + right);
                var last = cellStarts[(cell + 1)];

                for (var entry = cellStarts[cell]; (entry < last); ++entry) {
                    var target = ((int)cellTargets[((int)entry)]);
                    var slot = (m_targetStart[target] + cursor[target]);

                    m_targetCharge[slot] = cellCharges[((int)entry)];
                    m_targetLeft[slot] = left;
                    m_targetRight[slot] = right;
                    ++cursor[target];
                }
            }
        }

        m_compiled = new CompiledProduct<TValue>(
            keyCount: m_keyCount,
            start: cellStarts.ToArray(),
            target: cellTargets.ToArray(),
            charge: cellCharges.ToArray(),
            zero: material.Zero
        );
        Identity = BuildElement(keys: presentation.IdentityKeys, coefficients: presentation.IdentityCharges);
        Zero = new Element(owner: this, keys: [], coefficients: []);
        m_generatorElements = new Element[presentation.GeneratorCount];

        var scratch = new ChargedPresentation<TValue, TOps>.KeyedCombination();
        var words = new ChargedPresentation<TValue, TOps>.Combination();

        for (var symbol = 0; (symbol < m_generatorElements.Length); ++symbol) {
            if (!presentation.TryRewriteToKeys(word: [symbol], charge: presentation.GeneratorCharge(symbol: symbol), stepLimit: NormalizationBudget, result: scratch, combination: words, stepsTaken: out _)) {
                throw new ArgumentException(message: "A generator of this presentation has no bounded normal form.", paramName: nameof(presentation));
            }

            m_generatorElements[symbol] = BuildElement(combination: scratch);
        }
    }

    /// <summary>Gets the additive identity — the empty support.</summary>
    public Element Zero { get; }
    /// <summary>Gets the multiplicative identity, the normal-form decomposition of the unit word. It is a single basis
    /// element for a monoid presentation and a sum of idempotents for a quiver.</summary>
    public Element Identity { get; }
    /// <summary>Gets the largest support a product of this algebra can return — the exact length a
    /// <see cref="MultiplyInto"/> buffer needs, derived from the presentation as the fused accumulator's width is.</summary>
    /// <remarks>It is the presentation's normal-form count, because a dense product's support is a subset of the
    /// normal-form set. It is zero when the normal-form set is not finite, where no bound exists and
    /// <see cref="MultiplyInto"/> is unavailable.</remarks>
    public int MaximumSupportCount => m_keyCount;
    /// <summary>Gets the presentation this algebra is the kernel of.</summary>
    public ChargedPresentation<TValue, TOps> Presentation { get; }

    /// <summary>Creates the presented algebra of a presentation, generating its compiled product eagerly.</summary>
    /// <param name="presentation">The presentation.</param>
    /// <returns>The described algebra.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="presentation"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentException">A generator has no bounded normal form under the presentation's rules.</exception>
    public static PresentedAlgebra<TValue, TOps> Create(ChargedPresentation<TValue, TOps> presentation) {
        ArgumentNullException.ThrowIfNull(argument: presentation);

        return new(presentation: presentation);
    }

    /// <summary>Adds two elements coefficientwise.</summary>
    /// <param name="left">The first addend.</param>
    /// <param name="right">The second addend.</param>
    /// <returns>The sum, its support canonically ordered and its zeros pruned.</returns>
    /// <exception cref="ArgumentException">An addend belongs to another algebra.</exception>
    /// <remarks>The merge walks into grow-on-demand instance scratch bounded by the two supports, so a sum materializes
    /// exactly the two arrays its result carries and nothing else. That scratch is mutable state, so one instance is
    /// still not safe for concurrent use.</remarks>
    public Element Add(in Element left, in Element right) {
        RequireOwned(value: left, paramName: nameof(left));
        RequireOwned(value: right, paramName: nameof(right));

        var material = m_material;
        var leftKeys = left.Keys;
        var leftValues = left.Coefficients;
        var rightKeys = right.Keys;
        var rightValues = right.Coefficients;
        var needed = (leftKeys.Length + rightKeys.Length);

        if (m_sumKeys.Length < needed) {
            m_sumCoefficients = new TValue[needed];
            m_sumKeys = new long[needed];
        }

        var leftIndex = 0;
        var rightIndex = 0;
        var support = 0;

        while ((leftIndex < leftKeys.Length) || (rightIndex < rightKeys.Length)) {
            var takeLeft = ((rightIndex >= rightKeys.Length) || ((leftIndex < leftKeys.Length) && (leftKeys[leftIndex] <= rightKeys[rightIndex])));
            var takeRight = ((leftIndex >= leftKeys.Length) || ((rightIndex < rightKeys.Length) && (rightKeys[rightIndex] <= leftKeys[leftIndex])));
            var key = (takeLeft ? leftKeys[leftIndex] : rightKeys[rightIndex]);
            var value = material.Zero;

            if (takeLeft) { value = leftValues[leftIndex++]; }
            if (takeRight) { value = ((takeLeft) ? material.Add(left: value, right: rightValues[rightIndex++]) : rightValues[rightIndex++]); }

            if (!material.IsZero(value: value)) {
                m_sumCoefficients[support] = value;
                m_sumKeys[support] = key;
                ++support;
            }
        }

        return new Element(
            owner: this,
            keys: m_sumKeys.AsSpan(start: 0, length: support).ToArray(),
            coefficients: m_sumCoefficients.AsSpan(start: 0, length: support).ToArray()
        );
    }

    /// <summary>Decides whether two elements are the same element.</summary>
    /// <param name="left">The first element.</param>
    /// <param name="right">The second element.</param>
    /// <returns><see langword="true"/> when the two carry the same support keys with the same coefficients; otherwise
    /// <see langword="false"/>.</returns>
    /// <exception cref="ArgumentException">An operand belongs to another algebra.</exception>
    /// <remarks>Both supports are canonically ordered with their zeros pruned, so equality is one walk down the pair and
    /// needs no normalization. Coefficients are compared by the material carrier's own default equality.</remarks>
    public bool AreEqual(in Element left, in Element right) {
        RequireOwned(value: left, paramName: nameof(left));
        RequireOwned(value: right, paramName: nameof(right));

        if (left.SupportCount != right.SupportCount) { return false; }

        var comparer = EqualityComparer<TValue>.Default;
        var leftKeys = left.Keys;
        var leftValues = left.Coefficients;
        var rightKeys = right.Keys;
        var rightValues = right.Coefficients;

        for (var index = 0; (index < leftKeys.Length); ++index) {
            if ((leftKeys[index] != rightKeys[index]) || !comparer.Equals(x: leftValues[index], y: rightValues[index])) { return false; }
        }

        return true;
    }

    /// <summary>Computes law certificates by bounded checks of the compiled product over its finite basis.</summary>
    /// <param name="overlapLimit">The maximum number of basis tuples to examine across the certificate passes;
    /// verification stops there and reports <see cref="ClosureOutcome.SearchLimitReached"/>. The parameter retains its
    /// historical name for source compatibility; it does not count or enumerate overlaps between rewrite rules.</param>
    /// <returns>The certificate.</returns>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="overlapLimit"/> is negative.</exception>
    /// <remarks>A presentation with no finite basis reports <see cref="ClosureOutcome.SearchLimitReached"/> and no
    /// flags, because none of them has been proved.</remarks>
    public PresentationCertificate<TValue> Certify(long overlapLimit) {
        ArgumentOutOfRangeException.ThrowIfNegative(value: overlapLimit);

        if (!m_isDense) {
            return new(
                outcome: ClosureOutcome.SearchLimitReached,
                isAlternative: false,
                isAssociative: false,
                isBraided: false,
                isCoherent: false,
                isCommutative: false,
                isSymmetric: false,
                hasIdentity: false,
                nonAssociativeTripleCount: 0L,
                braidingKeys: 0,
                associatorWitness: [],
                braidingCharge: [],
                braidingWitness: [],
                coherenceWitness: [],
                zeroDivisorWitness: []
            );
        }

        var associators = new List<AssociatorCharge<TValue>>();
        var basis = new Element[m_keyCount];
        var braidingCharge = new TValue[(m_keyCount * m_keyCount)];
        var braidings = new List<BraidingWitness<TValue>>();
        var budget = overlapLimit;
        var comparer = EqualityComparer<TValue>.Default;
        var divisors = new List<ZeroDivisorWitness>();
        var field = (m_material as IFieldMaterial<TValue, TOps>);
        var limitReached = false;
        var products = new Element[(m_keyCount * m_keyCount)];

        for (var key = 0; (key < m_keyCount); ++key) { basis[key] = BasisElement(key: key); }

        Array.Fill(array: braidingCharge, value: m_material.Zero);

        var hasIdentity = true;
        var isAlternative = true;
        var isAssociative = true;
        var isCommutative = true;
        var nonAssociativeTripleCount = 0L;
        var braidingComplete = true;
        var braidingMirrored = true;
        var braidingUniform = true;

        for (var key = 0; (key < m_keyCount); ++key) {
            if (!AreEqual(left: Multiply(left: Identity, right: basis[key]), right: basis[key])
                || !AreEqual(left: Multiply(left: basis[key], right: Identity), right: basis[key])) {
                hasIdentity = false;
            }
        }

        for (var left = 0; ((left < m_keyCount) && !limitReached); ++left) {
            for (var right = 0; (right < m_keyCount); ++right) {
                if (--budget < 0L) {
                    limitReached = true;

                    break;
                }

                var mirror = BasisProduct(products: products, basis: basis, left: right, right: left);
                var product = BasisProduct(products: products, basis: basis, left: left, right: right);
                var slot = ((left * m_keyCount) + right);

                if (0 == product.SupportCount) { divisors.Add(item: new(LeftKey: left, RightKey: right)); }

                if (!AreEqual(left: product, right: mirror)) { isCommutative = false; }

                // The braiding rides this walk rather than adding one: the commutation charge of an ordered pair is
                // read off the two cells the commutativity test has already fetched from the memo, so deriving it costs
                // no product and no budget unit of its own.
                if (!TryDeriveCommutation(forward: product, reverse: mirror, field: field, comparer: comparer, charge: out braidingCharge[slot])) {
                    braidingComplete = false;
                    braidingMirrored = false;

                    continue;
                }

                braidingUniform &= comparer.Equals(x: braidingCharge[slot], y: m_material.One);
                // The walk is row-major, so the mirror slot of a pair below the diagonal is already filled and symmetry
                // is decided here rather than in a second scan.
                braidingMirrored &= ((left <= right) || comparer.Equals(x: braidingCharge[slot], y: braidingCharge[((right * m_keyCount) + left)]));
            }
        }

        for (var left = 0; ((left < m_keyCount) && !limitReached); ++left) {
            for (var middle = 0; ((middle < m_keyCount) && !limitReached); ++middle) {
                var leftPair = BasisProduct(products: products, basis: basis, left: left, right: middle);

                for (var right = 0; (right < m_keyCount); ++right) {
                    if (--budget < 0L) {
                        limitReached = true;

                        break;
                    }

                    var before = Multiply(left: leftPair, right: basis[right]);
                    var after = Multiply(left: basis[left], right: BasisProduct(products: products, basis: basis, left: middle, right: right));

                    if (AreEqual(left: before, right: after)) { continue; }

                    ++nonAssociativeTripleCount;
                    isAssociative = false;

                    if ((left == middle) || (middle == right) || (left == right)) { isAlternative = false; }

                    if (m_signed is not null) {
                        associators.Add(item: new(Left: left, Middle: middle, Right: right, Charge: LeadingDifference(left: before, right: after, signed: m_signed, comparer: comparer)));
                    }
                }
            }
        }

        // Alternativity is a statement about EVERY element, not only the basis, and the associator is trilinear, so it
        // linearizes exactly: the associator alternates iff its symmetrization over each adjacent pair of basis
        // arguments vanishes. Stated as an equality it needs no subtraction, so an unsigned material is served too.
        // An associative product is alternative outright, so the pass runs only where associativity already failed.
        for (var left = 0; ((left < m_keyCount) && !limitReached && !isAssociative && isAlternative); ++left) {
            for (var middle = left; ((middle < m_keyCount) && !limitReached && isAlternative); ++middle) {
                var forward = BasisProduct(products: products, basis: basis, left: left, right: middle);
                var reverse = BasisProduct(products: products, basis: basis, left: middle, right: left);

                for (var right = 0; (right < m_keyCount); ++right) {
                    if (--budget < 0L) {
                        limitReached = true;

                        break;
                    }

                    var before = Add(left: Multiply(left: forward, right: basis[right]), right: Multiply(left: reverse, right: basis[right]));
                    var after = Add(
                        left: Multiply(left: basis[left], right: BasisProduct(products: products, basis: basis, left: middle, right: right)),
                        right: Multiply(left: basis[middle], right: BasisProduct(products: products, basis: basis, left: left, right: right))
                    );

                    if (!AreEqual(left: before, right: after)) {
                        isAlternative = false;

                        break;
                    }
                }
            }
        }

        for (var left = 0; ((left < m_keyCount) && !limitReached && !isAssociative && isAlternative); ++left) {
            for (var middle = 0; ((middle < m_keyCount) && !limitReached && isAlternative); ++middle) {
                var forward = BasisProduct(products: products, basis: basis, left: left, right: middle);

                for (var right = middle; (right < m_keyCount); ++right) {
                    if (--budget < 0L) {
                        limitReached = true;

                        break;
                    }

                    var before = Add(left: Multiply(left: forward, right: basis[right]), right: Multiply(left: BasisProduct(products: products, basis: basis, left: left, right: right), right: basis[middle]));
                    var after = Add(
                        left: Multiply(left: basis[left], right: BasisProduct(products: products, basis: basis, left: middle, right: right)),
                        right: Multiply(left: basis[left], right: BasisProduct(products: products, basis: basis, left: right, right: middle))
                    );

                    if (!AreEqual(left: before, right: after)) {
                        isAlternative = false;

                        break;
                    }
                }
            }
        }

        // Coherence is a statement about the re-association charges rather than about the product: the two routes that
        // rebalance a quadruple must charge the same. The uniform regime is the one-key degenerate case of exactly this
        // loop, because its strides are zero, so a uniform charge of one is proved coherent by the same comparison that
        // proves a declared 3-cochain coherent. The other coherence axiom — normalization at the unit — is not
        // re-tested here: it is an admission fact of ChargedPresentation, refused at construction, because comparing
        // folded charges for it is unsound on a rounding carrier where two different charges truncate alike.
        var coherences = new List<CoherenceWitness<TValue>>();
        var isCoherent = true;
        var span = (Presentation.HasLiveReassociation ? m_keyCount : 1);

        for (var first = 0; ((first < span) && !limitReached); ++first) {
            for (var second = 0; ((second < span) && !limitReached); ++second) {
                for (var third = 0; ((third < span) && !limitReached); ++third) {
                    for (var fourth = 0; (fourth < span); ++fourth) {
                        if (--budget < 0L) {
                            limitReached = true;

                            break;
                        }

                        var nested = m_material.Multiply(
                            left: m_material.Multiply(
                                left: Presentation.SpliceCharge(left: first, middle: second, right: third),
                                right: Presentation.SpliceCharge(left: first, middle: Presentation.SpliceFold(key: second, letter: third), right: fourth)
                            ),
                            right: Presentation.SpliceCharge(left: second, middle: third, right: fourth)
                        );
                        var flat = m_material.Multiply(
                            left: Presentation.SpliceCharge(left: first, middle: second, right: Presentation.SpliceFold(key: third, letter: fourth)),
                            right: Presentation.SpliceCharge(left: Presentation.SpliceFold(key: first, letter: second), middle: third, right: fourth)
                        );

                        if (comparer.Equals(x: nested, y: flat)) { continue; }

                        coherences.Add(item: new(First: first, Second: second, Third: third, Fourth: fourth, Nested: nested, Flat: flat));
                        isCoherent = false;
                    }
                }
            }
        }

        // The braiding's two hexagon identities, over the derived charges rather than over declared ones. The uniform
        // regime is the one-key degenerate case of exactly this loop: where every derived charge is the material's one
        // both identities read one equals one times one at every triple, so no witness can exist and the span collapses
        // to a single budget unit. That collapse is PROVED by the charges the walk above measured, never assumed from
        // the presentation's shape. Where it does NOT collapse the pass is keys-cubed and spends the same overlapLimit
        // the passes above it spend, so it can truncate a call that a pre-braiding budget sized comfortably: at
        // Clifford(4,1,0) the first budget that certifies moved from 33793 to 66561. Consumption ORDER is unchanged,
        // and every budget above the new requirement returns what it always did, but the certificate a budget in
        // between returns is a different certificate rather than the same one.
        if (!limitReached && !TryProveHexagons(products: products, basis: basis, charge: braidingCharge, witnesses: braidings, comparer: comparer, span: (braidingUniform ? 1 : m_keyCount), budget: ref budget)) {
            limitReached = true;
        }

        var isBraided = ((braidingComplete && (0 == braidings.Count)) && !limitReached);
        var outcome = (limitReached
            ? ClosureOutcome.SearchLimitReached
            : ((0L != nonAssociativeTripleCount)
                ? ClosureOutcome.BasisNonAssociativityDetected
                : ClosureOutcome.BasisAssociativityVerified));

        return new(
            outcome: outcome,
            isAlternative: (isAlternative && !limitReached),
            isAssociative: (isAssociative && !limitReached),
            isBraided: isBraided,
            isCoherent: (isCoherent && !limitReached),
            isCommutative: (isCommutative && !limitReached),
            isSymmetric: (isBraided && braidingMirrored),
            hasIdentity: hasIdentity,
            nonAssociativeTripleCount: nonAssociativeTripleCount,
            braidingKeys: m_keyCount,
            associatorWitness: [.. associators],
            braidingCharge: braidingCharge,
            braidingWitness: [.. braidings],
            coherenceWitness: [.. coherences],
            zeroDivisorWitness: [.. divisors]
        );
    }

    /// <summary>Returns the generated dense product table.</summary>
    /// <returns>The compiled product; a table with no cells when the normal-form set is not finite.</returns>
    /// <remarks>Eager and immutable: the table was generated once, at construction, by the interpreted normalizer, so
    /// repeated calls return the same value and no build can race.</remarks>
    public CompiledProduct<TValue> Compile() =>
        m_compiled;

    /// <summary>Builds an element from a support, canonicalizing it.</summary>
    /// <param name="keys">The normal-form keys, in any order and with repeats allowed.</param>
    /// <param name="coefficients">The coefficients, one per key.</param>
    /// <returns>The element, its support sorted, its repeats combined through the material's addition, and its zeros
    /// pruned.</returns>
    /// <exception cref="ArgumentException">The two spans have different lengths.</exception>
    /// <exception cref="ArgumentOutOfRangeException">A key names no normal form of a finite presentation.</exception>
    /// <remarks>The canonicalization runs in one instance scratch combination cleared at entry, so the element's own two
    /// arrays are the whole allocation. That scratch is mutable state, so one instance is still not safe for concurrent
    /// use.</remarks>
    public Element FromSupport(ReadOnlySpan<long> keys, ReadOnlySpan<TValue> coefficients) {
        if (keys.Length != coefficients.Length) {
            throw new ArgumentException(message: "An element carries one coefficient per key.", paramName: nameof(coefficients));
        }

        var combination = m_supportScratch;

        combination.Clear();

        for (var index = 0; (index < keys.Length); ++index) {
            if (m_isDense && ((keys[index] < 0L) || (keys[index] >= m_keyCount))) {
                throw new ArgumentOutOfRangeException(paramName: nameof(keys), message: "The key names no normal form of this presentation.");
            }

            combination.Merge(
                key: keys[index],
                charge: m_material.Canonicalize(value: coefficients[index]),
                material: m_material
            );
        }

        return BuildElement(combination: combination);
    }

    /// <summary>Returns the basis element of one generator, carrying that generator's presentation charge.</summary>
    /// <param name="symbol">The generator's symbol.</param>
    /// <returns>The element. A presentation that gives a generator a weight — a quiver arrow's — returns the weighted
    /// basis element, which is what makes the weight load-bearing rather than decorative.</returns>
    /// <exception cref="ArgumentOutOfRangeException">The symbol names no generator.</exception>
    public Element Generator(int symbol) {
        ArgumentOutOfRangeException.ThrowIfNegative(value: symbol);
        ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(value: symbol, other: m_generatorElements.Length);

        return m_generatorElements[symbol];
    }

    /// <summary>Multiplies two elements: graft every support pair, resolve each graft under the charged rules, then
    /// round exactly once per distinct result key through the material's fused sum.</summary>
    /// <param name="left">The multiplicand.</param>
    /// <param name="right">The multiplier.</param>
    /// <returns>The product.</returns>
    /// <exception cref="ArgumentException">An operand belongs to another algebra.</exception>
    /// <exception cref="InvalidOperationException">The presentation has no finite basis and a grafted pair exceeded the
    /// normalization budget or the key scheme.</exception>
    public Element Multiply(in Element left, in Element right) {
        RequireOwned(value: left, paramName: nameof(left));
        RequireOwned(value: right, paramName: nameof(right));

        return (m_isDense
            ? MultiplyDense(left: left, right: right)
            : MultiplySparse(left: left, right: right));
    }

    /// <summary>Multiplies two elements into caller-provided buffers, allocating nothing.</summary>
    /// <param name="left">The multiplicand.</param>
    /// <param name="right">The multiplier.</param>
    /// <param name="keys">Receives the result's normal-form keys, ascending; at least
    /// <see cref="MaximumSupportCount"/> long.</param>
    /// <param name="coefficients">Receives the result's coefficients, in the same order; at least
    /// <see cref="MaximumSupportCount"/> long.</param>
    /// <returns>The number of support entries written.</returns>
    /// <exception cref="ArgumentException">A buffer is shorter than <see cref="MaximumSupportCount"/>, or an operand
    /// belongs to another algebra.</exception>
    /// <exception cref="InvalidOperationException">The presentation has no finite basis, so no support bound exists.</exception>
    /// <remarks>The identical loop <see cref="Multiply"/> runs, writing where the caller says instead of into a fresh
    /// array: the keys, the coefficients and the rounding chain are bit-identical to
    /// <see cref="Multiply"/>'s at every operand. It reads the same construction-time scatter buffers, so one instance
    /// is still not safe for concurrent use.</remarks>
    public int MultiplyInto(in Element left, in Element right, Span<long> keys, Span<TValue> coefficients) {
        if (!m_isDense) {
            throw new InvalidOperationException(message: "This presentation has no finite basis, so a product has no support bound to write into.");
        }

        if (keys.Length < m_keyCount) {
            throw new ArgumentException(message: "A product buffer is at least MaximumSupportCount long.", paramName: nameof(keys));
        }

        if (coefficients.Length < m_keyCount) {
            throw new ArgumentException(message: "A product buffer is at least MaximumSupportCount long.", paramName: nameof(coefficients));
        }

        RequireOwned(value: left, paramName: nameof(left));
        RequireOwned(value: right, paramName: nameof(right));

        return MultiplyCore(left: left, right: right, keys: keys, coefficients: coefficients);
    }

    /// <summary>Negates an element coefficientwise.</summary>
    /// <param name="value">The element to negate.</param>
    /// <returns>The additive inverse, its support unchanged.</returns>
    /// <exception cref="ArgumentException">The element belongs to another algebra.</exception>
    /// <exception cref="InvalidOperationException">The material carries no additive inverses.</exception>
    /// <remarks>Negation is exact wherever the material's own is, which over the house scalar it is: a raw negation
    /// rounds nothing. The support is unchanged because a material with additive inverses has no nonzero value whose
    /// negation is zero.</remarks>
    public Element Negate(in Element value) {
        RequireOwned(value: value, paramName: nameof(value));

        var signed = RequireSignedMaterial();
        var coefficients = new TValue[value.SupportCount];

        for (var index = 0; (index < coefficients.Length); ++index) { coefficients[index] = signed.Negate(value: value.Coefficients[index]); }

        return FromSupport(keys: value.Keys, coefficients: coefficients);
    }

    /// <summary>Raises an element to a power by ascending-bit square-and-multiply.</summary>
    /// <param name="value">The base.</param>
    /// <param name="exponent">The exponent; zero yields <see cref="Identity"/>.</param>
    /// <returns>The power.</returns>
    /// <exception cref="ArgumentException">The element belongs to another algebra.</exception>
    /// <remarks>The schedule is part of the contract: it is the same ascending-bit schedule
    /// <see cref="QuadraticAlgebra{TScalar}.CompanionPower"/> runs, so at the companion presentation over the house
    /// scalar the two are bit-identical, rounding chain included.</remarks>
    public Element Power(in Element value, ulong exponent) {
        RequireOwned(value: value, paramName: nameof(value));

        var power = value;
        var result = Identity;

        while (0UL != exponent) {
            if (0UL != (exponent & 1UL)) { result = Multiply(left: result, right: power); }

            exponent >>>= 1;

            if (0UL != exponent) { power = Multiply(left: power, right: power); }
        }

        return result;
    }

    /// <summary>Raises an element to a power by left-to-right repeated multiplication.</summary>
    /// <param name="value">The base.</param>
    /// <param name="exponent">The exponent; zero yields <see cref="Identity"/>.</param>
    /// <returns>The power.</returns>
    /// <exception cref="ArgumentException">The element belongs to another algebra.</exception>
    /// <remarks>Equal to <see cref="Power"/> on every <see cref="IExactSemiringMaterial{TValue, TOps}"/>, where the
    /// product associates. Over a scheduled rounding material the two schedules can round a different number of times
    /// — roughly <c>2·log₂ n</c> against <c>n</c> per coefficient — so they are permitted to differ, and each is pinned
    /// as its own statement.</remarks>
    public Element PowerSequential(in Element value, ulong exponent) {
        RequireOwned(value: value, paramName: nameof(value));

        var result = Identity;

        for (var step = 0UL; (step < exponent); ++step) { result = Multiply(left: result, right: value); }

        return result;
    }

    /// <summary>Subtracts one element from another coefficientwise.</summary>
    /// <param name="left">The minuend.</param>
    /// <param name="right">The subtrahend.</param>
    /// <returns>The difference, its support canonically ordered and its zeros pruned.</returns>
    /// <exception cref="ArgumentException">An operand belongs to another algebra.</exception>
    /// <exception cref="InvalidOperationException">The material carries no additive inverses.</exception>
    /// <remarks>Exactly <see cref="Add"/> of the minuend and <see cref="Negate"/> of the subtrahend, which is the
    /// composition every consumer of this algebra wrote by hand before it existed.</remarks>
    public Element Subtract(in Element left, in Element right) {
        RequireOwned(value: left, paramName: nameof(left));
        RequireOwned(value: right, paramName: nameof(right));

        return Add(left: left, right: Negate(value: right));
    }

    /// <summary>Returns the exact finite sum <c>1 + a + … + a^bound</c>.</summary>
    /// <param name="value">The element to sum the powers of.</param>
    /// <param name="bound">The highest power to include.</param>
    /// <returns>The truncated sum. Always available: it is the honest partial when no closure certificate exists.</returns>
    /// <exception cref="ArgumentException">The element belongs to another algebra.</exception>
    /// <exception cref="ArgumentOutOfRangeException"><paramref name="bound"/> is negative.</exception>
    public Element TruncatedSum(in Element value, int bound) {
        RequireOwned(value: value, paramName: nameof(value));
        ArgumentOutOfRangeException.ThrowIfNegative(value: bound);

        var power = Identity;
        var total = Identity;

        for (var step = 0; (step < bound); ++step) {
            power = Multiply(left: power, right: value);
            total = Add(left: total, right: power);
        }

        return total;
    }

    /// <summary>Normalizes a magma term — an n-ary tree over generator symbols — to the presentation's normal form, bounded.</summary>
    /// <param name="term">The term to normalize.</param>
    /// <param name="stepLimit">The maximum number of rewrite steps.</param>
    /// <param name="normalForm">On success, the charged combination of normal forms.</param>
    /// <param name="obstruction">On failure, the step count reached and the term that blocked.</param>
    /// <returns><see langword="true"/> on success; otherwise <see langword="false"/>.</returns>
    /// <remarks>
    /// <para>
    /// This runs the interpreted normalizer directly, and <see cref="Compile"/>'s generated cells are proved equal to
    /// it. The two routes share the rewriter — the compiled cells are what it produced at construction — so that
    /// agreement pins the flatten, rebalance, indexing and dense-fold path around it rather than the rewriting itself.
    /// It is deliberately the slow path.
    /// </para>
    /// <para>
    /// <b>The bracketing is paid for, not discarded.</b> The rewriter reduces a flat word, which is the left-normed
    /// bracketing, so every other bracketing is first rebalanced to it and the presentation's re-association charge is
    /// multiplied in once per bracket spliced away. Under a uniform charge of one that is silent and a tree's brackets
    /// are inert; under a declared associator 3-cochain it is the whole content of the tree regime, and the charge a
    /// term picks up depends only on the term, never on the order the brackets were spliced in — which is what the
    /// certificate's <see cref="PresentationCertificate{TValue}.IsCoherent"/> proves.
    /// </para>
    /// </remarks>
    public bool TryNormalize(in Term term, long stepLimit, out Element normalForm, out NormalizationObstruction obstruction) {
        var presentation = Presentation;
        var word = new int[term.Degree];
        var length = 0;

        normalForm = Zero;
        obstruction = default;

        if (!TryFlatten(term: term, word: word, length: ref length, generatorCount: presentation.GeneratorCount)) {
            obstruction = new(StepsTaken: 0L, BlockedKey: -1L);

            return false;
        }

        var charge = presentation.Material.One;

        _ = Rebalance(term: term, word: word, offset: 0, charge: ref charge, key: out _);

        var result = new ChargedPresentation<TValue, TOps>.KeyedCombination();

        if (!presentation.TryRewriteToKeys(word: word, charge: charge, stepLimit: stepLimit, result: result, combination: new(), stepsTaken: out var stepsTaken)) {
            obstruction = new(
                StepsTaken: stepsTaken,
                BlockedKey: (presentation.TryPackWord(word: word, key: out var blocked) ? blocked : -1L)
            );

            return false;
        }

        normalForm = BuildElement(combination: result);

        return true;
    }

    /// <summary>Sums an element over all lengths — <c>1 + a + a² + …</c> — when a guardedness certificate can be issued.</summary>
    /// <param name="value">The element to sum the powers of.</param>
    /// <param name="total">On success, the total.</param>
    /// <param name="obstruction">On failure, the certificate attempted and where the attempt stopped.</param>
    /// <returns><see langword="true"/> when a certificate was issued; otherwise <see langword="false"/>.</returns>
    /// <remarks>
    /// Two certificates are computed here, never assumed, and both require
    /// <see cref="IExactSemiringMaterial{TValue, TOps}"/>: without associativity, distributivity, and zero
    /// annihilation, a vanished power or one stabilized partial sum does not prove the unseen tail. A scheduled
    /// rounding material is therefore refused with <see cref="ClosureCertificate.None"/> and
    /// <see cref="TruncatedSum"/> remains its honest finite answer. On an exact semiring,
    /// <see cref="ClosureCertificate.Nilpotent"/> is issued when a power becomes zero, and
    /// <see cref="ClosureCertificate.Idempotent"/> when the partial sums stabilize and the material additionally
    /// declares idempotent addition.
    /// </remarks>
    public bool TrySumOverAllLengths(in Element value, out Element total, out SumClosureObstruction obstruction) {
        RequireOwned(value: value, paramName: nameof(value));

        if (!m_exactSemiringLicensed) {
            obstruction = new(
                Attempted: ClosureCertificate.None,
                SupportKey: ((0 == value.SupportCount) ? 0L : value.Keys[0]),
                StepsTaken: 0L
            );
            total = Zero;

            return false;
        }

        var attempted = (m_idempotentLicensed
            ? ClosureCertificate.Idempotent
            : ClosureCertificate.Nilpotent);
        var comparer = EqualityComparer<TValue>.Default;
        var limit = (m_isDense ? (m_keyCount + 1) : 0);
        var power = Identity;

        total = Identity;

        for (var step = 1; (step <= limit); ++step) {
            power = Multiply(left: power, right: value);

            if (0 == power.SupportCount) {
                obstruction = default;

                return true;
            }

            var next = Add(left: total, right: power);

            if (m_idempotentLicensed && AreEqual(left: next, right: total)) {
                total = next;
                obstruction = default;

                return true;
            }

            total = next;
        }

        obstruction = new(
            Attempted: attempted,
            SupportKey: ((0 == power.SupportCount) ? 0L : power.Keys[0]),
            StepsTaken: limit
        );
        total = Zero;

        return false;
    }

    // The normalization budget the construction-time and sparse paths run under. Cold paths only; TryNormalize takes
    // the caller's limit instead, because a bounded attempt is the whole point of the public surface.
    private const long NormalizationBudget = (1L << 20);

    // The coefficient of the lowest key at which two elements differ — the associator's leading charge.
    private static TValue LeadingDifference(in Element left, in Element right, ISignedMaterial<TValue, TOps> signed, EqualityComparer<TValue> comparer) {
        var leftIndex = 0;
        var rightIndex = 0;

        while ((leftIndex < left.SupportCount) || (rightIndex < right.SupportCount)) {
            var hasLeft = (leftIndex < left.SupportCount);
            var hasRight = (rightIndex < right.SupportCount);

            if (hasLeft && (!hasRight || (left.Keys[leftIndex] < right.Keys[rightIndex]))) {
                return left.Coefficients[leftIndex];
            }

            if (hasRight && (!hasLeft || (right.Keys[rightIndex] < left.Keys[leftIndex]))) {
                return signed.Negate(value: right.Coefficients[rightIndex]);
            }

            if (!comparer.Equals(x: left.Coefficients[leftIndex], y: right.Coefficients[rightIndex])) {
                return signed.Subtract(left: left.Coefficients[leftIndex], right: right.Coefficients[rightIndex]);
            }

            ++leftIndex;
            ++rightIndex;
        }

        return signed.Zero;
    }

    // The charge a bracketing costs, and the key its word reaches. A node is evaluated left to right, so bringing it to
    // the flat left-normed word the rewriter reduces splices away the brackets of every factor after the first: peeling
    // one letter off a factor's tail is one x·(y·z) → (x·y)·z move, whose charge is the presentation's re-association
    // datum at the three keys it joins. The walk is the same walk under a uniform charge, where the strides are zero and
    // the keys fall out of the lookup, so no path here discriminates by instance. Returns the leaves consumed, which is
    // how a subtree finds its own slice of the already-flattened word.
    private int Rebalance(in Term term, ReadOnlySpan<int> word, int offset, ref TValue charge, out long key) {
        var children = term.Children;
        var material = m_material;
        var presentation = Presentation;
        var consumed = 1;
        var index = 0;

        if (Term.Product == term.Symbol) {
            if (0 == children.Length) {
                key = presentation.SpliceUnitKey;

                return 0;
            }

            consumed = Rebalance(term: children[0], word: word, offset: offset, charge: ref charge, key: out key);
            index = 1;
        } else {
            key = term.Symbol;
        }

        for (; (index < children.Length); ++index) {
            var start = (offset + consumed);
            var length = Rebalance(term: children[index], word: word, offset: start, charge: ref charge, key: out _);
            var prefix = ((0 == length) ? 0L : word[start]);

            for (var step = 1; (step < length); ++step) {
                var letter = word[(start + step)];

                charge = material.Multiply(left: charge, right: presentation.SpliceCharge(left: key, middle: prefix, right: letter));
                prefix = presentation.SpliceFold(key: prefix, letter: letter);
            }

            for (var step = 0; (step < length); ++step) { key = presentation.SpliceFold(key: key, letter: word[(start + step)]); }

            consumed += length;
        }

        return consumed;
    }
    private static bool TryFlatten(in Term term, Span<int> word, ref int length, int generatorCount) {
        if (Term.Product != term.Symbol) {
            if ((term.Symbol < 0) || (term.Symbol >= generatorCount) || (length >= word.Length)) { return false; }

            word[length++] = term.Symbol;
        }

        foreach (var child in term.Children) {
            if (!TryFlatten(term: child, word: word, length: ref length, generatorCount: generatorCount)) { return false; }
        }

        return true;
    }

    // Membership, which nothing else can recover: a key is an index into THIS algebra's normal forms and tables, so an
    // element built elsewhere either reads the wrong cell or reads outside the table. One reference compare, on the
    // paths a foreign element can enter through; the default element carries no owner and no support, so it is the
    // zero of every algebra and is admitted.
    internal void RequireOwned(in Element value, string paramName) {
        if ((value.Owner is not null) && !ReferenceEquals(objA: value.Owner, objB: this)) {
            throw new ArgumentException(message: "This element belongs to another presented algebra, whose keys name different normal forms.", paramName: paramName);
        }
    }

    private ISignedMaterial<TValue, TOps> RequireSignedMaterial() {
        if (m_signed is null) {
            throw new InvalidOperationException(message: "Negation takes additive inverses, which a material that is not signed cannot do.");
        }

        return m_signed;
    }
    private Element BasisElement(long key) =>
        new(owner: this, keys: [key], coefficients: [m_material.One]);

    // One product of two basis elements, computed on first read and read back after. Every certificate loop re-derives
    // the same ordered key pairs — the commutativity walk covers each twice, the associativity and both alternativity
    // walks once per third key — so a certificate that multiplied them where it stood paid for one product up to keys
    // times over. A cell is filled on first read rather than up front, so a budget that cuts the enumeration short
    // pays for no product it never looked at. The price is keys-squared retained elements for the duration of the
    // call, which a cold diagnostic can afford; nothing on the running product's path allocates any of it.
    private Element BasisProduct(Element[] products, Element[] basis, int left, int right) {
        ref var cell = ref products[((left * m_keyCount) + right)];

        // A product carries the algebra that built it, so the owner-less default element IS the unfilled cell.
        if (cell.Owner is null) { cell = Multiply(left: basis[left], right: basis[right]); }

        return cell;
    }
    private Element BuildElement(ChargedPresentation<TValue, TOps>.KeyedCombination combination) {
        var coefficients = new TValue[combination.Count];
        var keys = new long[combination.Count];

        for (var index = 0; (index < combination.Count); ++index) {
            coefficients[index] = m_material.Canonicalize(value: combination.ChargeAt(index: index));
            keys[index] = combination.KeyAt(index: index);
        }

        return new Element(owner: this, keys: keys, coefficients: coefficients);
    }
    private Element BuildElement(ReadOnlySpan<long> keys, ReadOnlySpan<TValue> coefficients) {
        var canonical = new TValue[coefficients.Length];

        for (var index = 0; (index < canonical.Length); ++index) {
            canonical[index] = m_material.Canonicalize(value: coefficients[index]);
        }

        return new(owner: this, keys: keys.ToArray(), coefficients: canonical);
    }

    // The dense product's loop, writing wherever the caller points. Multiply hands it the algebra's own compaction
    // scratch and copies out; MultiplyInto hands it the caller's spans and copies nothing. Every other buffer it reads
    // was allocated at construction, so the loop itself allocates nothing at all.
    private int MultiplyCore(in Element left, in Element right, Span<long> keys, Span<TValue> coefficients) {
        var material = m_material;
        var leftKeys = left.Keys;
        var leftValues = left.Coefficients;
        var rightKeys = right.Keys;
        var rightValues = right.Coefficients;

        for (var index = 0; (index < leftKeys.Length); ++index) { m_denseLeft[((int)leftKeys[index])] = leftValues[index]; }
        for (var index = 0; (index < rightKeys.Length); ++index) { m_denseRight[((int)rightKeys[index])] = rightValues[index]; }

        var support = 0;

        for (var target = 0; (target < m_keyCount); ++target) {
            var last = m_targetStart[(target + 1)];
            var terms = 0;

            for (var entry = m_targetStart[target]; (entry < last); ++entry) {
                var leftValue = m_denseLeft[m_targetLeft[entry]];

                if (material.IsZero(value: leftValue)) { continue; }

                var rightValue = m_denseRight[m_targetRight[entry]];

                if (material.IsZero(value: rightValue)) { continue; }

                m_termCharge[terms] = m_targetCharge[entry];
                m_termLeft[terms] = leftValue;
                m_termRight[terms] = rightValue;
                ++terms;
            }

            if (0 == terms) { continue; }

            var value = material.FusedChargedSum(
                charges: m_termCharge.AsSpan(start: 0, length: terms),
                left: m_termLeft.AsSpan(start: 0, length: terms),
                right: m_termRight.AsSpan(start: 0, length: terms),
                lane: m_lane
            );

            if (material.IsZero(value: value)) { continue; }

            coefficients[support] = value;
            keys[support] = target;
            ++support;
        }

        for (var index = 0; (index < leftKeys.Length); ++index) { m_denseLeft[((int)leftKeys[index])] = material.Zero; }
        for (var index = 0; (index < rightKeys.Length); ++index) { m_denseRight[((int)rightKeys[index])] = material.Zero; }

        return support;
    }

    // The dense product: scatter both operands over the normal-form range, then walk the transposed cell table once per
    // result key, gathering that key's terms and folding them through exactly one fused sum. Every buffer here was
    // allocated at construction, so the only allocation is the result support.
    private Element MultiplyDense(in Element left, in Element right) {
        var support = MultiplyCore(left: left, right: right, keys: m_compactKeys, coefficients: m_compactCoefficients);

        // The support's keys are the algebra's own ascending key array whenever the result is full, which it is for
        // every dense product of dense operands, so a product allocates exactly one array.
        return new Element(
            owner: this,
            keys: ((support == m_keyCount) ? m_fullKeys : m_compactKeys.AsSpan(start: 0, length: support).ToArray()),
            coefficients: m_compactCoefficients.AsSpan(start: 0, length: support).ToArray()
        );
    }

    // The product at a presentation with no finite basis: graft and normalize per support pair, group the terms by
    // result key, and fold each group through one fused sum. Unlike the dense path this allocates; a presentation
    // without a finite basis has no bounded working set to pre-size.
    private Element MultiplySparse(in Element left, in Element right) {
        var presentation = Presentation;
        var material = m_material;
        var charges = new List<TValue>();
        var combination = new ChargedPresentation<TValue, TOps>.KeyedCombination();
        var leftValues = new List<TValue>();
        var rightValues = new List<TValue>();
        var targets = new List<long>();
        var word = new int[512];
        var words = new ChargedPresentation<TValue, TOps>.Combination();

        for (var leftIndex = 0; (leftIndex < left.SupportCount); ++leftIndex) {
            if (!presentation.TryUnpackWord(key: left.Keys[leftIndex], word: word, length: out var leftLength)) {
                throw new InvalidOperationException(message: "A support key of this element does not name a word of the presentation.");
            }

            for (var rightIndex = 0; (rightIndex < right.SupportCount); ++rightIndex) {
                if (!presentation.TryUnpackWord(key: right.Keys[rightIndex], word: word.AsSpan(start: leftLength), length: out var rightLength)) {
                    throw new InvalidOperationException(message: "A support key of this element does not name a word of the presentation.");
                }

                if (!presentation.TryRewriteToKeys(word: word.AsSpan(start: 0, length: (leftLength + rightLength)), charge: material.One, stepLimit: NormalizationBudget, result: combination, combination: words, stepsTaken: out _)) {
                    throw new InvalidOperationException(message: "A grafted pair exceeded the normalization budget of this presentation.");
                }

                for (var index = 0; (index < combination.Count); ++index) {
                    charges.Add(item: combination.ChargeAt(index: index));
                    leftValues.Add(item: left.Coefficients[leftIndex]);
                    rightValues.Add(item: right.Coefficients[rightIndex]);
                    targets.Add(item: combination.KeyAt(index: index));
                }
            }
        }

        return FoldByTarget(targets: targets, charges: charges, left: leftValues, right: rightValues);
    }

    // The grouped bilinear fold, single-homed: order the staged contributions by target key and then by insertion,
    // gather each target's group, and fold it through exactly ONE FusedChargedSum. That is the
    // one-rounding-per-returned-coefficient discipline stated as a call rather than as prose, and every producer of a
    // charged span — the sparse product and the outer product — routes through it.
    internal Element FoldByTarget(List<long> targets, List<TValue> charges, List<TValue> left, List<TValue> right) {
        var material = m_material;
        var order = OrderByTarget(targets: targets);
        var groupCharge = new List<TValue>();
        var groupLeft = new List<TValue>();
        var groupRight = new List<TValue>();
        var resultCoefficients = new List<TValue>();
        var resultKeys = new List<long>();
        var cursor = 0;

        while (cursor < order.Length) {
            var key = order[cursor].Target;

            groupCharge.Clear();
            groupLeft.Clear();
            groupRight.Clear();

            while ((cursor < order.Length) && (order[cursor].Target == key)) {
                var entry = order[cursor++].Index;

                groupCharge.Add(item: charges[entry]);
                groupLeft.Add(item: left[entry]);
                groupRight.Add(item: right[entry]);
            }

            var value = material.FusedChargedSum(
                charges: System.Runtime.InteropServices.CollectionsMarshal.AsSpan(list: groupCharge),
                left: System.Runtime.InteropServices.CollectionsMarshal.AsSpan(list: groupLeft),
                right: System.Runtime.InteropServices.CollectionsMarshal.AsSpan(list: groupRight),
                lane: m_lane
            );

            if (material.IsZero(value: value)) { continue; }

            resultCoefficients.Add(item: value);
            resultKeys.Add(item: key);
        }

        return new Element(owner: this, keys: [.. resultKeys], coefficients: [.. resultCoefficients]);
    }

    // The same fold at a constant operand — the documented partial evaluation the material pins bit for bit. The
    // residual is the one producer that has values rather than operand pairs, so it keeps this overload rather than
    // filling a span with ones, which would rest the identity on a law instead of on construction.
    internal Element FoldByTarget(List<long> targets, List<TValue> charges, List<TValue> values) {
        var material = m_material;
        var order = OrderByTarget(targets: targets);
        var groupCharge = new List<TValue>();
        var groupValue = new List<TValue>();
        var resultCoefficients = new List<TValue>();
        var resultKeys = new List<long>();
        var cursor = 0;

        while (cursor < order.Length) {
            var key = order[cursor].Target;

            groupCharge.Clear();
            groupValue.Clear();

            while ((cursor < order.Length) && (order[cursor].Target == key)) {
                var entry = order[cursor++].Index;

                groupCharge.Add(item: charges[entry]);
                groupValue.Add(item: values[entry]);
            }

            var value = material.FusedChargedLinear(
                charges: System.Runtime.InteropServices.CollectionsMarshal.AsSpan(list: groupCharge),
                values: System.Runtime.InteropServices.CollectionsMarshal.AsSpan(list: groupValue),
                lane: m_lane
            );

            if (material.IsZero(value: value)) { continue; }

            resultCoefficients.Add(item: value);
            resultKeys.Add(item: key);
        }

        return new Element(owner: this, keys: [.. resultKeys], coefficients: [.. resultCoefficients]);
    }

    // The grouping order, ascending by target key and then by insertion. The default tuple comparer orders
    // lexicographically, which IS that comparison, so it is a total order and never a hash order.
    private static (long Target, int Index)[] OrderByTarget(List<long> targets) {
        var order = new (long Target, int Index)[targets.Count];

        for (var index = 0; (index < order.Length); ++index) { order[index] = (targets[index], index); }

        Array.Sort(array: order);

        return order;
    }

    // Whether one element IS another scaled by a charge, decided coefficientwise without forming the scaled element. A
    // support carries no zeros, so a charge that annihilates an entry has to annihilate the whole of it, which is what
    // the walk's two ends together say. Two EMPTY supports satisfy this for every charge, so it decides nothing there;
    // the caller refuses that pair before proposing a candidate to it rather than reading the first success as an
    // answer.
    private bool ScalesTo(in Element scaled, TValue charge, in Element value, EqualityComparer<TValue> comparer) {
        var material = m_material;
        var index = 0;

        for (var entry = 0; (entry < value.SupportCount); ++entry) {
            var coefficient = material.Multiply(left: charge, right: value.Coefficients[entry]);

            if (material.IsZero(value: coefficient)) { continue; }

            if ((index >= scaled.SupportCount) || (scaled.Keys[index] != value.Keys[entry]) || !comparer.Equals(x: scaled.Coefficients[index], y: coefficient)) { return false; }

            ++index;
        }

        return (index == scaled.SupportCount);
    }

    // The commutation charge of one ordered basis pair, DERIVED from the two cells the certificate already read rather
    // than declared beside them: the coefficient c with a·b = c·(b·a). The candidates are the material's one, its
    // negation, and — at a field material — the coefficient the two cells' own leading charges name, which is
    // PresentedGroup.TryCertify's shipped rule exactly. Deriving only PROPOSES; the scaled comparison decides, so a
    // charge is issued only where the two products were found to differ by it.
    //
    // A pair that ANNIHILATES BOTH WAYS is refused before the search runs, because it constrains no coefficient: every
    // charge relates those two zeros, so the first candidate the search reaches is the walk's arbitrary choice and not
    // the product's own answer. Issuing it is worse than issuing nothing, since the hexagon identities then read a
    // charge no cell states: at a degenerate signature the value so pinned contradicts the graded sign the same
    // signature's NONvanishing pairs carry, and the certificate manufactures witnesses out of an absence.
    //
    // Where none of the three candidates works no charge is issued either: the material cannot name the coefficient
    // the pair would need. Both are shrunk guarantees rather than guesses. The zero written on either path is
    // unambiguous, because no candidate can BE zero — one and its negation are not the zero of any material, and a
    // quotient of two nonzero field coefficients is a unit.
    private bool TryDeriveCommutation(in Element forward, in Element reverse, IFieldMaterial<TValue, TOps>? field, EqualityComparer<TValue> comparer, out TValue charge) {
        charge = m_material.Zero;

        if ((0 == forward.SupportCount) && (0 == reverse.SupportCount)) { return false; }

        charge = m_material.One;

        if (ScalesTo(scaled: forward, charge: charge, value: reverse, comparer: comparer)) { return true; }

        if (m_signed is not null) {
            charge = m_signed.Negate(value: m_material.One);

            if (ScalesTo(scaled: forward, charge: charge, value: reverse, comparer: comparer)) { return true; }
        }

        if ((field is not null)
            && (0 != forward.SupportCount)
            && (0 != reverse.SupportCount)
            && field.TryInvert(value: reverse.Coefficients[0], inverse: out var inverse)) {
            charge = m_material.Multiply(left: forward.Coefficients[0], right: inverse);

            if (ScalesTo(scaled: forward, charge: charge, value: reverse, comparer: comparer)) { return true; }
        }

        charge = m_material.Zero;

        return false;
    }

    // The braiding's two hexagon identities, measured over the ordered basis triples: the commutation charge a folded
    // pair carries must be the product of the charges its two factors carry, in the first argument and in the second.
    // Both are indexed by the same triple, so one witness shape serves both. A triple whose folded product is not a
    // single basis element names no object for the identity to speak about, and one whose three charges were not all
    // derived has nothing to compare, so each is passed over rather than counted against the braiding. Returns whether
    // the whole span was examined; a false is the budget running out, which is distinct from finding a failure.
    private bool TryProveHexagons(
        Element[] products,
        Element[] basis,
        TValue[] charge,
        List<BraidingWitness<TValue>> witnesses,
        EqualityComparer<TValue> comparer,
        int span,
        ref long budget
    ) {
        for (var left = 0; (left < span); ++left) {
            for (var middle = 0; (middle < span); ++middle) {
                var leading = BasisProduct(products: products, basis: basis, left: left, right: middle);

                for (var right = 0; (right < span); ++right) {
                    if (--budget < 0L) { return false; }

                    var trailing = BasisProduct(products: products, basis: basis, left: middle, right: right);

                    if ((1 == leading.SupportCount)
                        && TryReadCommutation(charge: charge, left: ((int)leading.Keys[0]), right: right, value: out var folded)
                        && TryReadCommutation(charge: charge, left: left, right: right, value: out var head)
                        && TryReadCommutation(charge: charge, left: middle, right: right, value: out var tail)) {
                        var flat = m_material.Multiply(left: head, right: tail);

                        if (!comparer.Equals(x: folded, y: flat)) {
                            witnesses.Add(item: new(Left: left, Middle: middle, Right: right, Nested: folded, Flat: flat));
                        }
                    }

                    if ((1 == trailing.SupportCount)
                        && TryReadCommutation(charge: charge, left: left, right: ((int)trailing.Keys[0]), value: out var joined)
                        && TryReadCommutation(charge: charge, left: left, right: middle, value: out var lead)
                        && TryReadCommutation(charge: charge, left: left, right: right, value: out var trail)) {
                        var flat = m_material.Multiply(left: lead, right: trail);

                        if (!comparer.Equals(x: joined, y: flat)) {
                            witnesses.Add(item: new(Left: left, Middle: middle, Right: right, Nested: joined, Flat: flat));
                        }
                    }
                }
            }
        }

        return true;
    }

    // One entry of the derived commutation table, and whether it was derived at all. The material's zero is the one
    // value no candidate can produce, so it names the missing entry without a second table beside this one.
    private bool TryReadCommutation(TValue[] charge, int left, int right, out TValue value) {
        value = charge[((left * m_keyCount) + right)];

        return !m_material.IsZero(value: value);
    }

    /// <summary>
    /// An element: a canonically ordered support of normal-form key and coefficient pairs, with zeros pruned. Dense
    /// indexing is the COMPILED form of that support and lives in the algebra's working buffers, chosen at construction
    /// when the normal-form set is finite.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A default-initialized element is not a member of any algebra; obtain one from
    /// <see cref="PresentedAlgebra{TValue, TOps}.Zero"/>, <see cref="PresentedAlgebra{TValue, TOps}.Identity"/>,
    /// <see cref="PresentedAlgebra{TValue, TOps}.Generator"/>, or an operation.
    /// </para>
    /// <para>
    /// <b>An element belongs to the algebra that built it.</b> Its keys index that algebra's own normal forms and its
    /// tables, so handing one to a different algebra names different words — every element-consuming operation
    /// therefore refuses a foreign element with an <see cref="ArgumentException"/> rather than reading the wrong cell.
    /// The default element is the one exception, because it carries no support at all and so is the zero of whichever
    /// algebra receives it.
    /// </para>
    /// </remarks>
    public readonly struct Element {
        private readonly TValue[]? m_coefficients;
        private readonly long[]? m_keys;
        private readonly PresentedAlgebra<TValue, TOps>? m_owner;

        internal Element(PresentedAlgebra<TValue, TOps> owner, long[] keys, TValue[] coefficients) {
            m_coefficients = coefficients;
            m_keys = keys;
            m_owner = owner;
        }

        /// <summary>Gets the algebra that built this element, or <see langword="null"/> for a default-initialized one,
        /// which is empty and is therefore the zero of every algebra.</summary>
        internal PresentedAlgebra<TValue, TOps>? Owner => m_owner;

        /// <summary>Gets the coefficients, in the same order as <see cref="Keys"/>.</summary>
        public ReadOnlySpan<TValue> Coefficients =>
            ((m_coefficients is null)
                ? default
                : m_coefficients.AsSpan(start: 0, length: SupportCount));
        /// <summary>Gets the support's normal-form keys, ascending.</summary>
        public ReadOnlySpan<long> Keys =>
            ((m_keys is null)
                ? default
                : m_keys.AsSpan(start: 0, length: SupportCount));
        /// <summary>Gets the number of nonzero coefficients.</summary>
        public int SupportCount =>
            ((m_coefficients is null)
                ? 0
                : m_coefficients.Length);

        /// <summary>Gets the coefficient of one normal form.</summary>
        /// <param name="key">The normal form's key.</param>
        /// <returns>The coefficient, or the owning material's zero when the key is outside the support. An owner-less
        /// default element has no material and returns <see langword="default"/>; element-consuming operations interpret
        /// that empty support as their own material's zero.</returns>
        public TValue this[long key] {
            get {
                var keys = Keys;
                var low = 0;
                var high = keys.Length;

                while (low < high) {
                    var middle = ((low + high) >> 1);
                    var probe = keys[middle];

                    if (probe == key) { return m_coefficients![middle]; }

                    if (probe < key) { low = (middle + 1); } else { high = middle; }
                }

                return ((m_owner is null)
                    ? default!
                    : m_owner.m_material.Zero);
            }
        }
    }
}
