// Generated by `puck shaders generate` from the SDF instruction set's C# model; regenerate it, never edit it.
#ifndef SDF_ISA_HLSLI
#define SDF_ISA_HLSLI

// The instruction-set version and the report word the version handshake dispatches with.
#define SDF_ISA_VERSION        2u
#define SDF_ISA_REPORT_REQUEST 0x53444656u

// Puck.SignedDistance.SdfOp.
#define SDF_OP_RESET_POINT       0u
#define SDF_OP_TRANSLATE         1u
#define SDF_OP_ROTATE            2u
#define SDF_OP_SCALE             3u
#define SDF_OP_TRANSFORM_DYNAMIC 4u
#define SDF_OP_ROTATE_PLANE      5u
#define SDF_OP_ELONGATE          8u
#define SDF_OP_SHAPE_BLEND       9u
#define SDF_OP_REPEAT            11u
#define SDF_OP_REPEAT_LIMITED    12u
#define SDF_OP_ONION             16u
#define SDF_OP_DILATE            17u
#define SDF_OP_WALLPAPER_FOLD    18u
#define SDF_OP_LOG_SPHERE        21u
#define SDF_OP_CELL_JITTER       22u
#define SDF_OP_REPEAT_POLAR      23u
#define SDF_OP_DISPLACE          24u
#define SDF_OP_DOMAIN_WARP       25u
#define SDF_OP_SYMMETRY_PLANE    26u
#define SDF_OP_PUSH_FIELD        27u
#define SDF_OP_POP_FIELD         28u
#define SDF_OP_NOISE_DISPLACE    29u
#define SDF_OP_AXIAL_PROFILE     30u
#define SDF_OP_SHEAR             31u
#define SDF_OP_GAUSSIAN_PUSH     32u
#define SDF_OP_LANE_ERODE        34u
#define SDF_OP_CELL_DISPLACE     35u

// Puck.SignedDistance.SdfShapeType.
#define SDF_SHAPE_BOX                 0u
#define SDF_SHAPE_CAPSULE             1u
#define SDF_SHAPE_SPHERE              2u
#define SDF_SHAPE_TORUS               3u
#define SDF_SHAPE_CYLINDER            4u
#define SDF_SHAPE_PLANE               5u
#define SDF_SHAPE_VESICA              7u
#define SDF_SHAPE_ROUNDED_RECTANGLE   8u
#define SDF_SHAPE_REGULAR_POLYGON     9u
#define SDF_SHAPE_STAR                10u
#define SDF_SHAPE_ROUND_CONE          11u
#define SDF_SHAPE_TRAPEZOID           12u
#define SDF_SHAPE_ELLIPSE             13u
#define SDF_SHAPE_SCREEN_SLAB         14u
#define SDF_SHAPE_GLYPH               15u
#define SDF_SHAPE_SAMPLED_REGION      16u
#define SDF_SHAPE_CHAMFERED_RECTANGLE 17u
#define SDF_SHAPE_SUPERELLIPSOID      18u
#define SDF_SHAPE_CONVEX_POLYGON      19u
#define SDF_SHAPE_SWEEP               20u
#define SDF_SHAPE_PATH                21u

// Puck.SignedDistance.SdfBlendOp.
#define SDF_BLEND_UNION                0u
#define SDF_BLEND_SMOOTH_UNION         1u
#define SDF_BLEND_SUBTRACTION          2u
#define SDF_BLEND_INTERSECTION         3u
#define SDF_BLEND_XOR                  4u
#define SDF_BLEND_SMOOTH_INTERSECTION  5u
#define SDF_BLEND_SMOOTH_SUBTRACTION   6u
#define SDF_BLEND_CHAMFER_UNION        7u
#define SDF_BLEND_CHAMFER_INTERSECTION 8u
#define SDF_BLEND_CHAMFER_SUBTRACTION  9u
#define SDF_BLEND_GROOVE_UNION         10u
#define SDF_BLEND_PIPE_UNION           11u
#define SDF_BLEND_MORPH                12u
#define SDF_BLEND_GROOVE_SUBTRACTION   13u
#define SDF_BLEND_PIPE_SUBTRACTION     14u
#define SDF_BLEND_STAIRS_UNION         15u
#define SDF_BLEND_STAIRS_SUBTRACTION   16u

// Puck.SignedDistance.SdfLift.
#define SDF_LIFT_REVOLVE 0u
#define SDF_LIFT_EXTRUDE 1u

// Puck.SignedDistance.SdfNoiseFlavor.
#define SDF_NOISE_WHITE    0u
#define SDF_NOISE_BLUE     1u
#define SDF_NOISE_GAUSSIAN 2u

// Puck.SignedDistance.SdfPolarAxis.
#define SDF_POLAR_AXIS_X 0u
#define SDF_POLAR_AXIS_Y 1u
#define SDF_POLAR_AXIS_Z 2u

// Puck.SignedDistance.SdfWallpaperGroup.
#define SDF_WPG_P1   0u
#define SDF_WPG_P2   1u
#define SDF_WPG_PM   2u
#define SDF_WPG_PG   3u
#define SDF_WPG_CM   4u
#define SDF_WPG_PMM  5u
#define SDF_WPG_PMG  6u
#define SDF_WPG_PGG  7u
#define SDF_WPG_CMM  8u
#define SDF_WPG_P4   9u
#define SDF_WPG_P4M  10u
#define SDF_WPG_P4G  11u
#define SDF_WPG_P3   12u
#define SDF_WPG_P3M1 13u
#define SDF_WPG_P31M 14u
#define SDF_WPG_P6   15u
#define SDF_WPG_P6M  16u

// Puck.SignedDistance.SdfWallpaperPlane.
#define SDF_WPG_PLANE_XZ 0u
#define SDF_WPG_PLANE_XY 1u
#define SDF_WPG_PLANE_YZ 2u

// Shape-lane flags on a ShapeBlend instruction's header.
#define SDF_SHAPE_DETAIL_FLAG       0x80000000u
#define SDF_SHAPE_NO_SECONDARY_FLAG 0x40000000u

// Bound modes, and the flags packed beside them in bound, segment and instance records.
#define SDF_BOUND_NONE                      0u
#define SDF_BOUND_STATIC                    1u
#define SDF_BOUND_DYNAMIC                   2u
#define SDF_SEGMENT_RIGID_PLAN              0x80000000u
#define SDF_INSTANCE_SHADOW_TRANSPARENT_BIT 0x80000000u
#define SDF_INSTANCE_SEGMENT_END_MASK       0x7FFFFFFFu

// The rigid-leaf plan.
#define SDF_RIGID_LEAF_IDENTITY_ROTATION 0x80000000u
#define SDF_RIGID_LEAF_FOLDED            0x40000000u
#define SDF_RIGID_LEAF_MAX_FOLD_RUN      8u

// Program capacities, strides and floors.
#define SDF_MAX_INSTANCES              65536u
#define SDF_MATERIAL_VECTORS_PER_ENTRY 20u
#define SDF_GRID_HEADER_WORDS          16u
#define SDF_GRID_MAX_DIM               64u
#define SDF_MAX_FIELD_SCOPE_DEPTH      1u
#define SDF_FLARE_MIN_SCALE            0.05
#define SDF_LANE_ERODE_RAGGED_AMOUNT   0.35
#define SDF_SCREEN_MATERIAL            65535

#endif // SDF_ISA_HLSLI
