using System.Buffers.Binary;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Puck.Abstractions.Gpu;
using Puck.SignedDistance;

namespace Puck.SdfVm;

/// <summary>
/// Generates <see cref="FileName"/>, the kernels' declarations of the SDF instruction set: every enum an instruction word
/// carries, the packed-layout constants the interpreter decodes words with, the screen count,
/// the sampler filters a screen's row indexes the engine's samplers by, and where each row of the environment lies in a
/// pass block's environment array, with its light kinds, and the visibility record's identity fields, transform-slot
/// sentinel and currency rule (<see cref="SdfVisibility"/>). Every value is read from the C# model, never
/// transcribed, and an enum member's name is its C# name in upper snake case after the enum's prefix (<see cref="SdfOp.ResetPoint"/> is <c>SDF_OP_RESET_POINT</c>), so a new member reaches the kernels by
/// regenerating. <c>puck shaders generate</c> writes the file beside the kernels and <c>--check</c> fails on drift.
/// <para>The text is a pure function of the model: the same build generates the same bytes, with LF line endings, on
/// every host.</para>
/// <para>The instruction set's fingerprint (<see cref="DescribeFingerprint"/>) names its whole encoding: the generated
/// text, which states every enum, lane accessor, stride and constant the kernels read, and the encoding the model's
/// builder and packer produce (<see cref="SdfEncodingProbe.Describe()"/>: where every field, bitfield and table entry
/// lands). <c>puck shaders generate</c> records it (<see cref="SdfIsaFingerprint"/>, read as <see cref="Fingerprint"/>).
/// The SDF kernels' interfaces carry it as their stamp (<see cref="Stamp"/>, <see cref="SdfWorldInterfaces"/>), so every kernel's bytecode reflects the
/// instruction set it was compiled against, and a reload refuses kernels whose stamp is not this host's.</para>
/// </summary>
public static class SdfIsaHlsl {
    /// <summary>The file name of the generated include, which sits with the other generated declarations in
    /// <c>Assets/Shaders/Sdf/isa</c>.</summary>
    public const string FileName = "sdf-isa.hlsli";

    private const string Guard = "SDF_ISA_HLSLI";

    /// <summary>The repository-relative path of the generated source that records <see cref="Fingerprint"/>.</summary>
    public const string FingerprintSourcePath = "src/Puck.SdfVm/SdfIsaFingerprint.cs";

    /// <summary>Gets the fingerprint of this build's instruction set, as <c>puck shaders generate</c> recorded it when it
    /// wrote the kernels' declarations (<see cref="SdfIsaFingerprint.Value"/>), so a host names its instruction set
    /// without describing the encoding. <c>--check</c> holds the record to <see cref="DescribeFingerprint"/>.</summary>
    public static uint Fingerprint => SdfIsaFingerprint.Value;
    /// <summary>Gets the stamp the SDF kernels' interfaces carry for this build's instruction set: <see cref="StampOf"/>
    /// of <see cref="Fingerprint"/>.</summary>
    public static string Stamp { get; } = StampOf(fingerprint: Fingerprint);

    /// <summary>Returns the fingerprint of the model's instruction set: <see cref="FingerprintOf"/> of the generated
    /// include and the model's described encoding. It moves with any member, value, lane or constant the kernels read
    /// from the model, and with any change to where the builder puts a field or the packer a word.</summary>
    /// <returns>The fingerprint.</returns>
    public static uint DescribeFingerprint() =>
        FingerprintOf(
            encoding: SdfEncodingProbe.Describe(),
            include: Generate()
        );
    /// <summary>Generates the source that records a fingerprint as <see cref="SdfIsaFingerprint.Value"/>.</summary>
    /// <param name="fingerprint">The fingerprint (<see cref="DescribeFingerprint"/>).</param>
    /// <returns>The C# text.</returns>
    public static string GenerateFingerprintSource(uint fingerprint) =>
        string.Create(
            provider: CultureInfo.InvariantCulture,
            handler: $$"""
                // Generated by `puck shaders generate` from the SDF instruction set's C# model; regenerate it, never edit it.
                namespace Puck.SdfVm;

                /// <summary>The fingerprint of the instruction set this build's kernels are declared against
                /// (<see cref="SdfIsaHlsl.DescribeFingerprint"/>), recorded when <c>puck shaders generate</c> wrote the
                /// declarations.</summary>
                public static class SdfIsaFingerprint {
                    /// <summary>The fingerprint.</summary>
                    public const uint Value = 0x{{fingerprint:X8}}u;
                }

                """
        );
    /// <summary>Generates the include.</summary>
    /// <returns>The HLSL text.</returns>
    /// <exception cref="InvalidOperationException">Two declarations would share one HLSL name.</exception>
    public static string Generate() => Declare();
    /// <summary>Returns the fingerprint of an instruction set: the first four bytes, little-endian, of the SHA-256 of the
    /// UTF-8 text of its include, a NUL, and its described encoding.</summary>
    /// <param name="include">The include's text (<see cref="Generate"/>).</param>
    /// <param name="encoding">The encoding's description (<see cref="SdfEncodingProbe.Describe()"/>).</param>
    /// <returns>The fingerprint.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="include"/> or <paramref name="encoding"/> is
    /// <see langword="null"/>.</exception>
    public static uint FingerprintOf(string include, string encoding) {
        ArgumentNullException.ThrowIfNull(argument: include);
        ArgumentNullException.ThrowIfNull(argument: encoding);

        return BinaryPrimitives.ReadUInt32LittleEndian(source: SHA256.HashData(source: Encoding.UTF8.GetBytes(s: $"{include}\0{encoding}")));
    }
    /// <summary>Returns the interface stamp (<see cref="Puck.Shaders.ShaderInterface.Stamp"/>) of an instruction set:
    /// <c>Isa</c> followed by its fingerprint in eight upper-case hexadecimal digits.</summary>
    /// <param name="fingerprint">The instruction set's fingerprint.</param>
    /// <returns>The stamp.</returns>
    public static string StampOf(uint fingerprint) =>
        string.Create(
            provider: CultureInfo.InvariantCulture,
            handler: $"Isa{fingerprint:X8}"
        );

    // Every declaration the include makes.
    private static string Declare() {
        var declarations = new Declarations();

        declarations.Members<SdfOp>(prefix: "SDF_OP");
        declarations.Members<SdfShapeType>(prefix: "SDF_SHAPE");
        declarations.Members<SdfBlendOp>(prefix: "SDF_BLEND");
        declarations.Members<SdfLift>(prefix: "SDF_LIFT");
        declarations.Members<SdfNoiseFlavor>(prefix: "SDF_NOISE");
        declarations.Members<SdfCellMode>(prefix: "SDF_CELL_MODE");
        declarations.Members<SdfAxis>(prefix: "SDF_AXIS");
        declarations.Members<SdfPlane>(prefix: "SDF_PLANE");
        declarations.Members<SdfWallpaperGroup>(prefix: "SDF_WPG");
        declarations.Section(title: "The program header, the first vector of the word stream: the vectors before the instruction headers, and each lane's accessor.");
        declarations.Count(name: "SDF_PROGRAM_HEADER_VECTORS", value: SdfProgram.ProgramHeaderVectors);
        declarations.Lane(lane: SdfProgram.ProgramInstructionCountLane, name: "SDF_PROGRAM_INSTRUCTION_COUNT");
        declarations.Lane(lane: SdfProgram.ProgramMaterialCountLane, name: "SDF_PROGRAM_MATERIAL_COUNT");
        declarations.Lane(lane: SdfProgram.ProgramDataOffsetLane, name: "SDF_PROGRAM_DATA_OFFSET");
        declarations.Lane(lane: SdfProgram.ProgramMaterialOffsetLane, name: "SDF_PROGRAM_MATERIAL_OFFSET");
        declarations.Section(title: "An instruction: its header's lane accessors, and the data vectors each instruction holds in the data table.");
        declarations.Lane(lane: SdfProgram.InstructionOpLane, name: "SDF_INSTRUCTION_OP");
        declarations.Lane(lane: SdfProgram.InstructionShapeLane, name: "SDF_INSTRUCTION_SHAPE");
        declarations.Lane(lane: SdfProgram.InstructionBlendLane, name: "SDF_INSTRUCTION_BLEND");
        declarations.Lane(lane: SdfProgram.InstructionMaterialLane, name: "SDF_INSTRUCTION_MATERIAL");
        declarations.Count(name: "SDF_INSTRUCTION_DATA_VECTORS", value: SdfProgram.InstructionDataVectors);
        declarations.Section(title: "The bound records and the directories: a record's vectors, a directory's header vectors, and its header's lane accessors.");
        declarations.Count(name: "SDF_BOUND_RECORD_VECTORS", value: SdfProgram.BoundRecordVectors);
        declarations.Count(name: "SDF_DIRECTORY_HEADER_VECTORS", value: SdfProgram.DirectoryHeaderVectors);
        declarations.Lane(lane: SdfProgram.SegmentCountLane, name: "SDF_SEGMENT_COUNT");
        declarations.Lane(lane: SdfProgram.SegmentStepScaleLane, name: "SDF_SEGMENT_STEP_SCALE");
        declarations.Lane(lane: SdfProgram.SegmentRigidPlanLane, name: "SDF_SEGMENT_RIGID_PLAN_OFFSET");
        declarations.Lane(lane: SdfProgram.InstanceCountLane, name: "SDF_INSTANCE_COUNT");
        declarations.Lane(lane: SdfProgram.InstancePartProgramsLane, name: "SDF_INSTANCE_PART_PROGRAMS");
        declarations.Lane(lane: SdfProgram.InstanceFlagsLane, name: "SDF_INSTANCE_FLAGS");
        declarations.Lane(lane: SdfProgram.WorldSegmentCountLane, name: "SDF_WORLD_SEGMENT_COUNT");
        declarations.Section(title: "Shape-lane flags and the type mask on a ShapeBlend instruction's header.");
        declarations.Bits(
            name: "SDF_SHAPE_DETAIL_FLAG",
            value: SdfProgram.ShapeDetailFlag
        );
        declarations.Bits(
            name: "SDF_SHAPE_NO_SECONDARY_FLAG",
            value: SdfProgram.ShapeNoSecondaryFlag
        );
        declarations.Bits(
            name: "SDF_SHAPE_TYPE_MASK",
            value: SdfProgram.ShapeTypeMask
        );
        declarations.Section(title: "Bound modes, and the flags and masks packed beside them in bound, segment and instance records.");
        declarations.Count(
            name: "SDF_BOUND_NONE",
            value: SdfProgram.BoundModeNone
        );
        declarations.Count(
            name: "SDF_BOUND_STATIC",
            value: SdfProgram.BoundModeStatic
        );
        declarations.Count(
            name: "SDF_BOUND_DYNAMIC",
            value: SdfProgram.BoundModeDynamic
        );
        declarations.Bits(
            name: "SDF_SEGMENT_RIGID_PLAN",
            value: SdfProgram.SegmentRigidPlanFlag
        );
        declarations.Bits(
            name: "SDF_SEGMENT_BOUND_MASK",
            value: SdfProgram.SegmentBoundModeMask
        );
        declarations.Bits(
            name: "SDF_INSTANCE_SHADOW_TRANSPARENT_BIT",
            value: SdfProgram.ShadowTransparentInstanceFlag
        );
        declarations.Bits(
            name: "SDF_INSTANCE_CAMERA_HIDDEN_BIT",
            value: SdfProgram.CameraHiddenInstanceFlag
        );
        declarations.Bits(
            name: "SDF_INSTANCE_SEGMENT_END_MASK",
            value: SdfProgram.SegmentEndMask
        );
        declarations.Bits(
            name: "SDF_NO_DETAIL_SHAPES_FLAG",
            value: SdfProgram.NoDetailShapesFlag
        );
        declarations.Section(title: "The rigid-leaf plan.");
        declarations.Bits(
            name: "SDF_RIGID_LEAF_IDENTITY_ROTATION",
            value: SdfProgram.RigidLeafIdentityRotationFlag
        );
        declarations.Bits(
            name: "SDF_RIGID_LEAF_FOLDED",
            value: SdfProgram.RigidLeafFoldedFlag
        );
        declarations.Bits(
            name: "SDF_RIGID_LEAF_SHAPE_MASK",
            value: SdfProgram.RigidLeafShapeMask
        );
        declarations.Count(
            name: "SDF_RIGID_LEAF_MAX_FOLD_RUN",
            value: SdfProgram.RigidLeafMaxFoldRun
        );
        declarations.Section(title: "The sampled-region shape's packed dims.");
        declarations.Bits(
            name: "SDF_SAMPLED_REGION_DIM_MASK",
            value: SdfProgramBuilder.SampledRegionDimMask
        );
        declarations.Section(title: "Program capacities, strides and floors.");
        declarations.Count(
            name: "SDF_MAX_INSTANCES",
            value: SdfProgramBuilder.MaxInstances
        );
        declarations.Count(
            name: "SDF_MATERIAL_VECTORS_PER_ENTRY",
            value: SdfProgram.MaterialVectorsPerEntry
        );
        declarations.Count(
            name: "SDF_GRID_HEADER_WORDS",
            value: SdfInstanceGrid.HeaderWords
        );
        declarations.Count(
            name: "SDF_GRID_MAX_DIM",
            value: SdfInstanceGrid.MaxDimension
        );
        declarations.Count(
            name: "SDF_MAX_FIELD_SCOPE_DEPTH",
            value: SdfProgramBuilder.MaxFieldScopeDepth
        );
        declarations.Real(
            name: "SDF_FLARE_MIN_SCALE",
            value: SdfProgramBuilder.FlareMinScale
        );
        declarations.Real(
            name: "SDF_LANE_ERODE_RAGGED_AMOUNT",
            value: SdfProgramBuilder.LaneErodeRaggedAmount
        );
        declarations.Signed(
            name: "SDF_SCREEN_MATERIAL",
            value: SdfProgramBuilder.ScreenMaterialId
        );
        declarations.Count(
            name: "SDF_MAX_SCREEN_SURFACES",
            value: SdfProgramBuilder.MaxScreenSurfaces
        );
        declarations.Real(
            name: "SDF_MINIMUM_NEAR",
            value: SdfFrameBlock.MinimumNear
        );
        declarations.Count(
            name: "SDF_NOISE_PERIOD_CELLS",
            value: SdfVolume.NoisePeriodCells
        );
        declarations.Members<GpuSamplerFilter>(prefix: "SDF_FILTER");
        declarations.Members<GridOverlayFlags>(prefix: "SDF_GRID");
        declarations.Section(title: "The environment's rows in the pass block's environment array (SdfEnvironment) and its light kinds.");
        declarations.Count(name: "SDF_ENV_ROW_COUNT", value: SdfEnvironment.RowCount);
        declarations.Count(name: "SDF_ENV_CONTROL_ROW", value: SdfEnvironment.ControlRow);
        declarations.Count(name: "SDF_ENV_LIGHTS_ROW", value: SdfEnvironment.LightsRow);
        declarations.Count(name: "SDF_ENV_ROWS_PER_LIGHT", value: SdfEnvironment.RowsPerLight);
        declarations.Count(name: "SDF_ENV_MAX_LIGHTS", value: SdfEnvironment.MaxLights);
        declarations.Count(name: "SDF_ENV_CURVATURE_ROW", value: SdfEnvironment.CurvatureRow);
        declarations.Count(name: "SDF_ENV_SKY_CONTROL_ROW", value: SdfEnvironment.SkyControlRow);
        declarations.Count(name: "SDF_ENV_SKY_STOPS_ROW", value: SdfEnvironment.SkyStopsRow);
        declarations.Count(name: "SDF_ENV_MAX_SKY_STOPS", value: SdfEnvironment.MaxSkyStops);
        declarations.Count(name: "SDF_ENV_STARS_ROW", value: SdfEnvironment.StarsRow);
        declarations.Count(name: "SDF_ENV_TWINKLE_ROW", value: SdfEnvironment.TwinkleRow);
        declarations.Count(name: "SDF_ENV_CLOUDS_ROW", value: SdfEnvironment.CloudsRow);
        declarations.Count(name: "SDF_ENV_SOFTBOX_CONTROL_ROW", value: SdfEnvironment.SoftboxControlRow);
        declarations.Count(name: "SDF_ENV_SOFTBOXES_ROW", value: SdfEnvironment.SoftboxesRow);
        declarations.Count(name: "SDF_ENV_ROWS_PER_SOFTBOX", value: SdfEnvironment.RowsPerSoftbox);
        declarations.Count(name: "SDF_ENV_MAX_SOFTBOXES", value: SdfEnvironment.MaxSoftboxes);
        declarations.Count(name: "SDF_ENV_HORIZON_LOW_ROW", value: SdfEnvironment.HorizonLowRow);
        declarations.Count(name: "SDF_ENV_HORIZON_HIGH_ROW", value: SdfEnvironment.HorizonHighRow);
        declarations.Members<SdfLightKind>(prefix: "SDF_LIGHT");
        declarations.Members<SdfVisibilityKind>(prefix: "SDF_VISIBILITY_KIND");
        declarations.Section(title: "The visibility record's identity fields, transform-slot lane and currency box (SdfVisibility).");
        declarations.Count(name: "SDF_VISIBILITY_KIND_SHIFT", value: SdfVisibility.KindShift);
        declarations.Bits(name: "SDF_VISIBILITY_SOURCE_MASK", value: SdfVisibility.SourceMask);
        declarations.Signed(name: "SDF_TRANSFORM_SLOT_NONE", value: SdfProgram.NoDynamicTransformSlot);
        declarations.Count(name: "SDF_VISIBILITY_BOX_EDGE", value: SdfVisibility.BoxEdgePixels);
        declarations.Expression(name: "SDF_VISIBILITY_CURRENT(pixel, bounds)", value: SdfVisibility.CurrencyHlsl);

        return declarations.Text();
    }
    // A C# member name's HLSL spelling: upper snake case, with a word break before an upper-case letter that follows a
    // lower-case one, or that starts a new word after an upper-case letter or a digit (P4M stays P4M, LogSphere becomes
    // LOG_SPHERE, F2MinusF1 becomes F2_MINUS_F1).
    private static string UpperSnake(string name) {
        var text = new StringBuilder(capacity: (name.Length * 2));

        for (var index = 0; (index < name.Length); index++) {
            var character = name[index];

            if (
                (index > 0) &&
                char.IsUpper(c: character) &&
                (char.IsLower(c: name[(index - 1)]) || (
                    (char.IsUpper(c: name[(index - 1)]) || char.IsAsciiDigit(c: name[(index - 1)])) &&
                    ((index + 1) < name.Length) &&
                    char.IsLower(c: name[(index + 1)])
                ))
            ) {
                text.Append(value: '_');
            }

            text.Append(value: char.ToUpperInvariant(c: character));
        }

        return text.ToString();
    }

    private sealed class Declarations {
        private readonly List<(string Name, string Value)> m_group = [];
        private readonly HashSet<string> m_names = new(comparer: StringComparer.Ordinal);
        private readonly StringBuilder m_text = new();

        public Declarations() {
            Line(line: "// Generated by `puck shaders generate` from the SDF instruction set's C# model; regenerate it, never edit it.");
            Line(line: $"#ifndef {Guard}");
            Line(line: $"#define {Guard}");
        }

        private void Define(string name, string value) {
            if (!m_names.Add(item: name.Split(separator: '(')[0])) {
                throw new InvalidOperationException(message: $"Two SDF instruction-set declarations are both named {name}.");
            }

            m_group.Add(item: (name, value));
        }
        private void Flush() {
            var width = m_group.Max(selector: static entry => entry.Name.Length);

            foreach (var (name, value) in m_group) {
                m_text.Append(value: $"#define {name.PadRight(totalWidth: width)} {value}").Append(value: '\n');
            }

            m_group.Clear();
        }
        // A group of defines is aligned when the next non-define line ends it.
        private void Line(string line) {
            if (m_group.Count != 0) {
                Flush();
            }

            m_text.Append(value: line).Append(value: '\n');
        }

        public void Bits(string name, uint value) => Define(
            name: name,
            value: $"0x{value.ToString(
                format: "X8",
                provider: CultureInfo.InvariantCulture
            )}u"
        );
        public void Expression(string name, string value) => Define(
            name: name,
            value: value
        );
        public void Lane(string name, int lane) {
            ArgumentOutOfRangeException.ThrowIfNegative(value: lane);
            ArgumentOutOfRangeException.ThrowIfGreaterThan(
                other: 3,
                value: lane
            );
            Define(
                name: $"{name}(v)",
                value: $"((v).{"xyzw"[lane]})"
            );
        }
        public void Count(string name, long value) {
            ArgumentOutOfRangeException.ThrowIfNegative(value: value);
            ArgumentOutOfRangeException.ThrowIfGreaterThan(
                other: uint.MaxValue,
                value: value
            );
            Define(
                name: name,
                value: $"{value.ToString(provider: CultureInfo.InvariantCulture)}u"
            );
        }
        public void Members<T>(string prefix) where T : struct, Enum {
            Section(title: $"{typeof(T).FullName}.");

            foreach (var member in Enum.GetValues<T>()) {
                Count(
                    name: $"{prefix}_{UpperSnake(name: member.ToString())}",
                    value: Convert.ToInt64(
                        provider: CultureInfo.InvariantCulture,
                        value: member
                    )
                );
            }
        }
        public void Real(string name, float value) {
            if (!float.IsFinite(f: value)) {
                throw new ArgumentOutOfRangeException(
                    actualValue: value,
                    message: "An HLSL literal must be finite.",
                    paramName: nameof(value)
                );
            }

            var spelling = value.ToString(
                format: "R",
                provider: CultureInfo.InvariantCulture
            );

            Define(
                name: name,
                value: ((spelling.AsSpan().IndexOfAny(values: ".E") < 0)
                    ? (spelling + ".0")
                    : spelling)
            );
        }
        public void Section(string title) {
            Line(line: "");
            Line(line: $"// {title}");
        }
        public void Signed(string name, int value) => Define(
            name: name,
            value: value.ToString(provider: CultureInfo.InvariantCulture)
        );
        public string Text() {
            Line(line: "");
            Line(line: $"#endif // {Guard}");

            return m_text.ToString();
        }
    }
}
