// Generated by `puck shaders generate` from the SDF instruction set's C# model; regenerate it, never edit it.
namespace Puck.SdfVm;

/// <summary>The fingerprint of the instruction set this build's kernels are declared against
/// (<see cref="SdfIsaHlsl.DescribeFingerprint"/>), recorded when <c>puck shaders generate</c> wrote the
/// declarations.</summary>
public static class SdfIsaFingerprint {
    /// <summary>The fingerprint.</summary>
    public const uint Value = 0x0897E421u;
}
